-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"44269 Gitara",
	"62977 GITARA",
	"About You By The 1780242398856",
	"Andra And The BackBone - Sempurna Lyre.Mid",
	"Arranged By @KAyuna-Guitar - 夜に駆ける",
	"Binks Rum Binks Sake 1780241727588",
	"Bleach - Ranbu No Melody (OP 13)",
	"Can'T Help Falling In Love - Elvis Presley",
	"Chris Isaakwicked Game",
	"Clair-De-Lune-Debussy",
	"Come As You Are - Nirvana (Guitar Tab)",
	"Composed By Yu-Peng Chen Arranged By Devon Sebastian K - Liyue Harbor Song No. 4",
	"Ed Sheeran Thinking Out Loud",
	"Kembali Pulang Suara Kayu Ft Feby Putri BY SurrealFlux 1780242827893",
	"Mayonnaise - Synestheisa [MIDIfind.Com]",
	"Nirvana - Do Re Mi",
	"Oasis - Married With Children",
	"Radiohead - No Surprises",
	"S.T.A.L.K.E.R - Guitar Music From Stalker (3) [MIDIfind.Com]",
	"SHINING",
	"Tarot Feast 1780242551896",
}