-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"-",
	"- SILLY FOOLS OFFICIAL MV",
	"44269 Gitara",
	"62977 GITARA",
	"About You By The 1780242398856",
	"Acrophobia - Penguin Villa",
	"American Football - Never Meant (1)",
	"Andra And The BackBone - Sempurna Lyre.Mid",
	"Arranged By @KAyuna-Guitar - 夜に駆ける",
	"Batta - Chase",
	"Batta - Chase-Jojo",
	"Batta - Chase-JojoDr",
	"Beabadoobee - The Way Things Go",
	"Beabadoobee-The Perfect Pair-05-27-2023-Acoustic Guitar",
	"Bertaut - Guitar",
	"Binks Rum Binks Sake 1780241727588",
	"Black Sabbath - NIB Bass",
	"Black Sabbath - NIB Guitar",
	"Bleach - Ranbu No Melody (OP 13)",
	"Bocchi The Rock - Ano Bando",
	"Bocchi The Rock - Seisyun Complex",
	"Bodyslam - (1)",
	"Bodyslam -FUULL",
	"Bodyslam -Yapid",
	"Buddy Holly - Weezer",
	"Can'T Help Falling In Love - Elvis Presley",
	"Carabao -",
	"Chris Isaakwicked Game",
	"Cinderella - Tattoo Colour",
	"Clair-De-Lune-Debussy",
	"Clarion - Hello Juliet",
	"Come As You Are - Nirvana (Guitar Tab)",
	"Composed By Yu-Peng Chen Arranged By Devon Sebastian K - Liyue Harbor Song No. 4",
	"Creed - One Last Breath",
	"Deep Purple - Smoke On The Water-Drum Kit",
	"Deftones - Be Quiet And Drive Far AwayBass",
	"Deftones - Be Quiet And Drive Far AwayGuitar",
	"Dire Straits - Sultans Of Swing",
	"Dorian Concept - 'Hide",
	"Dumb Ways To Die",
	"Dying Light - Horizon",
	"Ed Sheeran Thinking Out Loud",
	"Forwards",
	"Forwards.Mp3",
	"Green Day - Good Riddance [MIDIfind.Com]",
	"Gto - GTO Opening 1 Drivers High",
	"Hers - Harvey",
	"Hill Billy Jim -[AudioTrimmer",
	"Hill Billy Jim (1)",
	"Hillbilly Jim Promo [1985-04-20] 320k",
	"Hokuto No Ken - You Wa Shock Full Version 2",
	"Holy-Diver",
	"I Just Threw Out The Love Of My Dreams - Weezer",
	"Iqro - Raim Laode",
	"Iqro - Raim Laode Guitar",
	"Jane! - The Long Faces",
	"JOJOs - Roundabout-Electric Bass, Electric Bass",
	"JOJOs - Roundabout-Electric Guitar, Electric Guitar",
	"JOJOs - RoundaboutBass",
	"JOJOs - RoundaboutGuitar",
	"Just The Two Of Us.",
	"Justin Bieber - Beauty And A Beat WWW.MIDISFREE.COM.Mid",
	"Karen Aoki Daisuke Hasegawa - Great Days Jojos Bizarre Adventure Diamond Is Unbreakable Op3",
	"Kembali Pulang Suara Kayu Ft Feby Putri BY SurrealFlux 1780242827893",
	"LArcenCiel - Drivers High",
	"Led Zeppelin - Stairway To Heaven - Fingerstyle",
	"Linkin Park - Numb Fingerstyle",
	"Loso -",
	"Loso - (1)",
	"Mac Demarco - Freaking Out The Neighborhood",
	"Mac Demarco - Freaking Out The Neighborhood (1)",
	"Made In Thailand, Made In USA",
	"Mayonnaise - Synestheisa [MIDIfind.Com]",
	"Misc Covers-Is It Really You (Acoustic VER.) By Loathe-07-04-2026",
	"Moderndog -",
	"Nirvana - Do Re Mi",
	"Nirvana - Rape Me",
	"NONT TANONT - โต๊ะริม (Melt)",
	"Nujabes MINMI - Shiki No Uta",
	"Oasis - Married With Children",
	"Paradox - Official MV",
	"Paradox - Official MV-Drum Kit (1)",
	"Pixies - Where Is My Mind",
	"Plastic Tree - Kuuchu Buranko-Electric Guitar",
	"PT Adamczyk Olga Jankowska Cyberpunk 2077 - Never Fade Away SAMURAI Cover Guitar Solo",
	"Radiohead - No Surprises",
	"RaunchyGuitar",
	"Ring-Around-The-Rosie",
	"Roundabout- Bass Only",
	"S.T.A.L.K.E.R - Guitar Music From Stalker (3) [MIDIfind.Com]",
	"Sailor (1)",
	"Samurai - Never Fade Away",
	"SHINING",
	"Silly Fools -",
	"Silly Fools - - Silly Fools Lyrics Audio",
	"Silly Fools - Kid Hord(1)",
	"Silly Fools -Cant Fight",
	"Slot Machine -",
	"Smash Mouth - All Star",
	"Smash Mouth - Walkin On The Sun",
	"Smashing Pumpkins - Luna",
	"Smile Buffalo -",
	"Solitude Is Bliss - Just One Thing",
	"Stone Metal Fire -",
	"Sunroof - Nicky Youre, Dazy",
	"Surf Curse - FreaksChorus",
	"Surf Curse - FreaksLead",
	"Tarot Feast 1780242551896",
	"The Beatles - Dont Let Me Down",
	"The Beatles - Here Comes The Sun",
	"The Beatles - Let It Be",
	"The Cure - Boys Dont Cry-Electric Guitar",
	"The Cure - Boys Dont Cry-Electric Guitar (1)",
	"The Cure - Boys Dont CryF",
	"The Jimi Hendrix Experience - Purple Haze",
	"The Neverminds - The Snow Will Catch Us Once Again",
	"The WORLD - Death Note",
	"Three Man Down - ถ้าเธอรักฉันจริง",
	"Tip Toe - HYBS",
	"Toe - Goodbye Rasgueo",
	"Tsuki (พระจันทร์) - LANDOKMAI",
	"Two Door Cinema Club - Undercover Martyn",
	"Winter Rain - Yented",
	"Wonderless - Acoustic By Pierce The Veil",
	"Yes - Roundabout Bass",
	"You Are My Dream",
	"YTDown Instrumental.Mp3",
	"กลับมา - 2 Days Ago Kids",
	"ก่อน - Moderndog",
	"ก้อนหินละเมอ - Soul After Six",
	"โกหก - Tattoo Colour",
	"ใกล้ - Scrubb",
	"ไกล Musketeer",
	"ของขวัญ - Musketeers [Fingerstyle]",
	"ข้างกัน (City) - Three Man Down Feat ออม TELEx TELEXs",
	"ขาหมู - Tattoo Colour",
	"ขี้หึง - Silly Fools [Fingerstyle]",
	"ความรักทำให้คนตาบอด - Bodyslam",
	"คำบางคำ Sqweez Animal",
	"คุกเข่า - Cocktail",
	"เคย",
	"จันทร์เจ้า Slot Machine",
	"ฉันอยู่ตรงนี้ - Blackhead",
	"ซ่อน(ไม่)หา - Jeff Satur X NONT TANONT",
	"ดาวหางฮัลเลย์ (Halley'S Comet) - Fellow Fellow",
	"ตาสว่าง - โมเดิร์นด็อก [Fingerstyle]",
	"เธอไม่ได้สอนให้ฉันอยู่คนเดียว - SHERRY",
	"นะหน้าทอง - โจอี้ ภูวศิษฐ์",
	"นักมายากล",
	"นางแมว",
	"น้ำลาย (Num Lye) - Silly Fools [Fingerstyle]",
	"น้ำลาย (Num Lye) - Silly Fools [Fingerstyle] (1)",
	"บ้าบอ",
	"เบื่อ",
	"ผิดที่ไว้ใจ Silly Fools",
	"ผู้ถูกเลือกให้ผิดหวัง (Sad Flower) - Reinizra",
	"พิจารณา (Consider) - Musketeers Ft Maiyarap",
	"ไม่บอกเธอ - Bedroom Audio",
	"ไม่มีเธอ",
	"ยาพิษ - Bodyslam (1)",
	"ร (W8) - GENE KASIDIT",
	"รักแรกพบ Tattoo Colour",
	"ฤดูร้อน (Acoustic Ver ) - Paradox",
	"ลมแล้ง - Yew (Summertime) Feat LANDOKMAI",
	"วัดใจ -",
	"วาดไว้ (Recall) - BOWKYLION",
	"วิภาวดี (Vibhavadi) YENTED",
	"สองรัก Zeal",
	"หรือ - Slur",
	"หวาดระแวง",
	"อยากให้เธอลอง Musketeers",
	"อย่าร้องอายเค้า - Tattoo Colour",
	"อยู่ต่อเลยได้ไหม - สิงโต นำโชค",
	"อะไรฉันก็ยอม - SARAN X The BESTS [Fingerstyle]",
	"作曲者：Toby Fox 編曲者：Jugon9187 - 夢と希望",
	"作詞：⽶津⽞師 作曲：⽶津⽞師 Tuning Eb Ab Db Gb Bb Eb - Lemon",
}