-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"-",
	"- EBOLAFull",
	"- Jintara Poonlarp I Tao NgoiOfficial MV",
	"- Jintara Poonlarp I Tao NgoiOfficial MVBass",
	"- Jintara Poonlarp I Tao NgoiOfficial MVGuitar",
	"- SILLY FOOLS OFFICIAL MV",
	"- So Cool",
	"44269 Gitara",
	"62977 GITARA",
	"About You By The 1780242398856",
	"ACDC - Dirty Deeds Done Dirt Cheap",
	"ACDC - Thunderstruck",
	"Acrophobia - Penguin Villa",
	"American Football - Never Meant (1)",
	"Andra And The BackBone - Sempurna Lyre.Mid",
	"Arranged By @KAyuna-Guitar - 夜に駆ける",
	"Ba - Duvet - Rurouni1928s Instrumental Ver",
	"Banes World - Drowsy",
	"Basement - Are You The One",
	"Batta - Chase",
	"Batta - Chase-Jojo",
	"Batta - Chase-JojoDr",
	"Beabadoobee - The Way Things Go",
	"Beabadoobee-The Perfect Pair-05-27-2023-Acoustic Guitar",
	"Bedroom Audio - รกมอสอง [Official Music Video]",
	"Bertaut - Guitar",
	"Binks Rum Binks Sake 1780241727588",
	"Black Sabbath - NIB Bass",
	"Black Sabbath - NIB Guitar",
	"Bleach - Ranbu No Melody (OP 13)",
	"Boa - Duvet Arranged",
	"Bocchi The Rock - Ano Bando",
	"Bocchi The Rock - Seisyun Complex",
	"Bodyslam - (1)",
	"Bodyslam -FUULL",
	"Bodyslam -Yapid",
	"Buddy Holly - Weezer",
	"Callalily - Magbalik (Lyrics) 1768700171923",
	"Callalily - Magbalik (Lyrics) 1768700171923 (1)",
	"Can'T Help Falling In Love - Elvis Presley",
	"Carabao -",
	"Carabao Nang Yam",
	"Chainsmoker Cat - Opening FULL Nanmonee By Wasureranneyo",
	"Chezile - Beanie",
	"Chezile - Run Away",
	"Chezile - Run Awaynobass",
	"Chris Isaakwicked Game",
	"Cinderella - Tattoo Colour",
	"Clair-De-Lune-Debussy",
	"CLAIRE - FLY ME TO THE MOON Neon Genesis Evangelion",
	"Clarion - Hello Juliet",
	"Come As You Are - Nirvana (Guitar Tab)",
	"Composed By Yu-Peng Chen Arranged By Devon Sebastian K - Liyue Harbor Song No. 4",
	"Creed - One Last Breath",
	"CUPSIZE - Poka-Poka 79503343",
	"CUPSIZE - Ты любишь танцевать Vocals Backing Track",
	"D4vd - Here With Me",
	"Daft Punk - Something About Us",
	"Deep Purple - Smoke On The Water-Drum Kit",
	"Deftones - Be Quiet And Drive Far AwayBass",
	"Deftones - Be Quiet And Drive Far AwayGuitar",
	"Deftones - My Own Summer Shove It",
	"Dio - Holy Diver",
	"Dire Straits - Sultans Of Swing",
	"Do Re Mi",
	"Do Re Mi - Nirvana",
	"Do Re Mi (Teste1)",
	"Docter Dance",
	"Dorian Concept - 'Hide",
	"Dumb Ways To Die",
	"Dying Light - Horizon",
	"Ed Sheeran Thinking Out Loud",
	"Etran De LAr - Imouha",
	"Etran De LAr - ImouhaBass",
	"Etran De LAr - ImouhaGuitar",
	"Evanescence - Bring Me To Life Live",
	"Firelake - Dirge For The Planet (S.T.A.L.K.E.R OST) [MIDIfind.Com]",
	"Forwards",
	"Forwards.Mp3",
	"Ginger Root - LorettaBassUploadByGreed",
	"Ginger Root - LorettaGuitarUploadByGreed",
	"Gotye - Somebody That I Used To Know (Ft. Kimbra)",
	"Green Day - Good Riddance [MIDIfind.Com]",
	"Gto - GTO Opening 1 Drivers High",
	"Hers - Harvey",
	"Hers - What Once Was",
	"Hill Billy Jim -[AudioTrimmer",
	"Hill Billy Jim (1)",
	"Hillbilly Jim Promo [1985-04-20] 320k",
	"Hokuto No Ken - You Wa Shock Full Version 2",
	"Holy-Diver",
	"HYBS - Ride",
	"I Just Threw Out The Love Of My Dreams - Weezer",
	"Iqro - Raim Laode",
	"Iqro - Raim Laode Guitar",
	"Jane! - The Long Faces",
	"Jindie - She Makes Me Wanna Die",
	"Joji - SLOW DANCING IN THE DARK",
	"Jojo - Steel Ball Run Johnny Joestar Theme",
	"JOJOs - Roundabout-Electric Bass, Electric Bass",
	"JOJOs - Roundabout-Electric Guitar, Electric Guitar",
	"JOJOs - RoundaboutBass",
	"JOJOs - RoundaboutGuitar",
	"Jojos Bizarre Adventure - Sono Chi No Sadame Short Version",
	"JoJos Bizarre Adventure - Traitors Requiem",
	"Jojos Bizzare Adventure - Stand Proud",
	"Just The Two Of Us.",
	"Justin Bieber - Beauty And A Beat WWW.MIDISFREE.COM.Mid",
	"Karen Aoki Daisuke Hasegawa - Great Days Jojos Bizarre Adventure Diamond Is Unbreakable Op3",
	"Kembali Pulang Suara Kayu Ft Feby Putri BY SurrealFlux 1780242827893",
	"LArcenCiel - Drivers High",
	"Led Zeppelin - Stairway To Heaven - Fingerstyle",
	"Linked Horizon - Attack On Titan OpShingeki No Kyojin Op",
	"Linkin Park - Numb Fingerstyle",
	"Loso -",
	"Loso - (1)",
	"Lynyrd Skynyrd - Sweet Home Alabama",
	"Mac Demarco - Freaking Out The Neighborhood",
	"Mac Demarco - Freaking Out The Neighborhood (1)",
	"Made In Thailand, Made In USA",
	"Malcolm Todd - Earrings For Band",
	"Malcolm Todd - Roommates",
	"Mayonnaise - Synestheisa [MIDIfind.Com]",
	"Metallica - Damage Inc",
	"Metallica - Enter Sandman",
	"Michael Jackson - Smooth Criminal Acoustic Fingerstyle",
	"Misc Covers-Holy By Mac Demarco-08-21-2026",
	"Misc Covers-Is It Really You (Acoustic VER.) By Loathe-07-04-2026",
	"MJMN - Rehab Session",
	"Moderndog -",
	"Mom Central",
	"Mor Lum",
	"Moving And Cut -",
	"My Chemical Romance - The Ghost Of You",
	"Never Shout Never - Your Biggest Fan Live KLICKAUD 1-AudioTrimmercom 1 Converted By Jukeblocks",
	"Nirvana - Do Re Mi",
	"Nirvana - Rape Me",
	"NONT TANONT - โต๊ะริม (Melt)",
	"Novulent - Scars",
	"Nujabes - Aruarian Dance",
	"Nujabes MINMI - Shiki No Uta",
	"Nujabes MINMI - Shiki No Uta (1)",
	"Oasis - Married With Children",
	"Output 11ec2b83 Creep - Radiohead (Piano Cover)",
	"Output Ca3c81c5 Its Snowing Like Its The End Of The World",
	"Paradox - Official MV",
	"Paradox - Official MV-Drum Kit (1)",
	"Penny Royal Tea - Approaching Nirvana (Piano-Vocal-Guitar)",
	"Pirates Of The Caribbean - He'S A Pirate (3)",
	"Pixies - Where Is My Mind",
	"Plastic Tree - Kuuchu Buranko-Electric Guitar",
	"PT Adamczyk Olga Jankowska Cyberpunk 2077 - Never Fade Away SAMURAI Cover Guitar Solo",
	"Radiohead - No Surprises",
	"Rainbow - Catch The Rainbow",
	"RaunchyGuitar",
	"Redbone - Come And Get Your Love 2",
	"Ring-Around-The-Rosie",
	"Roundabout- Bass Only",
	"S.T.A.L.K.E.R - Guitar Music From Stalker (3) [MIDIfind.Com]",
	"Sailor (1)",
	"Samurai - Never Fade Away",
	"SHINING",
	"Silly Fools -",
	"Silly Fools - - Silly Fools Lyrics Audio",
	"Silly Fools - Kid Hord(1)",
	"Silly Fools -Cant Fight",
	"Sleeping Sheep -Payu",
	"Slot Machine -",
	"Smash Mouth - All Star",
	"Smash Mouth - Walkin On The Sun",
	"Smashing Pumpkins - Luna",
	"Smile Buffalo -",
	"Solitude Is Bliss - Just One Thing",
	"Solitude Is Bliss - Vintage Pic",
	"Soundgarden - Black Hole Sun",
	"Stephen Sanchez - Until I Found You (1)",
	"Stone Metal Fire -",
	"Sunroof - Nicky Youre, Dazy",
	"Surf Curse - FreaksChorus",
	"Surf Curse - FreaksLead",
	"Tame Impala - The Less I Know The Better",
	"Tarot Feast 1780242551896",
	"Tattoo Color - Guitar Cover Skill Zource",
	"The Beatles - Dont Let Me Down",
	"The Beatles - Here Comes The Sun",
	"The Beatles - Let It Be",
	"The Cranberries - Zombie",
	"The Cure - Boys Dont Cry-Electric Guitar",
	"The Cure - Boys Dont Cry-Electric Guitar (1)",
	"The Cure - Boys Dont CryF",
	"The Jimi Hendrix Experience - Purple Haze",
	"The Neverminds - The Snow Will Catch Us Once Again",
	"The Pillows - Beautiful Morning With You",
	"The Police - Every Breath You Take",
	"The Walters - I Love You So",
	"The WORLD - Death Note",
	"Thirty Seconds To Mars - The Kill Bury Me",
	"Three Man Down - ถ้าเธอรักฉันจริง",
	"Tip Toe - HYBS",
	"Title Fight - Where Am I",
	"Toe - Goodbye Rasgueo",
	"Torete - Moira Dela Torre Love You To The Stars And Back (Lyrics) 1786923671826",
	"Tsuki (พระจันทร์) - LANDOKMAI",
	"Two Door Cinema Club - Undercover Martyn",
	"Unknown - Redbone - Come And Get Your Love Fingerstyle",
	"Unknown Artist - 2020 Sleeping Sheep",
	"Vacations - Telephones",
	"Van Halen - Aint Talkin Bout Love",
	"Vanippop",
	"Veil BassUploadByGreed",
	"Voice - Bille Jean",
	"Weezer Keaton Crackower - Say It Aint So Band Arrangement",
	"WILLIS - I Think I Like When It Rains",
	"Winter Rain - Yented",
	"Wisp - Once Then Well Be Free",
	"Wisp - Tangled Dreams",
	"Wonderless - Acoustic By Pierce The Veil",
	"Xandulsbored - Stronger Than You Charas ResponseGenocide Remix",
	"Yes - Roundabout Bass",
	"You Are My Dream",
	"YTDown Instrumental.Mp3",
	"YTDowncom YouTube What-Is-Love Media E8WfCAfom U 009 128k-AudioTrimmercom Converted By Jukeblocks",
	"ZweetRoll -",
	"กลับมา - 2 Days Ago Kids",
	"ก่อน - Moderndog",
	"ก้อนหินละเมอ - Soul After Six",
	"โกหก - Tattoo Colour",
	"ใกล้ - Scrubb",
	"ไกล Musketeer",
	"ของขวัญ - Musketeers [Fingerstyle]",
	"ข้างกัน (City) - Three Man Down Feat ออม TELEx TELEXs",
	"ขาหมู - Tattoo Colour",
	"ขี้หึง - Silly Fools [Fingerstyle]",
	"ความรักทำให้คนตาบอด - Bodyslam",
	"คำบางคำ Sqweez Animal",
	"คืนจันทร์ - LOSO",
	"คุกเข่า - Cocktail",
	"เคย",
	"จันทร์เจ้า Slot Machine",
	"ฉันอยู่ตรงนี้ - Blackhead",
	"ซ่อน(ไม่)หา - Jeff Satur X NONT TANONT",
	"ดาวหางฮัลเลย์ (Halley'S Comet) - Fellow Fellow",
	"ตาสว่าง - โมเดิร์นด็อก [Fingerstyle]",
	"เธอไม่ได้สอนให้ฉันอยู่คนเดียว - SHERRY",
	"นะหน้าทอง - โจอี้ ภูวศิษฐ์",
	"นักมายากล",
	"นางแมว",
	"น้ำลาย (Num Lye) - Silly Fools [Fingerstyle]",
	"น้ำลาย (Num Lye) - Silly Fools [Fingerstyle] (1)",
	"บ้าบอ",
	"เบื่อ",
	"ผิดที่ไว้ใจ Silly Fools",
	"ผู้ถูกเลือกให้ผิดหวัง (Sad Flower) - Reinizra",
	"พิจารณา (Consider) - Musketeers Ft Maiyarap",
	"ไม่บอกเธอ - Bedroom Audio",
	"ไม่มีเธอ",
	"ยาพิษ - Bodyslam (1)",
	"ร (W8) - GENE KASIDIT",
	"รักแรกพบ Tattoo Colour",
	"ฤดูร้อน (Acoustic Ver ) - Paradox",
	"ลมแล้ง - Yew (Summertime) Feat LANDOKMAI",
	"วัดใจ -",
	"วาดไว้ (Recall) - BOWKYLION",
	"วิภาวดี (Vibhavadi) YENTED",
	"สองรัก Zeal",
	"หรือ - Slur",
	"หวาดระแวง",
	"อยากให้เธอลอง Musketeers",
	"อย่าร้องอายเค้า - Tattoo Colour",
	"อยู่ต่อเลยได้ไหม - สิงโต นำโชค",
	"อะไรฉันก็ยอม - SARAN X The BESTS [Fingerstyle]",
	"作曲者：Toby Fox 編曲者：Jugon9187 - 夢と希望",
	"作詞：⽶津⽞師 作曲：⽶津⽞師 Tuning Eb Ab Db Gb Bb Eb - Lemon",
}