-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Across The Sea By Weezer",
	"1Join Me In Death By HIM",
	"1Kagefumi (Accurate) By Hyakkei",
	"1Laputa By Panchiko",
	"1Ma Cherie Guitar By Malice Mizer",
	"1Reunion By Korea Girl",
	"46792 Buko-",
	"Aerosmith - Dream On",
	"Audioslave - Like A Stone [MIDIfind.Com]",
	"Basic Pitch Transcription",
	"Basic Pitch Transcription (1)",
	"Basic Pitch Transcription (4)",
	"Basic Pitch Transcription (5)",
	"Bedrott (Full Song)",
	"Bjork - Army Of Me WWW.MIDISFREE.COM",
	"Chase Batta - JoJo'S Bizarre Adventure Part4 Diamond Is Unbreakable OP2",
	"Chevelle - Comfortable Liar [MIDIfind.Com]",
	"Creep - Radiohead - Extremely Accurate (Full Band) G",
	"CREEP U KLICKAUD",
	"Deftones My Own Summer Shove It.Gtr",
	"DöNence( ARsi3SHma6c )",
	"Everlong By The Foo Fighters Piia",
	"In The End - Linkin Park",
	"Is It Really You - Loathe",
	"Jane! Ttest",
	"LED ZEPPELIN.Stairway To Heaven KA",
	"Lit My Own Worst Enemy.Gtr",
	"Made In Thailland 2",
	"MAYONAISE",
	"My Chemical Romance - I Don'T Love You [MIDIfind.Com]",
	"New Computers - Girlfriends",
	"Nirvana - Sliver (5) [MIDIfind.Com]",
	"PTV - King For A Day",
	"Radiohead - My Iron Lung",
	"Sayonara Cross Teck-07-04-2026",
	"Smashing Pumpkins - Mayonaise [MIDIfind.Com]",
	"Soundgarden - Black Hole Sun (3) [MIDIfind.Com]",
	"Soundgarden - Half [MIDIfind.Com]",
	"Them Bones - Alice In Chains",
	"Treehouse Alex G",
	"Weezer - Island In The Sun (4) [MIDIfind.Com]",
	"Wonderless",
	"Wonderless2",
}