-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Across The Sea By Weezer",
	"1Join Me In Death - HIM (Guitar)",
	"1Join Me In Death By HIM",
	"1Kagefumi (Accurate) By Hyakkei",
	"1Laputa By Panchiko",
	"1Ma Cherie Guitar By Malice Mizer",
	"1Reunion By Korea Girl",
	"46792 Buko-",
	"Aerosmith - Dream On",
	"Alex G - Mary",
	"All In My Head Riff.Mid",
	"Audioslave - Like A Stone [MIDIfind.Com]",
	"Basic Pitch Transcription",
	"Basic Pitch Transcription (1)",
	"Basic Pitch Transcription (4)",
	"Basic Pitch Transcription (5)",
	"Bass About The Girl-The Academy Is",
	"Bass Helena MCR",
	"Bedrott (Full Song)",
	"Bjork - Army Of Me WWW.MIDISFREE.COM",
	"Chase Batta - JoJo'S Bizarre Adventure Part4 Diamond Is Unbreakable OP2",
	"Chevelle - Comfortable Liar [MIDIfind.Com]",
	"Creep - Radiohead - Extremely Accurate (Full Band) G",
	"CREEP U KLICKAUD",
	"Deftones My Own Summer Shove It.Gtr",
	"DöNence( ARsi3SHma6c )",
	"Everlong By The Foo Fighters Piia",
	"Glistening-Absurdism Full Version-05-06-2026",
	"Go Away - Weezer",
	"Guiarra Lead Annabel Alesana",
	"Guitar Rtm About The Girl-The Academy Is",
	"Guitar1 Helena MCR",
	"Guitar2 Helena MCR",
	"I Cant Handle Change - Roar",
	"In The End - Linkin Park",
	"Is It Really You - Loathe",
	"Jane! Ttest",
	"Kaer Morhen From Witcher",
	"LED ZEPPELIN.Stairway To Heaven KA",
	"Lit My Own Worst Enemy.Gtr",
	"Lustra - Scotty Doesn'T Know (2) [MIDIfind.Com]",
	"Made In Thailland 2",
	"Mary Alex G",
	"MAYONAISE",
	"Mudhoney - Suck You Dry [MIDIfind.Com]",
	"Mudhoney - Touch Me I'M Sick [MIDIfind.Com]",
	"My Chemical Romance - I Don'T Love You [MIDIfind.Com]",
	"New Computers - Girlfriends",
	"Nirvana - Sliver (5) [MIDIfind.Com]",
	"Pixies - Where Is My Mind (5) [MIDIfind.Com]",
	"PTV - King For A Day",
	"Queens Of The Stone Age - Song For The Dead [MIDIfind.Com]",
	"Radiohead - My Iron Lung",
	"Sayonara Cross Teck-07-04-2026",
	"Smashing Pumpkins - Mayonaise (2) [MIDIfind.Com]",
	"Smashing Pumpkins - Mayonaise (3) [MIDIfind.Com]",
	"Smashing Pumpkins - Mayonaise [MIDIfind.Com]",
	"Soundgarden - Black Hole Sun (3) [MIDIfind.Com]",
	"Soundgarden - Half [MIDIfind.Com]",
	"Test Seumur Hidup Kan Ku Habiskan By Harum Manis",
	"Them Bones - Alice In Chains",
	"Treehouse Alex G",
	"Undone The Sweater Song - Weezer (Piano-Vocal-Guitar)",
	"Weezer - Island In The Sun (4) [MIDIfind.Com]",
	"Weezer - Undone The Sweater Song [MIDIfind.Com]",
	"WEEZERUndone",
	"WelcometotheBlackParade",
	"Where Is My Mind",
	"Where Is My Mind - Pixies",
	"Wonderless",
	"Wonderless2",
}