-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"Buddy Holly - Weezer (Extremely Accurate) 🔥🎸G",
	"Cant Stop - Red Hot Chili Peppers",
	"Children",
	"Fingerstyle",
	"GOAT - Polyphia G O A T - Copy Mscz",
	"Guns N Roses - Sweet Child O Mine",
	"Hava Nagila A Z Idelsohn",
	"Megalovania On Guitar",
	"My Hero - Foo Fighters",
	"My Hero - Foo Fighters (1)",
	"PAUSE",
	"Playing God - Polyphia Playing God Tab",
	"Shiki No Uta (1)",
	"Three Days Grace - Painkiller",
	"Through The Fire And Flames - DragonForce (Complete, Virtuoso Version)",
	"Tuyo (Narcos Theme) - Rodrigo Amarante",
	"Wake Me Up When September Ends - Green Day (Guitar Tab Play-Along)",
	"แสงสุดท้าย (Saeng Sud Tye) - Bodyslam [Fingerstyle]",
}