-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"And-Your-Bird-Can-Sing",
	"AUD Lr0462",
	"AUD NOY0290",
	"Beatles (The) - Eleanor Rigby [MIDIfind.Com]",
	"Beatles (The) - Here Comes The Sun [MIDIfind.Com]",
	"Beatles (The) - I'M Only Sleeping [MIDIfind.Com]",
	"Beatles (The) - While My Guitar Gently Weeps (2) [MIDIfind.Com]",
	"Buddy Holly - Weezer (Extremely Accurate) 🔥🎸G",
	"Cant Stop - Red Hot Chili Peppers",
	"Children",
	"Do You Wanna Know A Secret",
	"Eagles (The) - Hotel California (3) [MIDIfind.Com]",
	"Fingerstyle",
	"Foo Fighters - Everlong [MIDIfind.Com]",
	"GOAT - Polyphia G O A T - Copy Mscz",
	"Guns N Roses - Sweet Child O Mine",
	"Hava Nagila A Z Idelsohn",
	"Iron Maiden - Iron Maiden [MIDIfind.Com]",
	"Jerryc - Canon Rock Lead Guitar [MIDIfind.Com]",
	"Last Rites Loved To Deth - Megadeth Last Rites Loved To Deth - Megadeth (Demo)",
	"Let It Happen - Tame Impala",
	"Linkin Park - Numb",
	"Megadeth - Holy Wars The Punishment Due",
	"Megalovania On Guitar",
	"METALLICA.One",
	"Metallica+-+Master+Of+Puppets+(Guitars+Only)",
	"My Hero - Foo Fighters",
	"My Hero - Foo Fighters (1)",
	"Norwegian-Wood-1",
	"Paperback Writer",
	"PAUSE",
	"Playing God - Polyphia Playing God Tab",
	"Queen - Bohemian Rhapsody Complete [MIDIfind.Com]",
	"Santana Carlos - Smooth [MIDIfind.Com]",
	"Shiki No Uta (1)",
	"The Beatles - A Hard Day'S Night",
	"THE BEATLES.Blackbird K",
	"THE BEATLES.Helter Skelter",
	"Three Days Grace - Painkiller",
	"Through The Fire And Flames - DragonForce (Complete, Virtuoso Version)",
	"Tuyo (Narcos Theme) - Rodrigo Amarante",
	"Van Halen - Eruption",
	"Wake Me Up When September Ends - Green Day (Guitar Tab Play-Along)",
	"แสงสุดท้าย (Saeng Sud Tye) - Bodyslam [Fingerstyle]",
}