-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"Chase-Atlantic-Into-It-Sax-Solo-Cover-On-Guitar Bs6stem Mt 0 Guitar",
	"Composed By Toby Fox Transcribed By Nefelibata - Home",
	"Dont Let Me Down",
	"Dumb Ways To Die",
	"Dumb Ways To Die (1)",
	"Finnish Folk Song - SäKkijäRven Polkka",
	"Giorno'S Theme [Jojo'S Bizarre Adventure] (WIP)",
	"Heart-Shaped Box",
	"Just The Two Of Us.",
	"Just The Two Of Us.Mid (1)",
	"Lithium - Nirvana",
	"Misirlou.Mid",
	"One Last Breath",
	"Piano God - Fikram",
	"PNE - Gitara (Fingerstyle)",
	"Sempurna - Guitar - Fikram",
	"Smells Like Teen Spirit",
	"THE EAGLES.Hotel California K",
	"Virgoun - Surat Cinta Untuk Starla - Guitar - Fikram",
	"Ween-Ocean Man (Piano Arrangement) [50 FOLLOWER SPECIAL]",
}