-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Hava Nagila",
	"1The Housebuilding Song",
	"Blowin' In The Wind - Bob Dylan, Peter, Paul & Mary (Piano-Vocal-Guitar)",
	"Bob Dylan - Like A Rolling Stone",
	"Bob DylanBobDylan Like A Rolling Stone",
	"Dylan Bob - Like A Rolling Stone (2) [MIDIfind.Com]",
	"Fallen Down But In Ragtime",
	"Glitchtale Love - True LOVE",
	"House-Of-The-Rising-Sun-1.Mid",
	"Huricane - Bob Dylan",
	"Jazz In Paris",
	"Kalinka.Mid",
	"Katyusha.Mid",
	"Knockin'On Heaven'S Door - Bob Dylan",
	"Like A Rolling Stone - Bob Dylan",
	"Like A Rolling Stone - Bob Dylan (Piano-Vocal-Guitar)",
	"Misc Covers-Foggy Mountain Breakdown-07-04-2026",
	"Misc Covers-You'Ve Gotta Move-07-04-2026",
	"Pachka Sigaret - Kino (Femboy'S Version)",
	"Ragtime-Cowboy-Joe",
	"The Entertainer - Scott Joplin",
}