-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"[Midi] Michael Jackson - Rock With You",
	"Adventure Of A Lifetime - Coldplay",
	"Altars Of Apostasy.Mid",
	"Another Part Of Me (2012 Remaster)",
	"Crazy Frog - Axel F.Mid",
	"D CR0057",
	"Daft Punk - Get Lucky [MIDIfind.Com]",
	"Daft+Punk+-+Get+Lucky+(Slowed+++Reverb) 128k",
	"Event Horizon (Reach For The Sun And Burn! Burn! Burn!) - ULTRAKILL OST",
	"Get Proto Art Of Guitar (2)",
	"Limp Bizkit - Take A Look Around [MIDIfind.Com]",
	"Metallica-Enter-Sandman Midi",
	"Motley Crue - Kickstart My Heart.Mid",
	"Ozzy Osbourne - Crazy Train.Mid",
	"Red Hot Chili Peppers - Scar Tissue",
	"Sweet Dreams Midi",
	"Tiki Tiki Funk",
	"Кино - Группа крови [MIDIfind.Com]",
	"Кино - Последний Герой Kino - The Last Hero",
	"Кино - Спокойная ночь",
	"Руки вверх - 18 мне уже [MIDIfind.Com]",
}