-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Innocence - Daniel Caesar (Piano)",
	"1On The Square (Piano)",
	"Angus And Julia Stone - Big Jet Plane [MIDIfind.Com]",
	"Bass For Now Not Ever-Motifs",
	"Bass Teen Rebel DropD V2",
	"Bass Teen Rebel DropD V3",
	"Bass Teen Rebel DropD V4",
	"Bass Teen Rebel The Haunted Youth Tuning Drop D",
	"Boys Don'T Cry - The Cure (Piano Arrangement)",
	"Brubeck Dave - Take Five [MIDIfind.Com]",
	"Creep - Radiohead (Guitar)",
	"Guitar Alicia Viajes En El Tiempo",
	"Guitar For Now Not Ever-Motifs",
	"Guitar Lead Surf Curse Freaks",
	"Guitar Rtm Surf Curse Freaks",
	"Guitar1 Alv Bye Melted Ice Cream",
	"Guitar1 Eidolon Hibou",
	"Guitar2 Alv Bye Melted Ice Cream",
	"Guitar2 Eidolon Hibou",
	"Guitar2 For Now Not Ever-Motifs",
	"Guitars 1 2 Teen Rebel THY",
	"Guitars 1 2 Teen Rebel THY LIVE ROCK",
	"Guns N' Roses - November Rain [MIDIfind.Com]",
	"Key Test",
	"Keys Test V2",
	"Keys Test V3",
	"Keys Test V4",
	"Led Zeppelin-Stairway To Heaven-06-11-2026 (1)",
	"Mac Demarco - Freaking Out The Neighborhood [MIDIfind.Com]",
	"Mundo By Iv Of Spades ( Solo Cover)",
	"Nope Your Too Late I Already Died",
	"Pink Floyd - Comfortably Numb (The Wall Live) [MIDIfind.Com]",
	"Radiohead - All I Need [MIDIfind.Com]",
	"Radiohead - Fake Plastic Trees Acoustic Version [MIDIfind.Com]",
	"Radiohead - Jigsaw Falling Into Place [MIDIfind.Com]",
	"Radiohead - Nude [MIDIfind.Com]",
	"ROAR - Christmas Kids",
	"RoMIDI Context Test 48-63",
	"RoMIDI Context Test 48-63 SLOW",
	"RoMIDI NOTE 48",
	"RoMIDI NOTE 49",
	"RoMIDI NOTE 50",
	"RoMIDI NOTE 51",
	"RoMIDI NOTE 52",
	"RoMIDI NOTE 53",
	"RoMIDI NOTE 54",
	"RoMIDI NOTE 55",
	"SpongeBob - Main Theme [MIDIfind.Com]",
	"Teen Rebel Guitar Lead",
	"Teen Rebel Guitar Lead 2",
	"Tek It - Cafune.Mid",
	"Test Tr",
	"The Haunted Youth-Teen Rebel-08-02-2026",
}