-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"06.Metallica-Escape",
	"50 AC DC RIFFS",
	"50 Iron Maiden RIFFS",
	"50 KISS RIFFS",
	"50 Megadeth RIFFS",
	"50 Metallica RIFFS",
	"50 Pantera RIFFS",
	"50 Riffs - Ac Dc (Pro)",
	"50 Riffs - Iron Maiden (Pro)",
	"50 Riffs - Megadeth (Pro)",
	"50 Riffs - MetáLica (Pro)",
	"50 Riffs - Pantera (Pro)",
	"505 - Arctic Monkeys",
	"A Miserable Life",
	"ÁGua De Beber (Tom Jobim), Apenas Solo.Mid",
	"Angel Of Death - Slayer (Corrected To E Standard)",
	"AngelOfDeath",
	"Anthrax - Madhouse (4) [MIDIfind.Com]",
	"Avenged Sevenfold - Afterlife Solo Live [MIDIfind.Com]",
	"Avenged Sevenfold - Buried Alive [MIDIfind.Com]",
	"Avenged Sevenfold - Clairvoyant Disease [MIDIfind.Com]",
	"Avenged Sevenfold - Dancing Dead Solo [MIDIfind.Com]",
	"Avenged Sevenfold - Hail To The King Solo [MIDIfind.Com]",
	"Avenged Sevenfold - Nightmare [MIDIfind.Com]",
	"Avenged Sevenfold - Nightmare Solo Per By David Escobar [MIDIfind.Com]",
	"Avenged Sevenfold - Save Me (2) [MIDIfind.Com]",
	"Avenged Sevenfold - Seize The Day Solo [MIDIfind.Com]",
	"Avenged Sevenfold - So Far Away [MIDIfind.Com]",
	"Avenged Sevenfold - This Means War (Guitar Solo) [MIDIfind.Com]",
	"Bathory - A Fine Day To Die [MIDIfind.Com]",
	"Bathory - Necromansy [MIDIfind.Com]",
	"Bathory - Song To Hall Up High",
	"Becker Jason - Altitudes (2) [MIDIfind.Com]",
	"Becker Jason - Serrana (2) [MIDIfind.Com] (1)",
	"Beggin-Maneskin.Mid (1)",
	"Black Sabbath - Black Sabbath [MIDIfind.Com]",
	"Black Sabbath - Paranoid [MIDIfind.Com]",
	"Blackened Isolated Solo By Chicoplatr",
	"Blitzkrieg Bop - Ramones",
	"Burzum - Det Som En Gang Var [MIDIfind.Com]",
	"Burzum - Dunkelheit Burzum [MIDIfind.Com]",
	"Burzum - Ea Lord Of The Depths [MIDIfind.Com]",
	"Burzum - Feeble Screams From Forests Unknown [MIDIfind.Com]",
	"Burzum - Jesus Tod [MIDIfind.Com]",
	"Cacophony - Concerto (2) [MIDIfind.Com]",
	"Cacophony - Speed Metal Symphony (2) [MIDIfind.Com]",
	"Cancertid - Lifelover",
	"Candlemass - Solitude [MIDIfind.Com]",
	"Converted-1783627408087",
	"Crybaby - Destroy Boys",
	"Cryptopsy - Back To The Worms (Guitar)",
	"Cryptopsy - Benedictine Convulsions (Guitar)",
	"Cryptopsy - Dead And Dripping (Guitar)",
	"Cryptopsy - Defenestration (Guitar)",
	"Cryptopsy - Depths You'Ve Fallen (Guitar)",
	"Cryptopsy - Graves Of The Fathers (Guitar)",
	"Cryptopsy - Mutant Christ (Guitar)",
	"Cryptopsy - Slit Your Guts (Guitar)",
	"Darkthrone - Lifeless [MIDIfind.Com]",
	"Darkthrone - Transilvanian Hunger (4) [MIDIfind.Com]",
	"Darkthrone - Under A Funeral Moon [MIDIfind.Com]",
	"Darkthrone - Unholy Blackmetal [MIDIfind.Com]",
	"Darkthrone - Valkyrie [MIDIfind.Com]",
	"DauðI Baldrs - Burzum",
	"Death Pierce Me (Guitar)",
	"Decalius Lonliness Solo",
	"Dimmu Borgir - Puritania [MIDIfind.Com]",
	"Dio Ronnie James - Holy Diver [MIDIfind.Com]",
	"Discharge - Fight Back [MIDIfind.Com]",
	"Discharge - Realities Of War [MIDIfind.Com]",
	"Domination - Pantera, R Guitar + Solo, No Vocals Or Bass! (FIXED VERSION)",
	"Domination - Pantera, Rhythm Guitar + Solo Only! No Vocals Or Bass! By Chicoplatr",
	"Domination- Pantera, Rhythm And Solo Only Guitars!",
	"DragonForce - Fury Of The Storm [MIDIfind.Com]",
	"DragonForce - Heroes Of Our Time [MIDIfind.Com]",
	"DragonForce - Operation Ground And Pound [MIDIfind.Com]",
	"DragonForce - Through The Fire And Flames (2) [MIDIfind.Com]",
	"DragonForce - Valley Of The Damned Demo [MIDIfind.Com] (1)",
	"Eldoraudio-Destroy Boys - Crybaby Guitar Solo 1",
	"Electric Wizard - We Hate You [MIDIfind.Com]",
	"Eruption - Van Halen",
	"Eyes Of A Homeless Dog - Psychonaut 4",
	"For-Whom-The-Bell-Tolls",
	"Funeral Ceremony - Grausamkeit",
	"Gojira - Flying Whales (OFFICIAL) [MIDIfind.Com]",
	"Gotterkreig - Grausamkeit Gotterkreig (Only Melody, Without Ornaments) - Grausamkeit Gotterkreig",
	"Han Som Reiste - Burzum",
	"Happy Days - Don'T Guns (Guitar)",
	"Haunted (The) - Silencer [MIDIfind.Com]",
	"Helloween - Dr Stein (2) [MIDIfind.Com]",
	"Helloween - Eagle Fly Free (4) [MIDIfind.Com]",
	"Helloween - Future World (3) [MIDIfind.Com]",
	"Helloween - Halloween (2) [MIDIfind.Com]",
	"Helloween - I Want Out (2) [MIDIfind.Com]",
	"HermoðR Á Helferð - Burzum",
	"HIM - Gone With The Sin [MIDIfind.Com]",
	"HIM - Join Me [MIDIfind.Com]",
	"HIM - Poison Girl [MIDIfind.Com]",
	"HIM - Razorblade Kiss [MIDIfind.Com]",
	"HIM - Your Sweet 666 [MIDIfind.Com]",
	"Ilia Burzum",
	"Jason Becker - Altitudes Solo",
	"Judas Priest - A Touch Of Evil [MIDIfind.Com]",
	"Judas Priest - Breaking The Law [MIDIfind.Com]",
	"Judas Priest - Diamonds And Rust [MIDIfind.Com]",
	"Judas Priest - Electric Eye [MIDIfind.Com]",
	"Judas Priest - Electric Eye Solo 1 [MIDIfind.Com]",
	"Judas Priest - Electric Eye Solo 2nd Part [MIDIfind.Com]",
	"Judas Priest - Grinder [MIDIfind.Com]",
	"Judas Priest - Jugulator [MIDIfind.Com]",
	"Judas Priest - Love Bites [MIDIfind.Com]",
	"Judas Priest - Nightcrawler [MIDIfind.Com]",
	"Judas Priest - Out In The Cold [MIDIfind.Com]",
	"Judas Priest - Painkiller [MIDIfind.Com]",
	"Judas Priest - Revolution [MIDIfind.Com]",
	"Judas Priest - Screaming For Vengeance [MIDIfind.Com]",
	"Judas Priest - The Ripper [MIDIfind.Com]",
	"Judas Priest - The Sentinel [MIDIfind.Com]",
	"Judas Priest - Turbo Lover [MIDIfind.Com]",
	"Judas Priest - Victim Of Changes [MIDIfind.Com]",
	"Judas Priest - Victim Of Changes Intro (Solo) [MIDIfind.Com]",
	"KISS - Detroit Rock City",
	"Kiss - Rock And Roll All Night",
	"Kratze - Grausamkeit - Joel 12344",
	"Lifelover - Androider [MIDIfind.Com]",
	"Lifelover - Cancertid [MIDIfind.Com]",
	"Lifelover - I Love To Hurt You (2) [MIDIfind.Com]",
	"Lifelover - Lethargy [MIDIfind.Com]",
	"Lifelover - Mental Central Dialog [MIDIfind.Com]",
	"Lifelover - Myspys [MIDIfind.Com]",
	"Lifelover - Nackskott [MIDIfind.Com]",
	"Limp Bizkit - Break Stuff (2) [MIDIfind.Com]",
	"Lost Wisdom - Burzum",
	"Megadeth - Devils Island [MIDIfind.Com]",
	"Megadeth - Hanger 18",
	"Megadeth - In My Darkest Hour [MIDIfind.Com]",
	"Megadeth - Mechanix (3) [MIDIfind.Com]",
	"Megadeth - Peace Sells [MIDIfind.Com]",
	"Megadeth - Symphony Of Destruction [MIDIfind.Com]",
	"Megadeth - The Conjuring [MIDIfind.Com]",
	"Megadeth - Tornado Of Souls [MIDIfind.Com]",
	"Megadeth-Rust In Peace Polaris",
	"Metallica - 2 X 4 [MIDIfind.Com]",
	"Metallica - Am I Evil [MIDIfind.Com]",
	"Metallica - And Justice For All [MIDIfind.Com]",
	"Metallica - Anesthesia Pulling Teeth With Wah Sound",
	"Metallica - Battery [MIDIfind.Com]",
	"Metallica - Blackened [MIDIfind.Com]",
	"Metallica - Blackened Reversed (Intro) [MIDIfind.Com]",
	"Metallica - Blackened Solo Tutorial By Chris Zoupa [MIDIfind.Com]",
	"Metallica - Creeping Death (2) [MIDIfind.Com]",
	"Metallica - Creeping Death (Solo) [MIDIfind.Com]",
	"Metallica - Damage Inc [MIDIfind.Com]",
	"Metallica - Disposable Heroes [MIDIfind.Com]",
	"Metallica - Dyers Eve [MIDIfind.Com]",
	"Metallica - Enter Sandman [MIDIfind.Com]",
	"Metallica - Eye Of The Beholder [MIDIfind.Com]",
	"Metallica - Fade To Black [MIDIfind.Com]",
	"Metallica - Fade To Black Solo Guitar Kelly Valleau [MIDIfind.Com]",
	"Metallica - Fight Fire With Fire (7) [MIDIfind.Com]",
	"Metallica - Fight Fire With Fire [MIDIfind.Com]",
	"Metallica - For Whom The Bell Tolls [MIDIfind.Com]",
	"Metallica - Frayed Ends Of Sanity [MIDIfind.Com]",
	"Metallica - Fuel (2) [MIDIfind.Com]",
	"Metallica - Fuel [MIDIfind.Com]",
	"Metallica - Harvester Of Sorrow (2) [MIDIfind.Com]",
	"Metallica - Harvester Of Sorrow [MIDIfind.Com]",
	"Metallica - Hit The Lights [MIDIfind.Com]",
	"Metallica - Holier Than Thou [MIDIfind.Com]",
	"Metallica - Jump In The Fire [MIDIfind.Com]",
	"Metallica - Last Caress (2) [MIDIfind.Com]",
	"Metallica - Leper Messiah [MIDIfind.Com]",
	"Metallica - Lux ÆTerna",
	"Metallica - Master Of Puppets",
	"Metallica - Master Of Puppets (23) [MIDIfind.Com]",
	"Metallica - Master Of Puppets [MIDIfind.Com]",
	"Metallica - Metal Militia [MIDIfind.Com]",
	"Metallica - Motorbreath (2) [MIDIfind.Com]",
	"Metallica - Motorbreath [MIDIfind.Com]",
	"Metallica - My Apocalypse [MIDIfind.Com]",
	"Metallica - No Remorse [MIDIfind.Com]",
	"Metallica - Nothing Else Matters Whole Song Single Guitar [MIDIfind.Com]",
	"Metallica - Of Wolf And Man (3) [MIDIfind.Com]",
	"Metallica - One",
	"Metallica - One [MIDIfind.Com]",
	"Metallica - One Solo Played By David Escobar [MIDIfind.Com]",
	"Metallica - Orion (Bass Riff) [MIDIfind.Com]",
	"Metallica - Orion (Bass Solo) [MIDIfind.Com]",
	"Metallica - Orion [MIDIfind.Com]",
	"Metallica - Phantom Lord [MIDIfind.Com]",
	"Metallica - Ride The Lightning",
	"Metallica - Ride The Lightning Solo Tutorial By Chris Zoupa [MIDIfind.Com]",
	"Metallica - Sad But True [MIDIfind.Com]",
	"Metallica - Seek And Destroy [MIDIfind.Com]",
	"Metallica - Some Kind Of Monster [MIDIfind.Com]",
	"Metallica - Spit Out The Bone",
	"Metallica - St Anger [MIDIfind.Com]",
	"Metallica - The Call Of Ktulu [MIDIfind.Com]",
	"Metallica - The Day That Never Comes (13) [MIDIfind.Com]",
	"Metallica - The Four Horseman [MIDIfind.Com]",
	"Metallica - The Shortest Straw [MIDIfind.Com]",
	"Metallica - The Struggle Within [MIDIfind.Com]",
	"Metallica - The Thing That Should Not Be [MIDIfind.Com]",
	"Metallica - The Unforgiven [MIDIfind.Com]",
	"Metallica - Through The Never [MIDIfind.Com]",
	"Metallica - To Live Is To Die (11) [MIDIfind.Com]",
	"Metallica - Trapped Under Ice [MIDIfind.Com]",
	"Metallica - Welcome Home Sanatarium [MIDIfind.Com]",
	"Metallica - Wherever I May Roam [MIDIfind.Com]",
	"Metallica - Whiplash [MIDIfind.Com]",
	"Metallica Spit Out The Bone",
	"Michael Jackson - Thriller",
	"Midnight Queen - SarcóFago (IníCio)",
	"Monster - Skillet",
	"Ms Salmonella - Lifelover",
	"Necromancy - Bathory",
	"Nocturnal Depression - Her Ghost Haunts These Walls",
	"Opensheets-Torment-Payback",
	"Osbourne Ozzy - Crazy Train [MIDIfind.Com]",
	"Osbourne Ozzy - Hellraiser [MIDIfind.Com]",
	"Osbourne Ozzy - I Don'T Wanna Stop [MIDIfind.Com]",
	"Osbourne Ozzy - Mr Crowley [MIDIfind.Com]",
	"Osbourne Ozzy - No More Tears [MIDIfind.Com]",
	"Osbourne Ozzy - Perry Mason [MIDIfind.Com]",
	"Osbourne Ozzy - Walk On Water [MIDIfind.Com]",
	"Ozzy Osbourne-Crazy Train",
	"Pantera - 10'S [MIDIfind.Com]",
	"Pantera - 5 Minutes Alone [MIDIfind.Com]",
	"Pantera - A New Level [MIDIfind.Com]",
	"Pantera - Becoming [MIDIfind.Com]",
	"Pantera - By Demons Be Driven [MIDIfind.Com]",
	"Pantera - Cemetery Gates (7) [MIDIfind.Com]",
	"Pantera - Cowboys From Hell [MIDIfind.Com]",
	"Pantera - Domination",
	"Pantera - Floods [MIDIfind.Com]",
	"Pantera - Fucking Hostile [MIDIfind.Com]",
	"Pantera - Good Friends And A Bottle Of Pills",
	"Pantera - Heresy [MIDIfind.Com]",
	"Pantera - I'M Broken [MIDIfind.Com]",
	"Pantera - Primal Concrete Sledge [MIDIfind.Com]",
	"Pantera - Psycho Holiday [MIDIfind.Com]",
	"Pantera - Revolution Is My Name (2) [MIDIfind.Com]",
	"Pantera - Revolution Is My Name [MIDIfind.Com]",
	"Pantera - Shedding Skin [MIDIfind.Com]",
	"Pantera - Slaughtered [MIDIfind.Com]",
	"Pantera - Strenght Beyond Strenght [MIDIfind.Com]",
	"Pantera - The Art Of Shredding",
	"Pantera - This Love [MIDIfind.Com]",
	"Pantera - Walk (3)",
	"Pantera-Hollow",
	"People = Shit - Slipknot",
	"Phobophile",
	"Psychonaut 4 - Drop By Drop [MIDIfind.Com]",
	"Psychonaut 4 - Lethargic Dialogue [MIDIfind.Com]",
	"Psychonaut 4 - Nackskott [MIDIfind.Com]",
	"Psychonaut 4 - Overdose Was The Best Way To Die [MIDIfind.Com]",
	"Psychonaut 4 - Serial Lier (2) [MIDIfind.Com]",
	"Psychonaut 4 - World Of Pain And Hate [MIDIfind.Com]",
	"Racer X - Scarified (2) [MIDIfind.Com]",
	"Racer X - Technical Difficulties (3) [MIDIfind.Com]",
	"Rage Against The Machine - Bulls On Parade (2) [MIDIfind.Com]",
	"Rage Against The Machine - Killing In The Name (2) [MIDIfind.Com]",
	"Rage Against The Machine - Killing In The Name [MIDIfind.Com]",
	"RainingBlood",
	"Rammstein - Du Hast [MIDIfind.Com]",
	"Rammstein - Sonne [MIDIfind.Com]",
	"Repentless",
	"Roses On Bathory S Blood Bath",
	"Serrana Solo",
	"Silencer - Death Pierce Me [MIDIfind.Com]",
	"Silencer - Sterile Nails And Thunderbowels [MIDIfind.Com]",
	"Slayer - Angel Of Death (2) [MIDIfind.Com]",
	"Slayer - Raining Blood [MIDIfind.Com]",
	"Slipknot - Before I Forget [MIDIfind.Com]",
	"Slipknot - Duality [MIDIfind.Com]",
	"Slipknot - Sic [MIDIfind.Com]",
	"Slipknot - The Heretic Anthem (4) [MIDIfind.Com]",
	"Smoke On The Water - Deep Purple Smoke On The Water - Deep Purple",
	"Stabwound - Necrophagist Piano Arrangement (Sorta) Lyrics!!",
	"Symphony X - Sea Of Lies First Part",
	"System Of A Down - B.Y.O.B. [MIDIfind.Com]",
	"System Of A Down - Lonely Day [MIDIfind.Com]",
	"The Crying Orc - Burzum",
	"Three Days Grace - Animal I Have Become [MIDIfind.Com]",
	"Three Days Grace - I Hate Everything About You (4) [MIDIfind.Com]",
	"Three Days Grace - I Hate Everything About You [MIDIfind.Com]",
	"Three Days Grace - Never Too Late (3) [MIDIfind.Com]",
	"Three Days Grace - Pain (2) [MIDIfind.Com]",
	"Through The Fire And Flames - DragonForce",
	"Tool - Parabol Parabola [MIDIfind.Com]",
	"Tool - Schism (3) [MIDIfind.Com]",
	"Toxicity - System Of A Down",
	"Trilogy Suite Op 5 - Yngwie Malmsteen",
	"Type O Negative - Black No 1 (2) [MIDIfind.Com]",
	"Type O Negative - Christian Woman [MIDIfind.Com]",
	"Type O Negative - I Don'T Wanna Be Me [MIDIfind.Com]",
	"Type O Negative - My Girlfriend'S Girlfriend (2) [MIDIfind.Com]",
	"Type O Negative - Out Of The Fire [MIDIfind.Com]",
	"Vai Steve - For The Love Of God [MIDIfind.Com]",
	"Valhalla - Bathory",
	"Venom - Black Metal (4) [MIDIfind.Com]",
	"Venom - Countess Bathory (2) [MIDIfind.Com]",
	"Venom - Don'T Burn The Witch [MIDIfind.Com]",
	"Venom - If You Wanna War [MIDIfind.Com]",
	"Venom - In League With Satan [MIDIfind.Com]",
	"Venom - Prime Evil [MIDIfind.Com]",
	"Venom - Welcome To Hell [MIDIfind.Com]",
	"Venom - Witching Hour [MIDIfind.Com]",
	"VØJ & Narvent - Memory Reboot",
	"War - Burzum",
	"WASP - On Your Knees [MIDIfind.Com]",
	"Мастер - 2000 лет (Иуда) [MIDIfind.Com]",
	"Мастер - Берегись [MIDIfind.Com]",
	"Мастер - Мастер [MIDIfind.Com]",
}