-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"Avenged Sevenfold - Afterlife Solo Live [MIDIfind.Com]",
	"Avenged Sevenfold - Buried Alive [MIDIfind.Com]",
	"Avenged Sevenfold - Clairvoyant Disease [MIDIfind.Com]",
	"Avenged Sevenfold - Dancing Dead Solo [MIDIfind.Com]",
	"Avenged Sevenfold - Hail To The King Solo [MIDIfind.Com]",
	"Avenged Sevenfold - Nightmare Solo Per By David Escobar [MIDIfind.Com]",
	"Avenged Sevenfold - Save Me (2) [MIDIfind.Com]",
	"Avenged Sevenfold - Seize The Day Solo [MIDIfind.Com]",
	"Avenged Sevenfold - So Far Away [MIDIfind.Com]",
	"Avenged Sevenfold - This Means War (Guitar Solo) [MIDIfind.Com]",
	"For-Whom-The-Bell-Tolls",
	"Megadeth - In My Darkest Hour [MIDIfind.Com]",
	"Metallica - Blackened [MIDIfind.Com]",
	"Metallica - Creeping Death (2) [MIDIfind.Com]",
	"Metallica - Enter Sandman [MIDIfind.Com]",
	"Metallica - One",
	"Metallica - One [MIDIfind.Com]",
	"Metallica - Orion [MIDIfind.Com]",
	"Metallica - Ride The Lightning",
	"Pantera - Cemetery Gates (7) [MIDIfind.Com]",
	"Pantera - Floods [MIDIfind.Com]",
	"Pantera - This Love [MIDIfind.Com]",
	"Through The Fire And Flames - DragonForce",
}