-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"50 AC DC RIFFS",
	"50 Iron Maiden RIFFS",
	"50 KISS RIFFS",
	"50 Megadeth RIFFS",
	"50 Metallica RIFFS",
	"50 Pantera RIFFS",
	"505 - Arctic Monkeys",
	"ÁGua De Beber (Tom Jobim), Apenas Solo.Mid",
	"Avenged Sevenfold - Afterlife Solo Live [MIDIfind.Com]",
	"Avenged Sevenfold - Buried Alive [MIDIfind.Com]",
	"Avenged Sevenfold - Clairvoyant Disease [MIDIfind.Com]",
	"Avenged Sevenfold - Dancing Dead Solo [MIDIfind.Com]",
	"Avenged Sevenfold - Hail To The King Solo [MIDIfind.Com]",
	"Avenged Sevenfold - Nightmare Solo Per By David Escobar [MIDIfind.Com]",
	"Avenged Sevenfold - Save Me (2) [MIDIfind.Com]",
	"Avenged Sevenfold - Seize The Day Solo [MIDIfind.Com]",
	"Avenged Sevenfold - So Far Away [MIDIfind.Com]",
	"Avenged Sevenfold - This Means War (Guitar Solo) [MIDIfind.Com]",
	"Becker Jason - Altitudes (2) [MIDIfind.Com]",
	"Black Sabbath - Black Sabbath [MIDIfind.Com]",
	"Black Sabbath - Paranoid [MIDIfind.Com]",
	"Blitzkrieg Bop - Ramones",
	"Burzum - Det Som En Gang Var [MIDIfind.Com]",
	"Burzum - Dunkelheit Burzum [MIDIfind.Com]",
	"Burzum - Ea Lord Of The Depths [MIDIfind.Com]",
	"Burzum - Feeble Screams From Forests Unknown [MIDIfind.Com]",
	"Burzum - Jesus Tod [MIDIfind.Com]",
	"Cacophony - Concerto (2) [MIDIfind.Com]",
	"Cacophony - Speed Metal Symphony (2) [MIDIfind.Com]",
	"Candlemass - Solitude [MIDIfind.Com]",
	"Darkthrone - Transilvanian Hunger (4) [MIDIfind.Com]",
	"Darkthrone - Under A Funeral Moon [MIDIfind.Com]",
	"Darkthrone - Unholy Blackmetal [MIDIfind.Com]",
	"Darkthrone - Valkyrie [MIDIfind.Com]",
	"Dimmu Borgir - Puritania [MIDIfind.Com]",
	"Dio Ronnie James - Holy Diver [MIDIfind.Com]",
	"Eruption - Van Halen",
	"For-Whom-The-Bell-Tolls",
	"HermoðR Á Helferð - Burzum",
	"Ilia Burzum",
	"Jason Becker - Altitudes Solo",
	"Judas Priest - A Touch Of Evil [MIDIfind.Com]",
	"Judas Priest - Breaking The Law [MIDIfind.Com]",
	"Judas Priest - Diamonds And Rust [MIDIfind.Com]",
	"Judas Priest - Electric Eye [MIDIfind.Com]",
	"Judas Priest - Electric Eye Solo 1 [MIDIfind.Com]",
	"Judas Priest - Electric Eye Solo 2nd Part [MIDIfind.Com]",
	"Judas Priest - Grinder [MIDIfind.Com]",
	"Judas Priest - Jugulator [MIDIfind.Com]",
	"Judas Priest - Love Bites [MIDIfind.Com]",
	"Judas Priest - Nightcrawler [MIDIfind.Com]",
	"Judas Priest - Out In The Cold [MIDIfind.Com]",
	"Judas Priest - Painkiller [MIDIfind.Com]",
	"Judas Priest - Revolution [MIDIfind.Com]",
	"Judas Priest - Screaming For Vengeance [MIDIfind.Com]",
	"Judas Priest - The Ripper [MIDIfind.Com]",
	"Judas Priest - The Sentinel [MIDIfind.Com]",
	"Judas Priest - Turbo Lover [MIDIfind.Com]",
	"Judas Priest - Victim Of Changes [MIDIfind.Com]",
	"Judas Priest - Victim Of Changes Intro (Solo) [MIDIfind.Com]",
	"KISS - Detroit Rock City",
	"Kiss - Rock And Roll All Night",
	"Limp Bizkit - Break Stuff (2) [MIDIfind.Com]",
	"Megadeth - Devils Island [MIDIfind.Com]",
	"Megadeth - Hanger 18",
	"Megadeth - In My Darkest Hour [MIDIfind.Com]",
	"Megadeth - Peace Sells [MIDIfind.Com]",
	"Megadeth - Symphony Of Destruction [MIDIfind.Com]",
	"Megadeth - The Conjuring [MIDIfind.Com]",
	"Megadeth - Tornado Of Souls [MIDIfind.Com]",
	"Metallica - And Justice For All [MIDIfind.Com]",
	"Metallica - Anesthesia Pulling Teeth With Wah Sound",
	"Metallica - Battery [MIDIfind.Com]",
	"Metallica - Blackened [MIDIfind.Com]",
	"Metallica - Blackened Reversed (Intro) [MIDIfind.Com]",
	"Metallica - Creeping Death (2) [MIDIfind.Com]",
	"Metallica - Damage Inc [MIDIfind.Com]",
	"Metallica - Disposable Heroes [MIDIfind.Com]",
	"Metallica - Dyers Eve [MIDIfind.Com]",
	"Metallica - Enter Sandman [MIDIfind.Com]",
	"Metallica - Fade To Black [MIDIfind.Com]",
	"Metallica - Fight Fire With Fire (7) [MIDIfind.Com]",
	"Metallica - Fight Fire With Fire [MIDIfind.Com]",
	"Metallica - For Whom The Bell Tolls [MIDIfind.Com]",
	"Metallica - Frayed Ends Of Sanity [MIDIfind.Com]",
	"Metallica - Fuel [MIDIfind.Com]",
	"Metallica - Hit The Lights [MIDIfind.Com]",
	"Metallica - Leper Messiah [MIDIfind.Com]",
	"Metallica - Lux ÆTerna",
	"Metallica - No Remorse [MIDIfind.Com]",
	"Metallica - Of Wolf And Man (3) [MIDIfind.Com]",
	"Metallica - One",
	"Metallica - One [MIDIfind.Com]",
	"Metallica - Orion [MIDIfind.Com]",
	"Metallica - Phantom Lord [MIDIfind.Com]",
	"Metallica - Ride The Lightning",
	"Metallica - Sad But True [MIDIfind.Com]",
	"Metallica - Seek And Destroy [MIDIfind.Com]",
	"Metallica - Some Kind Of Monster [MIDIfind.Com]",
	"Metallica - The Four Horseman [MIDIfind.Com]",
	"Metallica - The Thing That Should Not Be [MIDIfind.Com]",
	"Metallica - Trapped Under Ice [MIDIfind.Com]",
	"Metallica - Welcome Home Sanatarium [MIDIfind.Com]",
	"Metallica - Wherever I May Roam [MIDIfind.Com]",
	"Metallica - Whiplash [MIDIfind.Com]",
	"Michael Jackson - Thriller",
	"Monster - Skillet",
	"Osbourne Ozzy - Crazy Train [MIDIfind.Com]",
	"Osbourne Ozzy - Hellraiser [MIDIfind.Com]",
	"Osbourne Ozzy - I Don'T Wanna Stop [MIDIfind.Com]",
	"Osbourne Ozzy - Mr Crowley [MIDIfind.Com]",
	"Osbourne Ozzy - No More Tears [MIDIfind.Com]",
	"Osbourne Ozzy - Perry Mason [MIDIfind.Com]",
	"Pantera - By Demons Be Driven [MIDIfind.Com]",
	"Pantera - Cemetery Gates (7) [MIDIfind.Com]",
	"Pantera - Cowboys From Hell [MIDIfind.Com]",
	"Pantera - Domination",
	"Pantera - Floods [MIDIfind.Com]",
	"Pantera - Shedding Skin [MIDIfind.Com]",
	"Pantera - Slaughtered [MIDIfind.Com]",
	"Pantera - The Art Of Shredding",
	"Pantera - This Love [MIDIfind.Com]",
	"Pantera - Walk (3)",
	"Rage Against The Machine - Killing In The Name (2) [MIDIfind.Com]",
	"Rage Against The Machine - Killing In The Name [MIDIfind.Com]",
	"Rammstein - Du Hast [MIDIfind.Com]",
	"Rammstein - Sonne [MIDIfind.Com]",
	"Slayer - Angel Of Death (2) [MIDIfind.Com]",
	"Slayer - Raining Blood [MIDIfind.Com]",
	"Symphony X - Sea Of Lies First Part",
	"The Crying Orc - Burzum",
	"Three Days Grace - I Hate Everything About You [MIDIfind.Com]",
	"Through The Fire And Flames - DragonForce",
	"Tool - Schism (3) [MIDIfind.Com]",
	"Toxicity - System Of A Down",
	"Trilogy Suite Op 5 - Yngwie Malmsteen",
	"Type O Negative - Black No 1 (2) [MIDIfind.Com]",
	"Type O Negative - Christian Woman [MIDIfind.Com]",
	"Type O Negative - I Don'T Wanna Be Me [MIDIfind.Com]",
	"Type O Negative - My Girlfriend'S Girlfriend (2) [MIDIfind.Com]",
	"Type O Negative - Out Of The Fire [MIDIfind.Com]",
	"Vai Steve - For The Love Of God [MIDIfind.Com]",
	"VØJ & Narvent - Memory Reboot",
	"WASP - On Your Knees [MIDIfind.Com]",
	"Мастер - 2000 лет (Иуда) [MIDIfind.Com]",
	"Мастер - Берегись [MIDIfind.Com]",
	"Мастер - Мастер [MIDIfind.Com]",
}