-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"04-Hypnotize",
	"Deftones - Be Quiet And Drive [MIDIfind.Com]",
	"Deftones - Change In The House Of Flies [MIDIfind.Com]",
	"Deftones - Engine Number (9) [MIDIfind.Com]",
	"Deftones - Knife Prty-06-24-2026",
	"Deftones - My Own Summer (Shove It)",
	"Deftones - My Own Summer Shove It [MIDIfind.Com]",
	"Deftones-Be Quiet And Drive-06-27-2026",
	"Deftones-Beauty School-05-02-2026",
	"Deftones-Departing The Body-03-28-2026",
	"Deftones-Rosemary-05-02-2026",
	"Korn - Blind",
	"Korn - Falling Away From Me [MIDIfind.Com]",
	"Korn - Freak On A Leash [MIDIfind.Com]",
	"La Distancia Para Un Duelo",
	"Limp Bizkit - Break Stuff (2) [MIDIfind.Com]",
	"Linkin Park - Numb [MIDIfind.Com]",
	"Linkin Park - One Step Closer [MIDIfind.Com]",
	"Linkin Park - Papercut [MIDIfind.Com]",
	"Metallica - So What [MIDIfind.Com]",
	"Psychosocial - Slipknot",
	"Slipknot - Eyeless (2) [MIDIfind.Com]",
	"Static-X - I'M With Stupid [MIDIfind.Com]",
	"Static-X - Push It (2) [MIDIfind.Com]",
	"Sweet Child O' Mine (Solo) - Guns N Roses",
	"System Of A Down - Aerials [MIDIfind.Com]",
	"System Of A Down - Sugar [MIDIfind.Com]",
	"System Of A Down - Suite Pee [MIDIfind.Com]",
	"System Of A Down - War (4) [MIDIfind.Com]",
}