-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1 House Theme - Dexter - Daniel Licht",
	"1Great Fairy Fountain Theme",
	"1JoJo Vento Aureo OP 2 Traitor'S Requiem (Uragirimono No Requiem)",
	"1Jotaro'S Theme From Jojo'S Bizarre Adventures Stardust Crusaders",
	"1Red Swan - Attack On Titan Season 3 Opening",
	"Deadline-024-Roblox-Main-Menu-Soundtrack-Virtue-UNOFFICIAL- Get-Save",
	"Dire, Dire Docks (Super Mario 64)",
	"Doom - E1M1 (GM MIDI)",
	"Ella Baila Sola Eslabon Armado Y Peso Pluma",
	"Fastest-Thing-Alive-Full-Version (2)",
	"Fist-Bump (1) (1).Gtr",
	"Gary Moore.Still Got The Blues",
	"Ginyu Force Theme - [Faulconer Productions]",
	"Gohan Fights Frieza [Clean Cut]",
	"Gotenks Is Born - [Faulconer Productions]",
	"Grand Theft Auto San Andreas - Intro [MIDIfind.Com]",
	"Josh Hawke - Seisyun Complex",
	"Metro Exodus - A New Home (Guitar Cover) [MIDIfind.Com]",
	"Metro Exodus - Race Against Fate (Fingerstyle) [MIDIfind.Com]",
	"Metro Exodus - Theme From The Main Menu.Gtr",
	"Misc Covers-Full Theme By JoJo Steel Ball Run-07-04-2026",
	"Misc Covers-Jotaro'S Theme By JJBA-07-04-2026",
	"NAZARETH.Love Hurt",
	"Nine Thou (Grant Mohrman Superstars Remix)",
	"OFFICIAL Roblox Bakon Theme Song",
	"Pink Floyd - Comfortably Numb",
	"Queen - Bohemian Rhapsody",
	"Seek (Among Us) NEW",
	"Sonic-Drive (1)",
	"The Dragon Theme (Original) [Clean Cut]",
	"The Legend Of Zelda Great Fairy Fountain (Piano Cover)",
	"ULTRAKILL - War Without Reason",
	"Vegeta Fights Frieza [Clean Cut]",
	"War Without Reason ULTRAKILL 7-4 By Strix",
	"What I'M Made Of",
	"What I'M Made Of… (2026 AI Version) (1)",
	"Wonderful-Tonight-3",
}