-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1 House Theme - Dexter - Daniel Licht",
	"1Great Fairy Fountain Theme",
	"1JoJo Vento Aureo OP 2 Traitor'S Requiem (Uragirimono No Requiem)",
	"1Jotaro'S Theme From Jojo'S Bizarre Adventures Stardust Crusaders",
	"1Red Swan - Attack On Titan Season 3 Opening",
	"Deadline-024-Roblox-Main-Menu-Soundtrack-Virtue-UNOFFICIAL- Get-Save",
	"Dire, Dire Docks (Super Mario 64)",
	"Doom - E1M1 (GM MIDI)",
	"Ella Baila Sola Eslabon Armado Y Peso Pluma",
	"Gohan Fights Frieza [Clean Cut]",
	"Grand Theft Auto San Andreas - Intro [MIDIfind.Com]",
	"Metro Exodus - A New Home (Guitar Cover) [MIDIfind.Com]",
	"Metro Exodus - Race Against Fate (Fingerstyle) [MIDIfind.Com]",
	"Metro Exodus - Theme From The Main Menu.Gtr",
	"Misc Covers-Full Theme By JoJo Steel Ball Run-07-04-2026",
	"Misc Covers-Jotaro'S Theme By JJBA-07-04-2026",
	"NAZARETH.Love Hurt",
	"OFFICIAL Roblox Bakon Theme Song",
	"Queen - Bohemian Rhapsody",
	"Seek (Among Us) NEW",
	"The Legend Of Zelda Great Fairy Fountain (Piano Cover)",
	"Vegeta Fights Frieza [Clean Cut]",
	"Wonderful-Tonight-3",
}