-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Love - Wave To Earth (웨이브 투 어스) (Piano)",
	"Bad Apple Full Version",
	"Black Or White (Single Version)",
	"Blinding Lights - The Weeknd (Piano-Vocal-Guitar)",
	"Buong Doi Tay Nhau Ra",
	"Cause I Love You - Noo Phuoc Thinh Piano",
	"ChúNg Ta KhôNg ThuộC Về Nhau",
	"COME MY WAY",
	"CơN MưA Ngang Qua 2",
	"CơN MưA Ngang Qua Remix",
	"Flower Dance - DJ Okawari",
	"Flower Dance Had",
	"HãY Trao Cho Anh",
	"Ii",
	"KhôNg PhảI Là DạNg VừA đâU Ost",
	"Love Story X Golden Brown",
	"NắNg ấM Xa DầN - As One",
	"Never Gonna Give You Up",
	"Như NgàY HôM Qua",
	"Take Me Hand",
	"TháI BìNh Mồ HôI RơI",
	"There-S-No-One-At-All",
}