-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Caravan (From 'Whiplash')",
	"1Is It Really You - Sleep Token, Loathe",
	"Black Hole Sun - Soundgardenn",
	"Break By Alex G",
	"Gilbert Paul - Guitar Sequences [MIDIfind.Com]",
	"Holiday By Weezer-07-06-2026",
	"Lucy~ By Corbon Amodio",
	"Misc Covers-Loneliness By Decalius-07-04-2026",
	"Misc Covers-Made Your Mark-07-04-2026",
	"Misc Covers-Poppies Lane Memoryy By Slank",
	"Misc Covers-Restless By Untitled-07-04-2026",
	"Misc Covers-Sempurna By Andra And The Backbone-07-04-2026",
	"Misc Covers-Unslept (Accurate Pitch) By Miraidempa-07-04-2026",
	"Nope Your Too Late I Already Died By WifiSkeleton",
	"Sarah By Alex G",
	"Sayonara Cross Teck-07-04-2026",
	"Smashing Pumpkins - 1979",
	"Vai Steve - For The Love Of God (5) [MIDIfind.Com]",
	"Wonderless - Pierce The Veil",
}