-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"50 Nirvana RIFFS",
	"Breed - Nirvana (TABS And Vocals)",
	"Green Day - American Idiot (2) [MIDIfind.Com]",
	"Green Day - Are We The Waiting [MIDIfind.Com]",
	"Green Day - Basket Case [MIDIfind.Com]",
	"Green Day - Boulevard Of Broken Dreams [MIDIfind.Com]",
	"Green Day - Brain Stew [MIDIfind.Com]",
	"Green Day - Burnout [MIDIfind.Com]",
	"Green Day - Extraordinary Girl [MIDIfind.Com]",
	"Green Day - Give Me Novacaine [MIDIfind.Com]",
	"Green Day - Holiday [MIDIfind.Com]",
	"Green Day - Homecoming [MIDIfind.Com]",
	"Green Day - Jesus Of Suburbia (2) [MIDIfind.Com]",
	"Green Day - Letterbomb [MIDIfind.Com]",
	"Green Day - She'S A Rebel [MIDIfind.Com]",
	"Green Day - Whatsername [MIDIfind.Com]",
	"Green Day - When I Come Around [MIDIfind.Com]",
	"Green Dayst Jimmy",
	"Nirvana - Big Long Now",
	"Nirvana - Big Long Now (4) [MIDIfind.Com]",
	"Nirvana - Here She Comes Now (3) [MIDIfind.Com]",
	"Nirvana - Love Buzz (7) [MIDIfind.Com]",
	"Nirvana - Paper Cuts (2) [MIDIfind.Com]",
	"Nirvana - Paper Cuts [MIDIfind.Com]",
	"Nirvana - Sifting (3) [MIDIfind.Com]",
	"Nirvanararities Talk To Me",
	"Paper Cuts - Nirvana (Piano-Vocal-Guitar)",
	"Rape Me - Nirvana",
	"Sex Pistols - Anarchy In The UK (2) [MIDIfind.Com]",
	"Territorial - Pissings",
}