-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"50 Nirvana RIFFS",
	"Breed - Nirvana (TABS And Vocals)",
	"Green Day - American Idiot (2) [MIDIfind.Com]",
	"Green Day - Are We The Waiting [MIDIfind.Com]",
	"Green Day - Basket Case [MIDIfind.Com]",
	"Green Day - Boulevard Of Broken Dreams [MIDIfind.Com]",
	"Green Day - Brain Stew [MIDIfind.Com]",
	"Green Day - Burnout [MIDIfind.Com]",
	"Green Day - Extraordinary Girl [MIDIfind.Com]",
	"Green Day - Give Me Novacaine [MIDIfind.Com]",
	"Green Day - Holiday [MIDIfind.Com]",
	"Green Day - Homecoming [MIDIfind.Com]",
	"Green Day - Jesus Of Suburbia (2) [MIDIfind.Com]",
	"Green Day - Letterbomb [MIDIfind.Com]",
	"Green Day - She'S A Rebel [MIDIfind.Com]",
	"Green Day - Whatsername [MIDIfind.Com]",
	"Green Day - When I Come Around [MIDIfind.Com]",
	"Green Dayst Jimmy",
	"Jesus Doesn'T Want Me For A Sunbeam - Nirvana (Piano-Vocal-Guitar)",
	"Lake Of Fire - Nirvana (Piano-Vocal-Guitar)",
	"Nirvana - Aero Zeppelin (4) [MIDIfind.Com]",
	"Nirvana - Big Cheese (4) [MIDIfind.Com]",
	"Nirvana - Big Long Now",
	"Nirvana - Big Long Now (4) [MIDIfind.Com]",
	"Nirvana - Curmudgeon [MIDIfind.Com]",
	"Nirvana - Dive (7) [MIDIfind.Com]",
	"Nirvana - Dive (7) [MIDIfind.Com] (1)",
	"Nirvana - Here She Comes Now (3) [MIDIfind.Com]",
	"Nirvana - Love Buzz (7) [MIDIfind.Com]",
	"Nirvana - Molly'S Lips (3) [MIDIfind.Com]",
	"Nirvana - Oh Me (2) [MIDIfind.Com]",
	"Nirvana - Paper Cuts (2) [MIDIfind.Com]",
	"Nirvana - Paper Cuts [MIDIfind.Com]",
	"Nirvana - Plateau (3) [MIDIfind.Com]",
	"Nirvana - Return Of The Rat (2) [MIDIfind.Com]",
	"Nirvana - Sifting (3) [MIDIfind.Com]",
	"Nirvana - Son Of A Gun (3) [MIDIfind.Com]",
	"Nirvana - Stain (4) [MIDIfind.Com]",
	"Nirvanableach Big Cheese",
	"Nirvanableach Downer",
	"Nirvanableach Love Buzz",
	"Nirvanableach Scoff",
	"Nirvanaincesticide Beeswax",
	"Nirvanaincesticide Dive",
	"Nirvanaincesticide Hairspray Queen",
	"Nirvanaincesticide Turnaround",
	"Nirvanamuddy Banks Spank Thru",
	"Nirvananevermind Endless Nameless",
	"Nirvanararities D7",
	"Nirvanararities Even In His Youth",
	"Nirvanararities Oh The Guilt",
	"Nirvanararities Opinion",
	"Nirvanararities Talk To Me",
	"Nirvanararities The Money Will Roll Right In",
	"Nirvanaverse Chorus Verse",
	"Paper Cuts - Nirvana (Piano-Vocal-Guitar)",
	"Rape Me - Nirvana",
	"Sex Pistols - Anarchy In The UK (2) [MIDIfind.Com]",
	"Swap Meet - Nirvana (Piano-Vocal-Guitar)",
	"Territorial - Pissings",
	"The Man Who Sold The World - Nirvana",
	"Where Did You Sleep Last Night - Nirvana",
}