-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"21 Guns - Green Day (Piano-Vocal-Guitar)",
	"ACDC - Thunderstruck [MIDIfind.Com]",
	"Bismarck - Sabaton Piano Arrangement",
	"Chop Suey - System Of A Down",
	"Come As You Are (Unplugged) - Nirvana Bass",
	"Come As You Are (Unplugged) - Nirvana Guitar",
	"Come As You Are Nirvana Bass",
	"Come As You Are Nirvana Guitar",
	"Free Bird - Lynyrd Skynyrd",
	"Gorillaz - Feel Good Inc [MIDIfind.Com]",
	"Imagine - John Lennon",
	"Lonesome Town - Ricky Nelson",
	"Metallica - Master Of Puppets (22) [MIDIfind.Com]",
	"Michael Jackson - Beat It",
	"Nirvana - Smell Like Teen Spirit [MIDIfind.Com]",
	"Nirvana - Smell Like Teen Spirit [MIDIfind.Com] (1)",
	"Rachmaninoff - Piano Concerto No. 2 Op. 18 - 2nd Mvmt - Piano Solo",
	"Romantic Homicide",
	"Soda Stereo - De Musica Ligera [MIDIfind.Com]",
	"System Of A Down - Toxicity [MIDIfind.Com]",
}