-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"21 Guns - Green Day (Piano-Vocal-Guitar)",
	"ACDC - Thunderstruck [MIDIfind.Com]",
	"ACDC.Highway To Hell K",
	"ACDC.TNT",
	"Alice In Chains - Damm That River [MIDIfind.Com]",
	"Alice In Chains - It Ain'T Like It [MIDIfind.Com]",
	"Alice In Chains - Man In A Box",
	"Alice In Chains - Nutshell [MIDIfind.Com]",
	"Alice In Chains - Rotten Apple",
	"Alice In Chains - Sludge Factory [MIDIfind.Com]",
	"Alice In Chains - Would(3) [MIDIfind.Com]",
	"All-My-Loving-1",
	"American Football - Never Meant",
	"Arctic Monkeys - Crying Lightning [MIDIfind.Com]",
	"AUD DW0234",
	"Avenged Sevenfold - Seize The Day [MIDIfind.Com]",
	"Beatles It Wont Be Long",
	"Beggin-Maneskin.Mid",
	"Bismarck - Sabaton Piano Arrangement",
	"Black Rover - Black Clover (OP 3)",
	"Black Sabbath - Iron Man",
	"Black Sabbath - Iron Man-Drum Kit",
	"Black Sabbath - Paranoid [MIDIfind.Com]",
	"Blur - Song 2 [MIDIfind.Com]",
	"Chamber Of Reflection - Mac DeMarcoBass",
	"Chamber Of Reflection - Mac DeMarcoLead",
	"Chop Suey - System Of A Down",
	"Come As You Are (Unplugged) - Nirvana Bass",
	"Come As You Are (Unplugged) - Nirvana Guitar",
	"Come As You Are Nirvana Bass",
	"Come As You Are Nirvana Guitar",
	"Creed - One Last Breath [MIDIfind.Com]",
	"Crybaby - Destroy Boys",
	"Daft Punk - Robot Rock [MIDIfind.Com]",
	"Dont Say Lazy",
	"Flamewall By Camellia",
	"Flying Through The Sky (Ram Ranch)",
	"Fortunate Son - Creedance Clearwater Revival",
	"Fortunate Son - Creedance Clearwater Revival-Electric Bass, Fingered Bass",
	"Fortunate Son - Creedance Clearwater RevivalLEAD",
	"Franz Ferdinand - Take Me Out (2) [MIDIfind.Com]",
	"Free Bird - Lynyrd Skynyrd",
	"Gorillaz - Feel Good Inc [MIDIfind.Com]",
	"Heart Shaped Box - Nirvana",
	"Hoobastank - The Reason (2) [MIDIfind.Com]",
	"Imagine - John Lennon",
	"Judas Priest - You'Ve Got Another Thing Comin [MIDIfind.Com]",
	"Layla - Derek And The Dominos Ft Eric Clapton",
	"Layla (Unplugged) - Eric Clapton",
	"Linkin Park - Given Up [MIDIfind.Com]",
	"Living Colorcult Of Personality",
	"Lonesome Town - Ricky Nelson",
	"Megalo Box 2",
	"Megalovania Undertale",
	"Metallica - Master Of Puppets (22) [MIDIfind.Com]",
	"Michael Jackson - Beat It",
	"Michael Jackson - Dirty Diana",
	"Michael%20Jackson%20-%20Beat%20It",
	"Misc Covers-Steel Ball Run Teaser Trailer",
	"My Chemical Romance - Thank You For The Venom [MIDIfind.Com]",
	"My Chemical Romance - You Know What They Do To Guys Like Us In Prison (2) [MIDIfind.Com]",
	"Never Meant - American Football",
	"Nirvana - About A Girl (MTV Unplugged) [MIDIfind.Com]",
	"Nirvana - All Apologies [MIDIfind.Com]",
	"Nirvana - Aneurysm [MIDIfind.Com]",
	"Nirvana - Been A Son (2) [MIDIfind.Com]",
	"Nirvana - Blew (2) [MIDIfind.Com]",
	"Nirvana - Breed (2) [MIDIfind.Com]",
	"Nirvana - Drain You (2) [MIDIfind.Com]",
	"Nirvana - Drain You [MIDIfind.Com]",
	"Nirvana - Dumb [MIDIfind.Com]",
	"Nirvana - Heart Shaped Box [MIDIfind.Com]",
	"Nirvana - In Bloom (2) [MIDIfind.Com]",
	"Nirvana - In Bloom [MIDIfind.Com]",
	"Nirvana - Lithium (3) [MIDIfind.Com]",
	"Nirvana - Lounge Act [MIDIfind.Com]",
	"Nirvana - Mexican Seafood [MIDIfind.Com]",
	"Nirvana - Milk It [MIDIfind.Com]",
	"Nirvana - Nirvana Lithium Live MTV Vma 1992 [MIDIfind.Com]",
	"Nirvana - On A Plain (2) [MIDIfind.Com]",
	"Nirvana - Opinion [MIDIfind.Com]",
	"Nirvana - Rape Me [MIDIfind.Com]",
	"Nirvana - Sappy",
	"Nirvana - Scentless Apprentice (3) [MIDIfind.Com]",
	"Nirvana - Seasons In The Sun [MIDIfind.Com]",
	"Nirvana - Serve The Servants (5) [MIDIfind.Com]",
	"Nirvana - Serve The Servants [MIDIfind.Com]",
	"Nirvana - Sliver (2) [MIDIfind.Com]",
	"Nirvana - Smell Like Teen Spirit [MIDIfind.Com]",
	"Nirvana - Smell Like Teen Spirit [MIDIfind.Com] (1)",
	"Nirvana - Something In The Way",
	"Nirvana - Verse Chorus Verse (2) [MIDIfind.Com]",
	"Nirvana - You Know You'Re Right [MIDIfind.Com]",
	"Oasis - Cigarettes Alcohol [MIDIfind.Com]",
	"Oasis - Don'T Look Back In Anger",
	"Oasis - Shakermaker",
	"Oasis - She'S Electric [MIDIfind.Com]",
	"Oasis - Slide Away [MIDIfind.Com]",
	"Oasis - Supersonic [MIDIfind.Com]",
	"Oasis - Wonderwall",
	"Oasis-Dont Look Back In Anger",
	"OASIS.Stand By Me",
	"Paramore - Misery Business [MIDIfind.Com]",
	"Pearl Jam - Black (2) [MIDIfind.Com]",
	"Pearl Jam - Black [MIDIfind.Com]",
	"Pearl Jam - Even Flow (2) [MIDIfind.Com]",
	"Pearl Jam - Even Flow (3) [MIDIfind.Com]",
	"Pearl Jam - Even Flow [MIDIfind.Com]",
	"Queen - Bohemian Rhapsody (Guitar Solo) [MIDIfind.Com]",
	"Rachmaninoff - Piano Concerto No. 2 Op. 18 - 2nd Mvmt - Piano Solo",
	"Radiohead - 15 Step [MIDIfind.Com]",
	"Radiohead - 2+2=5 [MIDIfind.Com]",
	"Radiohead - Everything In Its Right Place [MIDIfind.Com]",
	"Radiohead - Fake Plastic Trees [MIDIfind.Com]",
	"Radiohead - Just [MIDIfind.Com]",
	"Radiohead - Kid A [MIDIfind.Com]",
	"Radiohead - Lucky [MIDIfind.Com]",
	"Radiohead - Motion Picture Soundtrack [MIDIfind.Com]",
	"Radiohead - No Surprises [MIDIfind.Com]",
	"Radiohead - Paranoid Android [MIDIfind.Com]",
	"Radiohead - Subterranean Homesick Alien [MIDIfind.Com]",
	"Radiohead - The Bends [MIDIfind.Com]",
	"Ratt - Lay It Down [MIDIfind.Com]",
	"Ratt - Round And Round [MIDIfind.Com]",
	"Romantic Homicide",
	"Samba De Verao (So Nice!)",
	"Scorpions - No One Like You (2) [MIDIfind.Com]",
	"Scorpions - Rock You Like A Hurricane [MIDIfind.Com]",
	"Seven Nation Army",
	"Shadow Bonnie - Bonnie Lullaby",
	"Simple Plan - Perfect [MIDIfind.Com]",
	"Skid Row - 18 And Life [MIDIfind.Com]",
	"Skillet - Monster (2) [MIDIfind.Com]",
	"Skillet - Monster [MIDIfind.Com]",
	"Snow (Hey Oh!)",
	"Soda Stereo - De Musica Ligera [MIDIfind.Com]",
	"Soda Stereo - Tratame Suavemente [MIDIfind.Com]",
	"Soundgarden - Spoonman [MIDIfind.Com]",
	"Still-Loving-You",
	"Stone Temple Pilots - Creep (3) [MIDIfind.Com]",
	"Stone Temple Pilots - Creep [MIDIfind.Com]",
	"Stone Temple Pilots - Plush [MIDIfind.Com]",
	"Stone Temple Pilots - Sex Type Thing [MIDIfind.Com]",
	"Stone Temple Pilots - Silvergun Superman [MIDIfind.Com]",
	"Strokes (The) - Last Nite [MIDIfind.Com]",
	"Strokes (The) - The End Has No End (7) [MIDIfind.Com]",
	"System Of A Down - Toxicity [MIDIfind.Com]",
	"TF2 Kazotsky Kick",
	"The Last Of Us - Main Theme (2) [MIDIfind.Com]",
	"The Trooper",
	"Vai Steve - For The Love Of God [MIDIfind.Com]",
	"Van Halen - Ain'T Talkin Bout Love (2) [MIDIfind.Com]",
	"War Pigs - Black Sabbath",
	"WASP - I Wanna Be Somebody (2) [MIDIfind.Com]",
	"WASP - Sleeping In The Fire [MIDIfind.Com]",
	"Weird Fishes Arpeggi - Radiohead Weird Fishes Arpeggi - Radiohead",
	"Welcome To The Jungle",
	"What I'Ve Done - Linkin Park",
	"Yara Yara Ya Phonk - Sua Amiga Eu Vou Pegar - MC Lan, MC WM SLOWED",
	"YTDown",
	"Ария - Я свободен [MIDIfind.Com]",
	"Король и Шут - Прыгну со скалы [MIDIfind.Com]",
	"Пикник - Египтянин [MIDIfind.Com]",
	"Пикник - Королевство кривых [MIDIfind.Com]",
}