-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"21 Guns - Green Day (Piano-Vocal-Guitar)",
	"ACDC - Thunderstruck [MIDIfind.Com]",
	"American Football - Never Meant",
	"Bismarck - Sabaton Piano Arrangement",
	"Black Sabbath - Iron Man",
	"Black Sabbath - Iron Man-Drum Kit",
	"Chop Suey - System Of A Down",
	"Come As You Are (Unplugged) - Nirvana Bass",
	"Come As You Are (Unplugged) - Nirvana Guitar",
	"Come As You Are Nirvana Bass",
	"Come As You Are Nirvana Guitar",
	"Creed - One Last Breath [MIDIfind.Com]",
	"Dont Say Lazy",
	"Free Bird - Lynyrd Skynyrd",
	"Gorillaz - Feel Good Inc [MIDIfind.Com]",
	"Heart Shaped Box - Nirvana",
	"Hoobastank - The Reason (2) [MIDIfind.Com]",
	"Imagine - John Lennon",
	"Lonesome Town - Ricky Nelson",
	"Metallica - Master Of Puppets (22) [MIDIfind.Com]",
	"Michael Jackson - Beat It",
	"Michael%20Jackson%20-%20Beat%20It",
	"Never Meant - American Football",
	"Nirvana - Smell Like Teen Spirit [MIDIfind.Com]",
	"Nirvana - Smell Like Teen Spirit [MIDIfind.Com] (1)",
	"Nirvana - Something In The Way",
	"Paramore - Misery Business [MIDIfind.Com]",
	"Rachmaninoff - Piano Concerto No. 2 Op. 18 - 2nd Mvmt - Piano Solo",
	"Romantic Homicide",
	"Simple Plan - Perfect [MIDIfind.Com]",
	"Snow (Hey Oh!)",
	"Soda Stereo - De Musica Ligera [MIDIfind.Com]",
	"Strokes (The) - Last Nite [MIDIfind.Com]",
	"Strokes (The) - The End Has No End (7) [MIDIfind.Com]",
	"System Of A Down - Toxicity [MIDIfind.Com]",
	"TF2 Kazotsky Kick",
	"The Last Of Us - Main Theme (2) [MIDIfind.Com]",
	"The Trooper",
	"War Pigs - Black Sabbath",
	"Weird Fishes Arpeggi - Radiohead Weird Fishes Arpeggi - Radiohead",
	"Welcome To The Jungle",
	"What I'Ve Done - Linkin Park",
	"Yara Yara Ya Phonk - Sua Amiga Eu Vou Pegar - MC Lan, MC WM SLOWED",
}