-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Karma Police - Radiohead, Thomas Yorke (Piano Solo)",
	"1La Foule, Edith Piaf, Piano-Chant",
	"1Robert Miles - Children",
	"1Stranded Lullaby (Piano)",
	"1White Ball - Miracle Musical (ミラクルミュージカル) White Ball",
	"AC DC - Thunderstruck - Opening Guitar Solo",
	"Ariana Grande - 7 Rings - Solo - Klaus Lightsbane",
	"As Time Flies - Tyrique Sayre (Piano Solo)",
	"Baggy Trousers - Madness (Piano-Voice-Guitar)",
	"Bass Little Girls OB",
	"Bazzi - Mine - Solo - Ravel Falskhern",
	"Billie Eilish - Bad Guy - Octet - Thymm Rayne",
	"Billie Eilish - Wildflower - Solo - Skynyrd Fraefolgwyn",
	"Black Hole Sun - Soundgarden",
	"Bruno Mars Ft. Lady Gaga - Die With A Smile - Solo - Ravel Falskhern",
	"Camila Cabello And Shawn Mendes - SeñOrita - Solo - Ravel Falskhern",
	"Canon In D For Guitar Solo",
	"Celine Dion - My Heart Will Go On - Solo - Ravel Falskhern",
	"Christina Perri - A Thousand Years - Solo - Debra VanHouten",
	"Converted Sound Midi",
	"Cyberpunk Edgerunners - I Really Want To Stay At Your House - Solo - Nozomi Tenma",
	"Demon Slayer - Nezuko Theme - Solo - Nozomi Tenma",
	"Demon Slayer - The Mugen Train - Tanjiro'S Dream - Solo - Nozomi Tenma",
	"Demon Slayer- Kamado Tanjiro No Uta - Solo - Zephyr Lathillion",
	"Doraemon Original Soundtrack (Full Version) - Doraemon'S Theme (Doraemon No Uta) - Solo - C' Lynn",
	"Floods Outro",
	"Guitar Lead Little Girls OB",
	"Guitar Rtm Little Girls OB",
	"Guitar-Waltz",
	"Gym Class Hero - Stereo Hearts - Solo - Ravel Falskhern",
	"HãY Trao Cho Anh",
	"Hotel California - Eagles (Solo Guitar)",
	"I Dont Wanna Be Me - Type O Negative",
	"Johnny-Guitar-1",
	"Johnny-Guitar-2",
	"Justin Bieber - Love Yourself - Solo - Ravel Falskhern",
	"Justin Bieber - Sorry - Solo - Ravel Falskhern",
	"JVKE - Golden Hour - Trio - KenTIP",
	"Kate Bush Stranger Things Season 4 - Running Up That Hill - Octet - SnowTheBard",
	"Kendrick Lamar - Luther - Solo - Ravel Falskhern",
	"Let You Break My Heart Again - Laufey",
	"Lonely Day - System Of A Down",
	"Love Story - Taylor Swift - Octet - Harmonia Crystal",
	"Lukas Graham - 7 Years - Solo - Ravel Falskhern",
	"Marshmello Ft. Bastille - Happier - Solo - Ravel Falskhern",
	"MusicNotes Sheet Music - Doja Cat - Say So - Solo - Shiro Astral",
	"Naruto - Sadness And Sorrow - Duet - SnowTheBard",
	"Naruto - Sadness And Sorrow - Octet - SnowTheBard",
	"Night Boat To Cairo - Madness",
	"Olivia Rodrigo - Vampire - Quartet - Skynyrd Fraefolgwyn",
	"One Direction - What Makes You Beautiful - Solo - Ravel Falskhern",
	"Passenger - Let Her Go - Solo - Ravel Falskhern",
	"Post Malone Ft. Ty Dolla $Ign - Psycho - Solo - Ravel Falskhern",
	"Ruth B - Dandelions.",
	"Shawn Mendes - Stitches - Solo - Ravel Falskhern",
	"Shawn Mendes - There'S Nothing Holdin' Me Back - Solo - Ravel Falskhern",
	"Shawn Mendes - Treat You Better - Solo - Ravel Falskhern",
	"Sia - Snowman - Octet - SnowTheBard",
	"Silent-Night-Guitar-Arrangement",
	"Slay The Princess, Brandon Boone - The Princess - Quartet - Sechesin",
	"Somewhere On Musescore. Dumb Me Didn'T Favorite Which Version. - Naruto - Sadness And Sorrow - Solo - Klaus Lightsbane",
	"The Chainsmokers - Closer - Solo - Ravel Falskhern",
	"Vanessa Carlton - A Thousand Miles - Solo - Ravel Falskhern",
	"Vibe Tracks (LIMO) - Nice To You - Octet - SnowTheBard",
	"When You Sleep - My Bloody Valentine",
	"X - Sadame (Guitar Version)",
	"Yung Kai - Blue - Solo - Ravel Falskhern",
	"Zack Tabudlo - Pano - Solo - Ravel Falskhern",
}