-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Karma Police - Radiohead, Thomas Yorke (Piano Solo)",
	"1La Foule, Edith Piaf, Piano-Chant",
	"1Robert Miles - Children",
	"1Stranded Lullaby (Piano)",
	"1White Ball - Miracle Musical (ミラクルミュージカル) White Ball",
	"AC DC - Thunderstruck - Opening Guitar Solo",
	"As Time Flies - Tyrique Sayre (Piano Solo)",
	"Baggy Trousers - Madness (Piano-Voice-Guitar)",
	"Bass Little Girls OB",
	"Black Hole Sun - Soundgarden",
	"Canon In D For Guitar Solo",
	"Floods Outro",
	"Guitar Lead Little Girls OB",
	"Guitar Rtm Little Girls OB",
	"HãY Trao Cho Anh",
	"Hotel California - Eagles (Solo Guitar)",
	"I Dont Wanna Be Me - Type O Negative",
	"Let You Break My Heart Again - Laufey",
	"Lonely Day - System Of A Down",
	"When You Sleep - My Bloody Valentine",
}