return {
    "Anak",
    "Apocalypse - Cigarettes After Sex",
    "Blue-Yung Kai",
    "Can't We Be Friends (guitar chord melody)",
    "Cry - Cigarettes After Sex",
    "DINA MULI - THE ITCHYWORMS (GUITAR SOLO PART)",
    "Di na muli guitar",
    "Di na muli",
    "Ed Sheeran - Shape of You (Guitar cover)",
    "Fly Me to the Moon for Solo Guitar",
    "Here comes the sun - The Beatles",
    "Lucid Dreams",
    "Magbalik by Callaliy",
    "Magbalik- Intro (Real Guitar App)",
    "Making Love Out Of Nothing At All - Air Supply",
    "Married Life for Guitar (from Up) - Michael Giacchino",
    "My way - Frank Sinatra",
    "Photograph - Ed Sheeran",
    "Pirates Of The Caribbean - He's A Pirate - Guitar Tab",
    "Sunflower - Post Malone & Swae Lee",
    "Sunsetz - Cigarettes After Sex",
    "The Sound Of Silence - Simon & Garfunkel",
    "The winner takes it all - ABBA",
    "What A Wonderful World - Louis Armstrong - TABs",
    "You Are My Sunshine",
    "You've got a friend in me Main Theme from Toy Story. Randy Newman. Arrangement for Solo Acoustic",
}
