-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"[Dropped] Gojira - The Art of Dying",
	"37075 Danger-Line (2)",
	"A Little Piece of Heaven - Avenged Sevenfold (With vocals).mid",
	"A.D.I.D.A.S.",
	"AC DC - Back in Black.mid",
	"ACDC - Back in Black (3) [MIDIfind.com]",
	"Avenged Sevenfold - Acid Rain [MIDIfind.com]",
	"Avenged Sevenfold - Almost Easy",
	"Avenged Sevenfold - Bat Country",
	"Avenged Sevenfold - Beast And The Harlot v7",
	"Avenged Sevenfold - Blinded in Chains [MIDIfind.com]",
	"Avenged Sevenfold - Buried Alive [MIDIfind.com]",
	"Avenged Sevenfold - Carry On [MIDIfind.com]",
	"Avenged Sevenfold - Chapter Four [MIDIfind.com]",
	"Avenged Sevenfold - Clairvoyant Disease [MIDIfind.Com]",
	"Avenged Sevenfold - Dancing Dead [MIDIfind.com]",
	"Avenged Sevenfold - Dear God.mid",
	"Avenged Sevenfold - Hail to the King [MIDIfind.com]",
	"Avenged Sevenfold - Heretic [MIDIfind.com]",
	"Avenged Sevenfold - I Won't See You Tonight Part (1) [MIDIfind.com]",
	"Avenged Sevenfold - M.I.A (WIP)",
	"Avenged Sevenfold - Natural Born Killer [MIDIfind.com]",
	"Avenged Sevenfold - Nightmare.mid",
	"Avenged Sevenfold - Nobody [MIDIfind.com]",
	"Avenged Sevenfold - Remenissions   WWW.MIDISFREE.COM",
	"Avenged Sevenfold - Save Me [MIDIfind.com]",
	"Avenged Sevenfold - Second Heartbeat (2)   WWW.MIDISFREE.COM",
	"Avenged Sevenfold - Seize the Day [MIDIfind.com]",
	"Avenged Sevenfold - Shepherd of Fire (2) [MIDIfind.com]",
	"Avenged Sevenfold - Sidewinder [MIDIfind.com]",
	"Avenged Sevenfold - St James [MIDIfind.com]",
	"Avenged Sevenfold - The Wicked End   WWW.MIDISFREE.COM",
	"Avenged Sevenfold - This Means War [MIDIfind.com]",
	"Avenged Sevenfold - Until the End [MIDIfind.com]",
	"Avenged Sevenfold - Warmness on the Soul [MIDIfind.com]",
	"Avenged Sevenfold - Welcome to the Family",
	"Avenged Sevenfold~Critical Acclaim",
	"BeQuickOrBeDead",
	"Bitchslap",
	"Black Sabbath - Paranoid [MIDIfind.Com]",
	"Black-Hole-Sun",
	"Blazed - Heavy Metal Balad [MIDIfind.com]",
	"Blind",
	"Bring Me The Horizon - Happy Song [MIDIfind.com]",
	"Bring Me the Horizon - Pray For Plagues [MIDIfind.com]",
	"Candlemass - Solitude [MIDIfind.Com]",
	"CaughtSomewhereInTime",
	"Clown",
	"Contempt of Cop",
	"Crucify Thy Infant",
	"Danger line (W.I.P)",
	"Deftones - 7 Words [MIDIfind.com]",
	"Deftones - Around the Fur [MIDIfind.com]",
	"Deftones - One Weak [MIDIfind.com]",
	"Dimmu Borgir - Puritania [MIDIfind.Com]",
	"Disasterpiece",
	"DOOM - Theme E1M1",
	"Drum - Afro Latin Ritm [MIDIfind.com]",
	"Drum - Drum Exercise Double Bass Drumming Bobby Jarzombek [MIDIfind.com]",
	"Drum - Drum Exercise Updown Rock N Jazz Flams Funk Rhythms [MIDIfind.com]",
	"Drum - Drums Fill and Solos Patterns [MIDIfind.com]",
	"Drum - Heavy Metal Drums [MIDIfind.com]",
	"Drum - Playing on Hi Hat With Two Hands [MIDIfind.com]",
	"Duality",
	"Duality - Slipknot",
	"Elena Siegman - 115",
	"Eyeless",
	"Faget",
	"Faith No More - A Small Victory [MIDIfind.com]",
	"Faith No More - Ashes to Ashes [MIDIfind.com]",
	"Faith No More - Caffeine [MIDIfind.com]",
	"Faith No More - Collision [MIDIfind.com]",
	"Fiction - Avenged Sevenfold   A7x",
	"FreakOnALeash",
	"Gentley",
	"GoodGod",
	"Gorillaz - Feel Good Inc [MIDIfind.Com]",
	"Guns N' Roses - Sweet Child O' Mine [MIDIfind.com]",
	"HereToStay",
	"I Won't See You Tonight - Avenged Sevenfold",
	"Judas Priest - Electric Eye [MIDIfind.Com]",
	"Judas Priest - Grinder [MIDIfind.Com]",
	"Judas Priest - Revolution [MIDIfind.Com]",
	"Korn - Daddy(1)   WWW.MIDISFREE.COM",
	"Master of Puppets",
	"Megadeth - Holy Wars",
	"Meshuggah- Bleed.mid",
	"Metallica - Battery (2) [MIDIfind.com]",
	"Metallica - Creeping Death (2) [MIDIfind.Com]",
	"Metallica - Fight Fire With Fire (7) [MIDIfind.Com]",
	"Metallica - For Whom The Bell Tolls [MIDIfind.Com]",
	"Metallica - Master Of Puppets (22) [MIDIfind.Com]",
	"Metallica-Enter-Sandman midi",
	"Mushroomhead - 12 Hundred [MIDIfind.com]",
	"Mushroomhead - Episode 29 [MIDIfind.com]",
	"Mushroomhead - Sun Doesn't Rise [MIDIfind.com]",
	"Mushroomhead - The Wrist [MIDIfind.com]",
	"NIRVANA.Smells Like Teen Spirit K",
	"Not Ready To Die",
	"Pantera - Becoming [MIDIfind.com]",
	"Pantera - Cemetery Gates [MIDIfind.com]",
	"PhantomOfTheOpera",
	"Powerslave",
	"Primer 55 - My Girl [MIDIfind.com]",
	"PrisonSong",
	"Rage Against the Machine - Bullet in the Head [MIDIfind.com]",
	"Rage Against the Machine - Down on the Street [MIDIfind.com]",
	"Rage Against the Machine - Killing in the Name with drum (1)",
	"Rage Against the Machine - Rage Against the Machine Know Your Enemy [MIDIfind.com]",
	"Revenga",
	"Scream",
	"Slapshock - Direction [MIDIfind.com]",
	"Slipknot - Before I Forget.drum midi",
	"Slipknot - Dead Memories (5) [MIDIfind.com]",
	"Slipknot - Eyeless",
	"Slipknot - Joey Jordison Drum Solo From Surfacing [MIDIfind.com]",
	"Slipknot - Psychosocial (ver 8 by Thaynan).mid",
	"Slipknot - Scissors [MIDIfind.com]",
	"Slipknot - Vermilion Pt.1   WWW.MIDISFREE.COM",
	"Slipknot - Wait And Bleed.mid",
	"slipknot-sic",
	"Slipknot-Snuff-Anonymous-20210724225809-nonstop2k.com",
	"So-Far-Away",
	"Staind - Can't Believe [MIDIfind.com]",
	"Staind - Ephiphany [MIDIfind.com]",
	"Staind - Staind Fade [MIDIfind.com]",
	"Styx - Heavy Metal Poisoning [MIDIfind.com]",
	"Sugar",
	"System Of A Down - Aerials [MIDIfind.Com]",
	"System Of A Down - Chop Suey! [MIDIfind.Com]",
	"System Of A Down - Sugar [MIDIfind.Com]",
	"The Stage - Avenged Sevenfold by Rgman",
	"Three Days Grace - I Hate Everything About You [MIDIfind.Com]",
	"ThunderStruck - ACDC",
	"Toxicity by System of a Down -- Version 4.2",
	"Unholy Confessions",
	"Valkyrie - Heavy Metal Brigade [MIDIfind.com]",
	"Vega - Heavy Metal Religija [MIDIfind.com]",
	"WASP - I Wanna Be Somebody (2) [MIDIfind.Com]",
}