-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"[Dropped] Gojira - The Art of Dying",
	"2x4",
	"37075 Danger-Line (2)",
	"50 AC DC RIFFS",
	"50 Iron Maiden RIFFS",
	"50 KISS RIFFS",
	"50 Megadeth RIFFS",
	"50 Metallica RIFFS",
	"50 Nirvana RIFFS",
	"50 Pantera RIFFS",
	"A Little Piece of Heaven - Avenged Sevenfold (With vocals).mid",
	"A.D.I.D.A.S.",
	"About A Girl - Nirvana",
	"AC DC - Back in Black.mid",
	"ACDC - Back in Black (3) [MIDIfind.com]",
	"Are You Dead Yet 5",
	"Avenged Sevenfold - A Little Piece Of Heaven (Drum)",
	"Avenged Sevenfold - Acid Rain [MIDIfind.com]",
	"Avenged Sevenfold - Almost Easy",
	"Avenged Sevenfold - Bat Country",
	"Avenged Sevenfold - Beast And The Harlot v7",
	"Avenged Sevenfold - Blinded in Chains [MIDIfind.com]",
	"Avenged Sevenfold - Buried Alive [MIDIfind.com]",
	"Avenged Sevenfold - Carry On [MIDIfind.com]",
	"Avenged Sevenfold - Chapter Four [MIDIfind.com]",
	"Avenged Sevenfold - Clairvoyant Disease [MIDIfind.Com]",
	"Avenged Sevenfold - Dancing Dead [MIDIfind.com]",
	"Avenged Sevenfold - Dear God.mid",
	"Avenged Sevenfold - Hail to the King [MIDIfind.com]",
	"Avenged Sevenfold - Heretic [MIDIfind.com]",
	"Avenged Sevenfold - I Won't See You Tonight Part (1) [MIDIfind.com]",
	"Avenged Sevenfold - M.I.A (WIP)",
	"Avenged Sevenfold - Natural Born Killer [MIDIfind.com]",
	"Avenged Sevenfold - Nightmare (Drum)",
	"Avenged Sevenfold - Nightmare [MIDIfind.Com]",
	"Avenged Sevenfold - Nightmare.mid",
	"Avenged Sevenfold - Nobody [MIDIfind.com]",
	"Avenged Sevenfold - Remenissions   WWW.MIDISFREE.COM",
	"Avenged Sevenfold - Save Me [MIDIfind.com]",
	"Avenged Sevenfold - Second Heartbeat (2)   WWW.MIDISFREE.COM",
	"Avenged Sevenfold - Seize the Day [MIDIfind.com]",
	"Avenged Sevenfold - Shepherd of Fire (2) [MIDIfind.com]",
	"Avenged Sevenfold - Sidewinder [MIDIfind.com]",
	"Avenged Sevenfold - St James [MIDIfind.com]",
	"Avenged Sevenfold - The Wicked End   WWW.MIDISFREE.COM",
	"Avenged Sevenfold - This Means War [MIDIfind.com]",
	"Avenged Sevenfold - Until the End [MIDIfind.com]",
	"Avenged Sevenfold - Warmness on the Soul [MIDIfind.com]",
	"Avenged Sevenfold - Welcome to the Family",
	"Avenged Sevenfold~Critical Acclaim",
	"Bathory - The Return Of The Darkness And Evil",
	"Bathory - Total Destruction",
	"BeQuickOrBeDead",
	"Bitchslap",
	"Black Sabbath - Black Sabbath [MIDIfind.Com]",
	"Black Sabbath - Paranoid [MIDIfind.Com]",
	"Black Sabbath - War Pigs (Drum)",
	"Black-Hole-Sun",
	"Blazed - Heavy Metal Balad [MIDIfind.com]",
	"Blind",
	"Blink-182 - Drum Solo (Rock)",
	"Breed - Nirvana Drums",
	"Bring Me The Horizon - Happy Song [MIDIfind.com]",
	"Bring Me The Horizon - It Never Ends MIDIfind.Com",
	"Bring Me the Horizon - Pray For Plagues [MIDIfind.com]",
	"Bring Me The Horizon - Sleepwalking MIDIfind.Com",
	"Bullet For My Valentine - Tears Don'T Fall [MIDIfind.Com]",
	"Candlemass - Solitude [MIDIfind.Com]",
	"Cannibal Corpse - Hammer Smashed Face (Drum)",
	"Cannibal Corpse - Scourge Of Iron (Drum)",
	"CaughtSomewhereInTime",
	"Chelsea Grin - Recreant [MIDIfind.Com]",
	"Chevelle - Comfortable Liar [MIDIfind.Com]",
	"Clown",
	"Contempt of Cop",
	"Crucify Thy Infant",
	"Cryptopsy - Back To The Worms (Drums)",
	"Cryptopsy - Benedictine Convulsions (Drums)",
	"Cryptopsy - Dead And Dripping (Drums)",
	"Cryptopsy - Defenestration (Drums)",
	"Cryptopsy - Depths You'Ve Fallen (Drums)",
	"Cryptopsy - Graves Of The Fathers (Drums)",
	"Cryptopsy - Mutant Christ (Drums)",
	"Cryptopsy - Slit Your Guts (Drums)",
	"Daft Punk - Robot Rock [MIDIfind.Com]",
	"Danger line (W.I.P)",
	"Death - Crystal Mountain (Drum)",
	"Death - Flesh And The Power It Holds [MIDIfind.Com]",
	"Death - Left To Die (Drum)",
	"Decease The Police(Full Version)",
	"Deftones - 7 Words [MIDIfind.com]",
	"Deftones - Around the Fur [MIDIfind.com]",
	"Deftones - Knife Party (2) [MIDIfind.Com]",
	"Deftones - My Own Summer Shove It [MIDIfind.Com]",
	"Deftones - One Weak [MIDIfind.com]",
	"Dethklok - Thunderhorse [MIDIfind.Com]",
	"Dimmu Borgir - Puritania [MIDIfind.Com]",
	"Disasterpiece",
	"Domination",
	"DOOM - Theme E1M1",
	"DragonForce - Through The Fire And Flames [MIDIfind.Com]",
	"Dream Theater - The Dance Of Eternity",
	"Dream Theater - The Dance Of Eternity (5) [MIDIfind.Com]",
	"Drum - Afro Latin Ritm [MIDIfind.com]",
	"Drum - Drum Exercise Double Bass Drumming Bobby Jarzombek [MIDIfind.com]",
	"Drum - Drum Exercise Updown Rock N Jazz Flams Funk Rhythms [MIDIfind.com]",
	"Drum - Drums Fill and Solos Patterns [MIDIfind.com]",
	"Drum - Heavy Metal Drums [MIDIfind.com]",
	"Drum - Playing on Hi Hat With Two Hands [MIDIfind.com]",
	"Drum Akatsuki Babymetal Live Wembley Arena 2016",
	"Drum Awadama Fever BABYMETAL",
	"Drum Awadama Fever LIVE BABYMETAL",
	"Drum Gimme Chocolate BABYMETAL",
	"Drum San Sebastian Sonata Arctica",
	"Drum-Kimi To Anime Ga Mitai-BABYMETAL",
	"Drums MIDI",
	"Duality",
	"Duality - Slipknot",
	"Elena Siegman - 115",
	"Event Reborn - Stillbirth [MIDIfind.Com]",
	"Eyeless",
	"Eyeless -Without Metronome Added",
	"Eyeless Cadence",
	"Faget",
	"Faith No More - A Small Victory [MIDIfind.com]",
	"Faith No More - Ashes to Ashes [MIDIfind.com]",
	"Faith No More - Caffeine [MIDIfind.com]",
	"Faith No More - Collision [MIDIfind.com]",
	"FallofTroyTheF.C.P.R.E.M.I.X",
	"Fiction - Avenged Sevenfold   A7x",
	"Floyd The Barber - Nirvana",
	"Frances Farmer Will Have Her Revenge On Seattle",
	"FreakOnALeash",
	"Gentley",
	"Girlfriends - New Computers",
	"GoodGod",
	"Gorillaz - Feel Good Inc [MIDIfind.Com]",
	"Guns N' Roses - Sweet Child O' Mine [MIDIfind.com]",
	"HARDWIRED",
	"Hatebreed - As Diehard As They Come [MIDIfind.Com]",
	"Hatebreed - In Ashes They Shall Reap [MIDIfind.Com]",
	"Hatebreeder",
	"Heart Shaped Box - Nirvana Heart Shaped Box",
	"HereToStay",
	"HIM - Gone With The Sin [MIDIfind.Com]",
	"HIM - Join Me [MIDIfind.Com]",
	"HIM - Poison Girl [MIDIfind.Com]",
	"HIM - Razorblade Kiss [MIDIfind.Com]",
	"HIM - Your Sweet 666 [MIDIfind.Com]",
	"I Hate Myself And Want To Die (Drums + Guitar)",
	"I Won't See You Tonight - Avenged Sevenfold",
	"Iron Maiden - The Trooper (Drum 162 Bpm)",
	"Iron Maiden - The Trooper (Drum)",
	"Judas Priest - Breaking The Law [MIDIfind.Com]",
	"Judas Priest - Diamonds And Rust [MIDIfind.Com]",
	"Judas Priest - Electric Eye [MIDIfind.Com]",
	"Judas Priest - Grinder [MIDIfind.Com]",
	"Judas Priest - Jugulator [MIDIfind.Com]",
	"Judas Priest - Love Bites [MIDIfind.Com]",
	"Judas Priest - Nightcrawler [MIDIfind.Com]",
	"Judas Priest - Revolution [MIDIfind.Com]",
	"Judas Priest - The Sentinel [MIDIfind.Com]",
	"Judas Priest - Victim Of Changes [MIDIfind.Com]",
	"Judas Priest - You'Ve Got Another Thing Comin [MIDIfind.Com]",
	"Korn - A.D.I.D.A.S (Drum)",
	"Korn - Ball Tongue (Drum)",
	"Korn - Ball Tongue [MIDIfind.Com]",
	"Korn - Blind (Drum)",
	"Korn - Daddy(1)   WWW.MIDISFREE.COM",
	"Korn - Falling Away From Me [MIDIfind.Com]",
	"Korn - Freak On A Leash [MIDIfind.Com]",
	"Korn - Got The Life (Drum)",
	"Limp Bizkit - Break Stuff (2) [MIDIfind.Com]",
	"Limp Bizkit - Break Stuff (Drum)",
	"Limp Bizkit - Just Like This (Drum)",
	"Limp Bizkit - Nookie (Drum)",
	"Linkin Park - In The End (Drum)",
	"Linkin Park - Numb [MIDIfind.Com]",
	"Linkin Park - One Step Closer [MIDIfind.Com]",
	"Linkin Park - Papercut [MIDIfind.Com]",
	"Lithium - Nirvana Drums And Leadsheet",
	"Master of Puppets",
	"Megadeth - Devils Island [MIDIfind.Com]",
	"Megadeth - Holy Wars",
	"Megadeth - Holy Wars The Punishment (Drum)",
	"Megadeth - Holy Wars The Punishment Due (Drum Updated)",
	"Megadeth - Holy Wars The Punishment Due [MIDIfind.Com]",
	"Megadeth - Peace Sells [MIDIfind.Com]",
	"Megadeth - Symphony Of Destruction [MIDIfind.Com]",
	"Megadeth - The Conjuring [MIDIfind.Com]",
	"Megadeth - Tornado Of Souls (Drum)",
	"Megadeth - Tornado Of Souls [MIDIfind.Com]",
	"Megadeth-Rust In Peace Polaris",
	"Meshuggah - Bleed (Drum)",
	"Meshuggah- Bleed.mid",
	"Metallica - Am I Evil [MIDIfind.Com]",
	"Metallica - And Justice For All [MIDIfind.Com]",
	"Metallica - Battery (2) [MIDIfind.com]",
	"Metallica - Battery [MIDIfind.Com]",
	"Metallica - Blackened [MIDIfind.Com]",
	"Metallica - Blackened Reversed (Intro) [MIDIfind.Com]",
	"Metallica - Creeping Death (2) [MIDIfind.Com]",
	"Metallica - Disposable Heroes [MIDIfind.Com]",
	"Metallica - Dyers Eve [MIDIfind.Com]",
	"Metallica - Fade To Black [MIDIfind.Com]",
	"Metallica - Fight Fire With Fire (7) [MIDIfind.Com]",
	"Metallica - For Whom The Bell Tolls [MIDIfind.Com]",
	"Metallica - Frantic [MIDIfind.Com]",
	"Metallica - Frayed Ends Of Sanity [MIDIfind.Com]",
	"Metallica - Fuel (2) [MIDIfind.Com]",
	"Metallica - Harvester Of Sorrow (2) [MIDIfind.Com]",
	"Metallica - Hit The Lights [MIDIfind.Com]",
	"Metallica - Last Caress (2) [MIDIfind.Com]",
	"Metallica - Master Of Puppets (22) [MIDIfind.Com]",
	"Metallica - Master Of Puppets (23) [MIDIfind.Com]",
	"Metallica - Master Of Puppets (Drum)",
	"Metallica - Master Of Puppets [MIDIfind.Com]",
	"Metallica - Motorbreath (2) [MIDIfind.Com]",
	"Metallica - My Apocalypse [MIDIfind.Com]",
	"Metallica - No Remorse [MIDIfind.Com]",
	"Metallica - One (Drum)",
	"Metallica - One [MIDIfind.Com]",
	"Metallica - Phantom Lord [MIDIfind.Com]",
	"Metallica - Ride The Lightning (11) [MIDIfind.Com]",
	"Metallica - Sad But True (2) [MIDIfind.Com]",
	"Metallica - Seek And Destroy (Drum)",
	"Metallica - Seek And Destroy [MIDIfind.Com]",
	"Metallica - So What (2) [MIDIfind.Com]",
	"Metallica - Some Kind Of Monster [MIDIfind.Com]",
	"Metallica - Spit Out The Bone",
	"Metallica - St Anger [MIDIfind.Com]",
	"Metallica - The Call Of Ktulu [MIDIfind.Com]",
	"Metallica - The Four Horseman [MIDIfind.Com]",
	"Metallica - The Struggle Within [MIDIfind.Com]",
	"Metallica - The Thing That Should Not Be (3) [MIDIfind.Com]",
	"Metallica - The Unforgiven [MIDIfind.Com]",
	"Metallica - To Live Is To Die (11) [MIDIfind.Com]",
	"Metallica - Trapped Under Ice [MIDIfind.Com]",
	"Metallica - Welcome Home Sanatarium [MIDIfind.Com]",
	"Metallica - Wherever I May Roam [MIDIfind.Com]",
	"Metallica - Whiplash [MIDIfind.Com]",
	"Metallica - Whiskey In The Jar [MIDIfind.Com]",
	"Metallica-Enter-Sandman midi",
	"Motorhead - Ace Of Spades (Drum)",
	"Mudvayne - Dig (Drum)",
	"Mushroomhead - 12 Hundred [MIDIfind.com]",
	"Mushroomhead - Episode 29 [MIDIfind.com]",
	"Mushroomhead - Sun Doesn't Rise [MIDIfind.com]",
	"Mushroomhead - The Wrist [MIDIfind.com]",
	"Necrophagist - Symbiotic In Theory [MIDIfind.Com]",
	"Needled 24 7 2",
	"New Computers - Girlfriends",
	"Nile - Lashed To The Slave Stick [MIDIfind.Com]",
	"Nile - Sarcophagus [MIDIfind.Com]",
	"NIRVANA.Smells Like Teen Spirit K",
	"No Name",
	"No Name (50)",
	"No Name (53)",
	"No Name (55)",
	"No Name (57)",
	"Not Ready To Die",
	"On A Plain - Nirvana",
	"Origin - Swarm [MIDIfind.Com]",
	"Osbourne Ozzy - Crazy Train [MIDIfind.Com]",
	"Osbourne Ozzy - Hellraiser [MIDIfind.Com]",
	"Osbourne Ozzy - I Don'T Wanna Stop [MIDIfind.Com]",
	"Osbourne Ozzy - Mr Crowley [MIDIfind.Com]",
	"Osbourne Ozzy - No More Tears [MIDIfind.Com]",
	"Osbourne Ozzy - Perry Mason [MIDIfind.Com]",
	"Osbourne Ozzy - Walk On Water [MIDIfind.Com]",
	"Painkiller",
	"Pantera - 5 Minutes Alone [MIDIfind.Com]",
	"Pantera - A New Level [MIDIfind.Com]",
	"Pantera - Becoming [MIDIfind.com]",
	"Pantera - Becoming [MIDIfind.Com]",
	"Pantera - By Demons Be Driven [MIDIfind.Com]",
	"Pantera - Cemetery Gates [MIDIfind.com]",
	"Pantera - Cowboys From Hell [MIDIfind.Com]",
	"Pantera - Domination (2) [MIDIfind.Com]",
	"Pantera - Domination [MIDIfind.Com]",
	"Pantera - Fucking Hostile [MIDIfind.Com]",
	"Pantera - Good Friends And A Bottle Of Pills",
	"Pantera - Heresy [MIDIfind.Com]",
	"Pantera - I'M Broken [MIDIfind.Com]",
	"Pantera - Primal Concrete Sledge [MIDIfind.Com]",
	"Pantera - Psycho Holiday [MIDIfind.Com]",
	"Pantera - Revolution Is My Name (2) [MIDIfind.Com]",
	"Pantera - Shedding Skin [MIDIfind.Com]",
	"Pantera - Slaughtered [MIDIfind.Com]",
	"Pantera - Strenght Beyond Strenght [MIDIfind.Com]",
	"Pantera - Throes Of Rejection (Drum)",
	"Pantera - Walk (Drum)",
	"People=Shit- FlipgridJR",
	"PhantomOfTheOpera",
	"Powerslave",
	"Primer 55 - My Girl [MIDIfind.com]",
	"PrisonSong",
	"Rage Against the Machine - Bullet in the Head [MIDIfind.com]",
	"Rage Against The Machine - Bulls On Parade (2) [MIDIfind.Com]",
	"Rage Against the Machine - Down on the Street [MIDIfind.com]",
	"Rage Against The Machine - Killing In The Name (Drum)",
	"Rage Against the Machine - Killing in the Name with drum (1)",
	"Rage Against the Machine - Rage Against the Machine Know Your Enemy [MIDIfind.com]",
	"Rammstein - Du Hast [MIDIfind.Com]",
	"Rammstein - Sonne [MIDIfind.Com]",
	"Ratt - Round And Round [MIDIfind.Com]",
	"Revenga",
	"School - Nirvana School - Nirvana",
	"Scorpions - No One Like You (2) [MIDIfind.Com]",
	"Scorpions - Rock You Like A Hurricane [MIDIfind.Com]",
	"Scream",
	"Sepultura - Arise (Drum)",
	"Sepultura - Attitude (Drum)",
	"Sepultura - Ratamahatta (Drum)",
	"Sepultura - Refuse Resist (Drum)",
	"Sepultura - Roots Bloody Roots (3) [MIDIfind.Com]",
	"Sepultura - Roots Bloody Roots (Drum)",
	"Sepultura - Roots Bloody Roots (Drums Only)",
	"Sepultura - Slave New World (Drum)",
	"Sepultura - Territory (Drum)",
	"Skid Row - 18 And Life [MIDIfind.Com]",
	"Slapshock - Direction [MIDIfind.com]",
	"Slayer - Angel Of Death (2) [MIDIfind.Com]",
	"Slayer - Angel Of Death (Drum)",
	"Slayer - Raining Blood (Drum)",
	"Slayer - Raining Blood [MIDIfind.Com]",
	"Slayer - Raining Blood Altars Of Sacrifice Jesus Saves [MIDIfind.Com]",
	"Slayer - Seasons In The Abyss (Drum)",
	"Slipknot - Before I Forget.drum midi",
	"Slipknot - Dead Memories (5) [MIDIfind.com]",
	"Slipknot - Duality (Drum)",
	"Slipknot - Eyeless",
	"Slipknot - Eyeless (2) [MIDIfind.Com]",
	"Slipknot - Eyeless (5) [MIDIfind.Com]",
	"Slipknot - Eyeless (Drum)",
	"Slipknot - Joey Jordison Drum Solo From Surfacing [MIDIfind.com]",
	"Slipknot - Joey Jordison Drum Solo From Surfacing [MIDIfind.Com]",
	"Slipknot - Joey Jordison Drum Solo From Surfacing [MIDIfind.Com] (1)",
	"Slipknot - People Shit (Drum)",
	"Slipknot - Psychosocial (Drum)",
	"Slipknot - Psychosocial (ver 8 by Thaynan).mid",
	"Slipknot - Scissors [MIDIfind.com]",
	"Slipknot - Sic (Drum)",
	"Slipknot - Spit It Out (Drum)",
	"Slipknot - Surfacing (Drum)",
	"Slipknot - Surfacing [MIDIfind.Com]",
	"Slipknot - Vendetta",
	"Slipknot - Vermilion Pt.1   WWW.MIDISFREE.COM",
	"Slipknot - Wait And Bleed (13) [MIDIfind.Com]",
	"Slipknot - Wait And Bleed.mid",
	"slipknot-sic",
	"Slipknot-Snuff-Anonymous-20210724225809-nonstop2k.com",
	"So-Far-Away",
	"Something In The Way - Nirvana",
	"Spit Out The Bone - Metallica",
	"Staind - Can't Believe [MIDIfind.com]",
	"Staind - Ephiphany [MIDIfind.com]",
	"Staind - Staind Fade [MIDIfind.com]",
	"Static-X - I'M With Stupid [MIDIfind.Com]",
	"Static-X - Push It (2) [MIDIfind.Com]",
	"Stay Away - Nirvana",
	"Styx - Heavy Metal Poisoning [MIDIfind.com]",
	"Sugar",
	"Suicide Silence - You Only Llive Once [MIDIfind.Com]",
	"System Of A Down - 36 (Drum)",
	"System Of A Down - Aerials [MIDIfind.Com]",
	"System Of A Down - ATWA (Drum)",
	"System Of A Down - B.Y.O.B. [MIDIfind.Com]",
	"System Of A Down - BYOB (Drum)",
	"System Of A Down - Chic 'N' Stu (Drum)",
	"System Of A Down - Chop Suey! (Drum)",
	"System Of A Down - Chop Suey! [MIDIfind.Com]",
	"System Of A Down - Fuck The System (Drum)",
	"System Of A Down - I-E-A-I-A-I-O (Drum)",
	"System Of A Down - Jet Pilot (Drum)",
	"System Of A Down - Know (Drum)",
	"System Of A Down - Prison Song (5) [MIDIfind.Com]",
	"System Of A Down - Prison Song (9) [MIDIfind.Com]",
	"System Of A Down - Spiders (Drum)",
	"System Of A Down - Sugar [MIDIfind.Com]",
	"System Of A Down - Suite Pee [MIDIfind.Com]",
	"System Of A Down - Toxicity (Drum)",
	"System Of A Down - Vicinity Of Obscenity (Drum)",
	"System Of A Down - War (4) [MIDIfind.Com]",
	"Territorial Pissings - Nirvana",
	"The Heretic Anthem - Slipknot",
	"The Man Who Sold The World - Nirvana",
	"The Stage - Avenged Sevenfold by Rgman",
	"The-Great-Southern-Trendkill",
	"The-Great-Southern-Trendkill.Drm 2026-09-06 06-40-25.Mid",
	"Three Days Grace - Animal I Have Become [MIDIfind.Com]",
	"Three Days Grace - Home [MIDIfind.Com]",
	"Three Days Grace - I Hate Everything About You (4) [MIDIfind.Com]",
	"Three Days Grace - I Hate Everything About You [MIDIfind.Com]",
	"Three Days Grace - Just Like You (2) [MIDIfind.Com]",
	"Three Days Grace - Just Like You [MIDIfind.Com]",
	"Three Days Grace - Never Too Late (3) [MIDIfind.Com]",
	"Three Days Grace - Pain (2) [MIDIfind.Com]",
	"Three Days Grace - Riot [MIDIfind.Com]",
	"Three Days Grace - Time For Dying [MIDIfind.Com]",
	"ThunderStruck - ACDC",
	"Tool - Lateralus (4) [MIDIfind.Com]",
	"Tool - Parabol Parabola [MIDIfind.Com]",
	"Tourettes - Nirvana Tourettes - Nirvana Drum Sheet Music",
	"Toxicity by System of a Down -- Version 4.2",
	"Type O Negative - Black No 1 (2) [MIDIfind.Com]",
	"Type O Negative - Christian Woman [MIDIfind.Com]",
	"Type O Negative - I Don'T Wanna Be Me [MIDIfind.Com]",
	"Type O Negative - My Girlfriend'S Girlfriend (2) [MIDIfind.Com]",
	"Type O Negative - Out Of The Fire [MIDIfind.Com]",
	"Under The Runes - Bathory",
	"Unholy Confessions",
	"Vai Steve - For The Love Of God [MIDIfind.Com]",
	"Valkyrie - Heavy Metal Brigade [MIDIfind.com]",
	"Vega - Heavy Metal Religija [MIDIfind.com]",
	"WASP - I Wanna Be Somebody (2) [MIDIfind.Com]",
	"Мастер - 2000 лет (Иуда) [MIDIfind.Com]",
	"Мастер - Берегись [MIDIfind.Com]",
	"Мастер - Мастер [MIDIfind.Com]",
	"Пикник - Королевство кривых [MIDIfind.Com]",
}