-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"21 Guns - Green Day (Green Day) 21 Guns",
	"505",
	"Alice In Chains - Damm That River [MIDIfind.Com]",
	"Alice In Chains - It Ain'T Like It [MIDIfind.Com]",
	"Alice In Chains - Nutshell [MIDIfind.Com]",
	"Alice In Chains - Rotten Apple (2)",
	"Alice In Chains - Would(3) [MIDIfind.Com]",
	"AllTheSmallThings",
	"American Football - Never Meant (Remastered 2024) [OFFICIAL AUDIO] drums mixed",
	"American Football - Never Meant [MIDIfind.com]",
	"AmericanIdiot",
	"Arctic Monkeys - Crying Lightning [MIDIfind.Com]",
	"Arctic Monkeys - Do I Wanna Know [MIDIfind.com]",
	"Arctic Monkeys - R U Mine [MIDIfind.com]",
	"Audioslave - Like A Stone [MIDIfind.Com]",
	"Avenged Sevenfold - Seize The Day [MIDIfind.Com]",
	"Beatles (The) - And I Love Her [MIDIfind.Com]",
	"Beatles (The) - I Am The Walrus [MIDIfind.Com]",
	"Beatles (The) - I Want You [MIDIfind.Com]",
	"Beatles (The) - If I Fell [MIDIfind.Com]",
	"Beatles (The) - Strawberry Fields Forever [MIDIfind.Com]",
	"Beatles (The) - Tomorrow Never Knows [MIDIfind.Com]",
	"Beatles (The) - While My Guitar Gently Weeps (2) [MIDIfind.Com]",
	"Beatles All My Loving",
	"Beatles Besame Mucho",
	"Beatles It Wont Be Long",
	"Big Cheese - Nirvana",
	"Blink-182 - Always 7",
	"Blink-182 - Drum Solo",
	"Blur - Song 2 [MIDIfind.Com]",
	"BoysDontCry",
	"BreakStuff",
	"Canned Heat - Going Up The Country",
	"Come as you are (3 beats)",
	"Come-Together-1",
	"Counterfeit",
	"Creep",
	"D7- Nirvana (Drums)",
	"Degenerate",
	"Eagles (The) - Hotel California (3) [MIDIfind.Com]",
	"Endless Nameless - Nirvana (Drums)",
	"Faith",
	"Foo Fighters - Everlong",
	"Fortunate Son - Creedance Clearwater Revival-Drum Kit, Drums",
	"Franz Ferdinand - Take Me Out [MIDIfind.Com]",
	"Girlfriend",
	"Green Day - American Eulogy [MIDIfind.Com]",
	"Green Day - Basket Case [MIDIfind.Com]",
	"Green Day - Boulevard Of Broken Dreams [MIDIfind.Com]",
	"Green Day - Brain Stew [MIDIfind.Com]",
	"Green Day - Burnout [MIDIfind.Com]",
	"Green Day - Extraordinary Girl [MIDIfind.Com]",
	"Green Day - Give Me Novacaine [MIDIfind.Com]",
	"Green Day - Holiday (2) [MIDIfind.Com]",
	"Green Day - Jesus Of Suburbia (2) [MIDIfind.Com]",
	"Green Day - Letterbomb [MIDIfind.Com]",
	"Green Day - Longview [MIDIfind.Com]",
	"Green Day - No One Knows [MIDIfind.Com]",
	"Green Day - She'S A Rebel [MIDIfind.Com]",
	"Green Day - Stray Heart [MIDIfind.Com]",
	"Green Day - Welcome To Paradise [MIDIfind.Com]",
	"Green Day - Whatsername [MIDIfind.Com]",
	"Green Day - When I Come Around [MIDIfind.Com]",
	"Green Dayst Jimmy",
	"Hkmori - Anybody Can Find Love",
	"Hkmori - Anybody Can Find Love (Except You.) [UNFINISHED] (Breakcore Drill 'N' Bass)",
	"Hot For Teacher",
	"imagine-dragons-believer-drum-score",
	"Korn - Embrace",
	"Leech",
	"Linkin Park - Given Up [MIDIfind.Com]",
	"Linkin Park - No More Sorrow",
	"Linkin Park - Numb",
	"Love Buzz - Nirvana (Drums)",
	"Mac Demarco - Freaking Out The Neighborhood [MIDIfind.Com]",
	"My Chemical Romance - I'M Not Okay I Promise [MIDIfind.Com]",
	"My Chemical Romance - Thank You For The Venom [MIDIfind.Com]",
	"My Chemical Romance - You Know What They Do To Guys Like Us In Prison (2) [MIDIfind.Com]",
	"Nirvana - All Apologies (2) [MIDIfind.Com]",
	"Nirvana - Aneurysm [MIDIfind.Com]",
	"Nirvana - Been A Son (2) [MIDIfind.Com]",
	"Nirvana - Blew (2) [MIDIfind.Com]",
	"Nirvana - Breed (2) [MIDIfind.Com]",
	"Nirvana - Come As You Are",
	"Nirvana - Dive (Drums)",
	"Nirvana - Drain You [MIDIfind.Com]",
	"Nirvana - Dumb [MIDIfind.Com]",
	"Nirvana - Floyd The Barber (Drums)",
	"Nirvana - Heart Shaped Box [MIDIfind.Com]",
	"Nirvana - In Bloom [MIDIfind.Com]",
	"Nirvana - Lithium (3) [MIDIfind.Com]",
	"Nirvana - Lounge Act [MIDIfind.Com]",
	"Nirvana - Mr. Moustache",
	"Nirvana - Nirvana Lithium Live MTV Vma 1992 [MIDIfind.Com]",
	"Nirvana - Old Age [MIDIfind.Com]",
	"Nirvana - Rape Me [MIDIfind.Com]",
	"Nirvana - Scentless Apprentice (3) [MIDIfind.Com]",
	"Nirvana - School",
	"Nirvana - Seasons In The Sun [MIDIfind.Com]",
	"Nirvana - Serve The Servants (5) [MIDIfind.Com]",
	"Nirvana - Sliver (2) [MIDIfind.Com]",
	"Nirvana - Sliver (5) [MIDIfind.Com]",
	"Nirvana - Smells Like Teen Spirit",
	"Nirvana - Territorial Pissings",
	"Nirvana - Verse Chorus Verse (2) [MIDIfind.Com]",
	"NIRVANA.Smells Like Teen Spirit K",
	"No Name 2",
	"Oasis - Cigarettes Alcohol [MIDIfind.Com]",
	"Oasis - Shakermaker",
	"Oasis - She'S Electric [MIDIfind.Com]",
	"Oasis - Supersonic [MIDIfind.Com]",
	"Oasis-Dont Look Back In Anger",
	"OASIS.Stand By Me",
	"Offspring (The) - Pretty Fly For A White Guy [MIDIfind.Com]",
	"Offspring (The) - The Kids Aren'T Alright [MIDIfind.Com]",
	"Pearl Jam - Black (2) [MIDIfind.Com]",
	"Pink Floyd - Comfortably Numb [MIDIfind.Com]",
	"Radiohead - 15 Step [MIDIfind.Com]",
	"Radiohead - 2+2=5 [MIDIfind.Com]",
	"Radiohead - Everything In Its Right Place [MIDIfind.Com]",
	"Radiohead - Fake Plastic Trees [MIDIfind.Com]",
	"Radiohead - Kid A [MIDIfind.Com]",
	"Radiohead - Lucky [MIDIfind.Com]",
	"Radiohead - No Surprises [MIDIfind.Com]",
	"Radiohead - Paranoid Android [MIDIfind.Com]",
	"Radiohead - Subterranean Homesick Alien [MIDIfind.Com]",
	"Radiohead - The Bends (2) [MIDIfind.Com]",
	"Rollin",
	"Santana Carlos - Smooth [MIDIfind.Com]",
	"Sex Pistols - Anarchy In The UK (2) [MIDIfind.Com]",
	"Skillet - Monster [MIDIfind.Com]",
	"Smells Like Teen Spirit - Drums",
	"Stone Temple Pilots - Plush [MIDIfind.Com]",
	"SurfinUSA",
	"The Avengers Theme Song (CHECK MY NEW VERSION)",
	"The Beatles - A Hard Day'S Night",
	"THE BEATLES.All My Loving",
	"THE BEATLES.Helter Skelter",
	"THE BEATLES.Something K",
	"Tom-Sawyer-3",
	"Undone (The Sweater Song) - Weezer",
	"Undone (The Sweater Song) - Weezer (Sleezy)",
	"Van Halen - Ain'T Talkin Bout Love (2) [MIDIfind.Com]",
	"Weezer - Undone the Sweater Song [MIDIfind.com]",
	"Where Is My Mind - Pixies Where Is My Mind",
}