-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	" NieR Automata -- Emil (Despair) ",
	"[Black MIDI] The Classic Black Medley",
	"200 AniSong Medley HalcyonMusic",
	"AIZO HalcyonMusic",
	"Akuma no Ko (a child of evil) - Attack on Titan The Final Season Part 2 Ending",
	"audio2midi",
	"bad apple 4.6 million",
	"Beastars - JUNO is in love -adult-",
	"Cat Loving HSR",
	"Chainsaw Man - In The Pool Reze Arc OST Mhxa",
	"Chainsaw Man - IRIS OUT Reze Arc Mhxa",
	"Chainsaw Man - JANE DOE Reze Arc Mhxa",
	"Chasing Kou - Oboreru Knife (Drowning Love)",
	"Cry Baby - Tokyo Revengers OP Mhxa",
	"Dan Dan Kokoro Hikareteku (From Dragon Ball GT) Ver 2",
	"DEAD OR LIE",
	"Death Note OP1 - THE WORLD Mhxa",
	"Demon Slayer OP Mhxa",
	"Doraemon - No Uta",
	"Eldoraudio-Hajime no Ippo  Knockout ED 1  Yuuzora no Kamihikouki  - Piano Tutorial MP3 160K ",
	"Eldoraudio-Juan Arenosa - Ofelia  Official Music Video  - Juan Arenosa  128k  humanized",
	"Fukashigi no Carte",
	"FULL Inferno - Enen No Shouboutai Fire Force OP Mhxa",
	"Giornos Theme",
	"GOZALO - Ariis",
	"HalcyonMusic 10k subs medley",
	"Harry Potter- Hedwig'S Theme",
	"Hurtful and painful but I don't think it sounds very good",
	"If I am with you",
	"If I Am With You  Yoshimasa Terui  Jujutsu Kaisen S2 OST LB7",
	"If I Am With You - Jujutsu Kaisen - Yoshimasa Terui (Incomplete I Got Lazy)",
	"IRIS OUT HalcyonMusic",
	"itterasshai-attack-on-titan-ss4-ed-ai-higuchi",
	"Jojo's Bizarre Adventure Part 2   Battle Tendency OP - Bloody Stream",
	"Josuke's theme Diamond Is Unbreakable in piano(COMPLETE)",
	"Judas",
	"Kamado Nezuko no Uta HalcyonMusic",
	"Kensuke Ushio - IN THE POOL",
	"Kensuke Ushio - in the pool v2",
	"Kensuke Ushio - in the pool v3",
	"Kimi no Na wa    Sparkle  TheIshter  Full Sheets 1772654410756",
	"Mermaid Rhapsody – v3rmillionkyo",
	"Merry Go Round Of Life - Howl'S Moving Castle Mhxa",
	"Mrs GREEN APPLE - Inferno",
	"Never Meant To Belong - Bleach",
	"Never Meant To Belong (Bleach OST)",
	"New Darling",
	"Nezuko HalcyonMusic",
	"NieR - Kaine Salvation",
	"No Game No Life - THIS GAME Mhxa Peak",
	"Orange 7!! - Your Lie In April",
	"pf solo",
	"popipo - Hatsune miku - midi by tutogamer2a - WIP",
	"Rokudenashi - One Voice Mhxa",
	"Scott Joplin'S The Entertainer MIDI FULL",
	"Self Embodiment of Perfection (Mahito Theme)",
	"Shinzou wo Sasageyo HalcyonMusic",
	"shock-attack-on-titan-ed6",
	"Sincerely - Violet Evergarden OP Mhxa",
	"Sono Chi No Sadame - Jojo's Bizarre Adventure",
	"Summer Pockets",
	"Sword Art Online Medley HalcyonMusic",
	"Tau Cash",
	"Throughout heaven and earth, i alone am the honored one",
	"Tokyo Ghoul - Unravel",
	"utsukushiki-zankoku-na-sekai-attack-on-titanshingeki-no-kyojin-ed-1-full",
	"Vickeblanka - Black Catcher Black Clover Opening 10 WT1",
	"Yoshimasa Terui - IF I AM WITH YOU",
	"You Say Run - My Hero Academia OST",
	"Your Reality",
}