-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"- Miss Kobayashis Dragon Maid Op Arr. Phyxinon",
	"[Black MIDI] The Classic Black Medley",
	"[COMPLETE] Bloody Stream (JoJo'S Bizarre Adventure)",
	"[FULL] Dystopia - The Iceblade Sorcerer Shall Rule The World OP - Piano Arrangement",
	"1JoJo Vento Aureo OP 2 Traitor'S Requiem (Uragirimono No Requiem)",
	"1Jotaro'S Theme From Jojo'S Bizarre Adventures Stardust Crusaders",
	"1Red Swan - Attack On Titan Season 3 Opening",
	"200 AniSong Medley HalcyonMusic",
	"Ai ĐưA Em Về Take Me Back Home",
	"Ai No Uta",
	"AIZO HalcyonMusic",
	"Akuma no Ko (a child of evil) - Attack on Titan The Final Season Part 2 Ending",
	"AOT - Ashes On The Fire Main Theme Mhxa",
	"AOT - Call Of Silence Ymir'S Theme Mhxa",
	"Aozora No Rhapsody From Miss Kobayashi'S Maid Dragon (Short Version)",
	"audio2midi",
	"Bad Apple",
	"bad apple 4.6 million",
	"Beastars - JUNO is in love -adult-",
	"BEASTARS -Classical- For 2 Violins",
	"BEFORE LIGHTS OUT",
	"Binary Data IV",
	"Bleach - Ranbu No Melody",
	"Bloody Stream Piano Arrangement",
	"Cat Loving HSR",
	"Chainsaw Man - In The Pool Reze Arc OST Mhxa",
	"Chainsaw Man - IRIS OUT Reze Arc Mhxa",
	"Chainsaw Man - JANE DOE Reze Arc Mhxa",
	"Chaos-Construct",
	"Chasing Kou - Oboreru Knife (Drowning Love)",
	"Cry Baby - Tokyo Revengers OP Mhxa",
	"Dan Dan Kokoro Hikareteku (From Dragon Ball GT) Ver 2",
	"DEAD OR LIE",
	"Death Note OP1 - THE WORLD Mhxa",
	"Death Note OST - L'S Theme Mhxa",
	"Demon Slayer OP - Gurenge Mhxa",
	"Demon Slayer OP Mhxa",
	"Doraemon - No Uta",
	"Dragon Ball Kai - Dragon Soul",
	"Eldoraudio-Ai No Uta",
	"Eldoraudio-Hajime no Ippo  Knockout ED 1  Yuuzora no Kamihikouki  - Piano Tutorial MP3 160K ",
	"Eldoraudio-Juan Arenosa - Ofelia  Official Music Video  - Juan Arenosa  128k  humanized",
	"Fhana - Ai No Supreme",
	"FháNa - 涙のパレード 映画小林さんちのメイドラゴン さみしがりやの竜オープニング主題歌",
	"Fukashigi no Carte",
	"FULL Inferno - Enen No Shouboutai Fire Force OP Mhxa",
	"Full Theme By JoJo Steel Ball Run",
	"FullMetal Alchemist - Again Brotherhood OP1 Mhxa",
	"Giornos Theme",
	"Gooby This Gooby Tha5",
	"GOZALO - Ariis",
	"HalcyonMusic 10k subs medley",
	"Harry Potter- Hedwig'S Theme",
	"Howls Merry Go Round Of Life By Trouble",
	"Hurtful and painful but I don't think it sounds very good",
	"If I am with you",
	"If I Am With You  Yoshimasa Terui  Jujutsu Kaisen S2 OST LB7",
	"If I Am With You - Jujutsu Kaisen - Yoshimasa Terui (Incomplete I Got Lazy)",
	"Into The World - Issei",
	"IRIS OUT HalcyonMusic",
	"It'S Mygo!!!",
	"itterasshai-attack-on-titan-ss4-ed-ai-higuchi",
	"JBA - Giorno'S Theme Mhxa",
	"Jojo's Bizarre Adventure Part 2   Battle Tendency OP - Bloody Stream",
	"Josuke's theme Diamond Is Unbreakable in piano(COMPLETE)",
	"Jotaro'S Theme By JJBA",
	"Judas",
	"Kaibutsu 怪物 (MONSTER) - YOASOBI (BEASTARS OP2)",
	"Kamado Nezuko no Uta HalcyonMusic",
	"Kensuke Ushio - IN THE POOL",
	"Kensuke Ushio - in the pool v2",
	"Kensuke Ushio - in the pool v3",
	"Kimi no Na wa    Sparkle  TheIshter  Full Sheets 1772654410756",
	"Kimi No Na Wa - Sparkle (Piano).Mid (1)",
	"Kiminonawa OST - Nandemonaiya Mhxa",
	"KISS OF DEATH（Produced By HYDE）(延音)",
	"Kobayashi San Chi No Maid Dragon ED - Ishukan Communication (TV Size) - ShinkoNetCavy",
	"Light'S Theme - Death Note",
	"Maid In Dragon",
	"Mermaid Rhapsody – v3rmillionkyo",
	"Merry Go Round Of Life - Howl'S Moving Castle Mhxa",
	"Mrs GREEN APPLE - Inferno",
	"Never Meant To Belong - Bleach",
	"Never Meant To Belong (Bleach OST)",
	"New Darling",
	"Nezuko HalcyonMusic",
	"NieR - Kaine Salvation",
	"No Game No Life - THIS GAME Mhxa Peak",
	"Omae Wa Mou Mhxa",
	"Orange 7!! - Your Lie In April",
	"Path Of The Wind - Totoro OST Mhxa",
	"pf solo",
	"popipo - Hatsune miku - midi by tutogamer2a - WIP",
	"Promise Neverland - Isabella'S Lullaby Mhxa",
	"Radiohead - No Surprises",
	"Rascal Does Not Dream Of Bunny Girl Senpai Mhxa",
	"RE ZERO - STAY ALIVE Mhxa",
	"Reinai Circulation Mhxa",
	"Ripped Pants By Spongebob Squarepants And The Losers",
	"Rokudenashi - One Voice Mhxa",
	"Sayonara Cross Teck-07-04-2026",
	"Scott Joplin'S The Entertainer MIDI FULL",
	"Self Embodiment of Perfection (Mahito Theme)",
	"SHIGATSU WA KIMI NO US ENDING -ORANGE MHXA",
	"Shinzou wo Sasageyo HalcyonMusic",
	"Shinzou-Wo-Sasageyo",
	"shock-attack-on-titan-ed6",
	"Sincerely - Violet Evergarden OP Mhxa",
	"Sono Chi No Sadame - Jojo's Bizarre Adventure",
	"Spirited Away - Inochi No Namae - The Name Of Life.Mid",
	"Steel Ball Run",
	"Summer Pockets",
	"Sword Art Online Medley HalcyonMusic",
	"Tau Cash",
	"The Amazing Digital Circus Theme (Carameii Ver.) Piano Sheet Piano Tutorial - 피아노섬 PIANOSUMM (192k)",
	"Three Years Of Youth Overflowing %E2%80%93 Yoshimasa Terui",
	"Throughout heaven and earth, i alone am the honored one",
	"Toilet Story 3",
	"Tokyo Ghoul - Unravel",
	"Unravel - Tokyo Ghoul (Piano Cover) - MIDI.Mid",
	"utsukushiki-zankoku-na-sekai-attack-on-titanshingeki-no-kyojin-ed-1-full",
	"Vickeblanka - Black Catcher Black Clover Opening 10 WT1",
	"Wild Side - ALI (Beastars OP 1)",
	"Yoshimasa Terui - IF I AM WITH YOU",
	"You Say Run - My Hero Academia OST",
	"YOUR NAME - SPARKLE Mhxa",
	"Your Reality",
	"센과 치히로의 행방불명 OST Always With Me By (Pianicast) Mhxa",
	"테일즈위버 OST - Reminiscence - Yeon H (192k)",
}