-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"ABBA - The Winner Takes it All",
	"About You By The 1780242398856",
	"Adele - Skyfall",
	"Advance Wars 2 Black Hole Rising - Colins Theme WWW.MIDISFREE.COM",
	"Afgan-Bukan Cinta Biasa",
	"Angel-Nidji",
	"Arabesque-in-E-Nr-1",
	"Baby - Justin Bieber",
	"Beethoven - Moonlight Sonata (1st Movement) ",
	"Beethoven Virus (insane)",
	"Beethoven Virus (insane).mid (1)",
	"Bruno Mars - Risk It All",
	"Chopin – Nocturne Op.9 No.2",
	"chopin ballade 4 (c)lubetsky",
	"Counting stars",
	"Dạo Bước HongKong 1999",
	"Drowning Love Tuxedo.Fx",
	"Flamewall",
	"Frank Sinatra - My Way",
	"Fur Elise",
	"Fur Elise (1)",
	"GAYNOR.I Will Survive K",
	"Gloria Gaynor Arr.  Elaine Kelkel - I Will Survive",
	"GOZALO - Ariis",
	"Handel,Halvorsen Passacaglia",
	"in the pool  C",
	"Indonesia Raya.MID",
	"Je Te Laisserai Des Mots (1)",
	"JOPLIN.The entertainer",
	"Kembali Pulang Suara Kayu Ft Feby Putri BY SurrealFlux 1780242827893",
	"liebestraum",
	"Merry-Go-Round of Life  Animenz",
	"Michael Jackson Billie Jeann",
	"MIDI File - Bruno Mars - Risk It All (Easy)",
	"MONTAGEM REBOLA",
	"Moonlight sonata 3rd x fantaisie impromptu",
	"moonlight-sonata-i",
	"MỘT ĐỜI (14 Casper & Bon Nghiêm)",
	"operas",
	"Pirates of the Caribbean - He's a Pirate (1)",
	"Rasa-Ini-Vierra",
	"Risk it all",
	"Rush E but its as difficult as humanly possible",
	"ssstik.io 1777299650774",
	"Summer",
	"Tarot Feast 1780242551896",
	"Tonight",
	"Vierra-Rasa-Ini-Anonymous-20200323154206-Nonstop2k.Com",
	"Wedding-Day-at-Troldhaugen",
	"بروحي فتاة.",
	"กลัวว่าฉันจะไม่เสียใจ (Fear) – PURPEECH",
}