-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"[Black MIDI] RUSH E",
	"💞...🪽부활(Boowhal) - Never Ending Story (Piano Cover) [가사LYRICS KOR] - Pianist Cho Younghoon／HOON TO-BE (192k)",
	"007amanha Nuncamais2",
	"93772 Imposter-Syndrome-",
	"ABBA - The Winner Takes it All",
	"About You By The 1780242398856",
	"Adele - Skyfall",
	"Advance Wars 2 Black Hole Rising - Colins Theme WWW.MIDISFREE.COM",
	"Afgan-Bukan Cinta Biasa",
	"Angel-Nidji",
	"Arabesque-in-E-Nr-1",
	"AUD AP2420H",
	"Baby - Justin Bieber",
	"Babydoll",
	"Barber-Of-Seville-(Ouverture)",
	"Beethoven - Moonlight Sonata (1st Movement) ",
	"Beethoven Virus (insane)",
	"Beethoven Virus (insane).mid (1)",
	"Beethoven-Moonlight-Sonata",
	"Binks Rum Binks Sake 1780241727588",
	"Bogemian",
	"Bruno Mars - Risk It All",
	"Chopin – Nocturne Op.9 No.2",
	"chopin ballade 4 (c)lubetsky",
	"Chopin Winter Wind Etude",
	"Christina Perri - A Thousand Years (Piano Cover)",
	"Counting stars",
	"Dạo Bước HongKong 1999",
	"Death Waltz.Mid",
	"Debra Lady Gaga - Shallow",
	"Drowning Love Tuxedo.Fx",
	"Flamewall",
	"Frank Sinatra - My Way",
	"Freedom Dive",
	"Friqtao Huye",
	"Full - Comptine D'Un Autre Ete; L'Apres Midi",
	"Fur Elise",
	"Fur Elise (1)",
	"Fur Elise Nightmare",
	"Galaxy Collapse (With Correct BPM)",
	"GAYNOR.I Will Survive K",
	"Girls-Und-Panzer-Ost---Piano-On-Musescore",
	"Gloria Gaynor Arr.  Elaine Kelkel - I Will Survive",
	"GOZALO - Ariis",
	"Handel, Halvorsen - Passacaglia.Mid",
	"Handel,Halvorsen Passacaglia",
	"Human-Nature (1)",
	"I Thought I Saw Your Face Today - She & Him (Piano Tutorial)",
	"in the pool  C",
	"Indonesia Raya.MID",
	"Its Raining Tacos",
	"Its Raining Tacos.Mid",
	"Je Te Laisserai Des Mots (1)",
	"JOPLIN.The entertainer",
	"Kembali Pulang Suara Kayu Ft Feby Putri BY SurrealFlux 1780242827893",
	"liebestraum",
	"Media Preview Over The Horizon 2021",
	"Merry-Go-Round of Life  Animenz",
	"Michael Jackson Billie Jeann",
	"MIDI File - Bruno Mars - Risk It All (Easy)",
	"MONTAGEM REBOLA",
	"Moonlight sonata 3rd x fantaisie impromptu",
	"moonlight-sonata-i",
	"Moonlight-Sonata-Nightmare-Lionel-Yu-Moonlightsonatanightmaremid",
	"MORGENSHTERN Ft. элджей - Cadillac",
	"MỘT ĐỜI (14 Casper & Bon Nghiêm)",
	"My Heart Will Go On - TITANIC - Sheet Music - 4K60p - Piano Cover - CANACANA",
	"operas",
	"Otsukare Summer",
	"Pedih Last Child 1780246257149",
	"Pirates of the Caribbean - He's a Pirate (1)",
	"Pirates Of The Caribbean - He'S A Pirate (Piano Version)",
	"Posso Até NãO Te Da Flores - MC Ryan SP, MC Jacaré E MC Meno K Piano",
	"Raca Negra - Cheia De Manias.Mid",
	"Rachmaninoff - Piano Concerto No 2 (Op 18) - 2nd Mvmt - Piano Solo",
	"Rasa-Ini-Vierra",
	"Risk it all",
	"Rockefeller Street By Nightcore (Piano)",
	"Rossini Barber Of Seville, Overture Transcribed For Piano",
	"Rossini Gioacchino Rossini - Barber Of Sevilla Ouverture [MIDIfind.Com]",
	"Running Up That Hill.Mid",
	"Rush D",
	"Rush E but its as difficult as humanly possible",
	"SAMSUNG Over The Horizon 2021 (1)",
	"Seluruh Nafas Ini Last Child 1780246231273",
	"She Neva Knows - Justatee She Neva Knows",
	"Sonate No 14, “Moonlight” 3rd Movement",
	"Sonate-No-14-Moonlight-3rd-Movement",
	"ssstik.io 1777299650774",
	"Stranger Things - Main Theme",
	"Summer",
	"Tarot Feast 1780242551896",
	"Tetris Block Arts V4",
	"The Amazing Digital Circus - Main Theme But Its By HANS ZIMMER EPIC VERSION (Your New Home) - Carameii (192k)",
	"Tonight",
	"Vierra-Rasa-Ini-Anonymous-20200323154206-Nonstop2k.Com",
	"Virginio Aiello, On Piano - Van Gogh",
	"Wedding-Day-at-Troldhaugen",
	"Woke Up In Japan By Friqtao",
	"Yung Kai - Blue Piano Cover Sheet Music (1)",
	"بروحي فتاة.",
	"กลัวว่าฉันจะไม่เสียใจ (Fear) – PURPEECH",
	"거리에서Sung-Si-Kyung---On-The-Street-Piano-Ver",
	"바라만-본다--피아노-커버악보포함--Pianocover",
	"카트라이더 대저택 Bgm 피아노 청음연주 + 중급자용 악보 (Mansion Dance Battle Piano Cover) [문호준 인트로] - 지훈피아노 JH Piano (192k)",
	"테일즈위버-Talesweaver-Ost--Second-Run-Piano-Cover-피아노-커버",
}