-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"(Play!) The Neighbourhood-Sweater Weather",
	"505 best part",
	"81416 Take-Me-Back-Home",
	"After The Love Has Gone  David Foster Earth Wind  Fire 1775672109595",
	"Anybody can find love (except you.) - Full Song",
	"Avenged Sevenfold - M I A [MIDIfind.com]",
	"Avenged Sevenfold - M.i.a.   WWW.MIDISFREE.COM",
	"Avenged Sevenfold — Warmness on the Soul [MIDIfind.com]",
	"Baby Hotline",
	"babydoll - dominic fike",
	"Back To Friends - Sombr",
	"Buttercup - Jack Stauber",
	"Childish Gambino - Redbone",
	"Coldplay - Sparks",
	"Còn gì đẹp hơn impossible",
	"Credits Song For My Death",
	"Cry for me impossible",
	"D4vd Romantic Homicide piano midi",
	"Die-With-A-Smile",
	"Do I Wanna Know Bass",
	"Do I Wanna Know by Arctic Monkeys",
	"Eldoraudio-AhaTik suara asli - Aditya 85d49cc5-bfd8-4ffb-98ba-899efdcd37c7",
	"Elton John - I'm still standing",
	"Erika",
	"Freaks – Surf Curse Freaks",
	"happy",
	"Happy",
	"Hope - XXXTENTACION",
	"I Deserve To Bleed - Suchi Soucy",
	"Imagine - John Lennon, John Lennon And The Plastic Ono Band (Piano Solo)",
	"Indila - Love Story",
	"Interstellar main theme (With Effects!)",
	"Jack Stauber - Baby Hotline (5)",
	"Jane",
	"Jowel: fantasmas",
	"Jowel: Goodbye World",
	"Jowel: Im Still Standing",
	"Jowel: Let Me Down",
	"Jowel: nunca es suficiente",
	"Jowel: Perdón",
	"Jowel: Por qué te vas",
	"Jowel: Your Love",
	"Justin-Bieber-Ghost-Anonymous-20220216213352-nonstop2k.com",
	"Kalapastangan - Fitterkarma",
	"Katy Perry - The One That Got Away",
	"Kevin MacLeod - Blue Feather ",
	"KISS — I Was Made For Loving You",
	"Laufey - Promise",
	"Laufey - Too little, too late",
	"like him - tyler creator",
	"Like Him Tyler The Creator",
	"Lost Sky - Dreams Pt. II",
	"Love Story  Taylor Swift 1775672226231",
	"Ludovico Einaudi - Experience",
	"Marcha Nupcial",
	"Moonlight - XXXTentacion",
	"Morning Mood",
	"Một vòng Việt Nam but impossible",
	"Mrs Magic - Strawberry Guy",
	"Mrs Magic - Strawberry Guy (Intro)",
	"Mrs Magic - Strawberry Guy (Piano Version)",
	"Multo - Cup of Joe RNE",
	"Như có Bác trong ngày Đại thắng impossible",
	"Nightchanges by dc ; @jvkowi",
	"Øneheart & reidenshi snowfall piano midi",
	"Pokemon BlackWhite - An Unwavering Heart",
	"PULSE  Tony Ann aka my neighbours car alarm 1770203303452",
	"RickRoll",
	"Risk It All  Bruno Mars 1776838404638",
	"River Flows In You",
	"Self Aware - Temper City (Piano)",
	"Sinking Town   沈める街 - Yoeko Kurahashi",
	"Sunsezt yt @moongate 1234",
	"Tai sinh",
	"Tally Hall- Hidden in the Sand ",
	"Thằng điên impossible",
	"Thằng điên normal",
	"The FatRat - Unity",
	"The Living Tombstone - It'S Been So Long (FNaF 2 Song)",
	"The Stranglers - Golden Brown 2",
	"Tom Odell - Another Love",
	"Tony Ann - ICARUS",
	"Tony Ann - Reminisce 2",
	"Too Little Too Late  laufey 1776838113996",
	"Việt Nam I love impossible",
	"Washing Machine Heart - Mitski",
	"Wave to earth - Love",
	"Where's My Love – SYML",
	"Wiz Khalifa - See You Again ft Charlie Puth Lyrics",
	"Young-Girl-A maybe more difficult",
	"Your Love",
}