-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	" Until-Then-OST--Memories",
	"'MEDIC!' (Piano Arrangement Of Team Fortress 2 Soundtrack)",
	"'Right Behind You' (Piano Arrangement Of Team Fortress 2 Soundtrack)",
	"'Rocket Jump Waltz' (Piano Arrangement Of Team Fortress 2 Soundtrack)",
	"'Team Fortress 2 (Main Theme)' (Piano Arrangement Of Team Fortress 2 Soundtrack)",
	"'Upgrade Station' (Piano Arrangement Of Team Fortress 2 Soundtrack)",
	"(REUPLOAD) Kevin MacLeod - Olde Timey",
	"[Black MIDI] Bad Apple!! 1 Million Notes v3 (fixed piano)",
	"[Black MIDI] The Classic Black Medley",
	"[JvP] Electroman Adventures - Geometry Dash",
	"[ULTRAKILL OST] Requiem.Mid",
	"[UndertaleOST-100]Megalovania - Toby Fox",
	"1Bakamitai",
	"1Granny - Theme Song (Horror Mobile Game)",
	"1Granny Ambience - Lambjelly4",
	"738567 Dj-N-Theory-Of-Everything- Converted By Jukeblocks",
	"After School Jamboree",
	"Animation Warrior Theme - Nighthawk22",
	"Animation Warrior Theme - NightHawk22 MIDI Piano Arrangement 1AG",
	"Anybody Can Find Love (Except You ) - Hkmori Breakcore",
	"ASGORE - Toby Fox",
	"ASGORE Kyle Landry EDT",
	"At The Speed Of Light",
	"Attack Of The Killer Queen - (Deltarune) - [MIDI]",
	"Back on Track",
	"Bad Apple!!",
	"Bad Piggies - Main Theme",
	"Basic Pitch Transcription (1)",
	"Basics in behavior",
	"Battle Against a True Hero (Undyne the Undying) (wip)",
	"Battlefield Theme - Misc Computer Games (Piano Solo)",
	"Bee - Groovydominoes52",
	"Bendy And The Ink Machine - Build Our Machine",
	"Blue Skies - Silent Partner (Guitar remix)",
	"C418 - Blind Spots (From Minecraft Volume Beta) - Piano Tutorial",
	"C418 - Mice on Venus",
	"C418 - Subwoofer Lullaby",
	"Caffeine Rush - Boksed",
	"Calamity Mod OST DM DOKURO - UNIVERSAL COLLAPSE Piano Solo",
	"Call Of Duty Black Ops Zombies",
	"Cascade2",
	"Casey Edwards - Devil Trigger",
	"Castle Vein - Ultrakill (1)",
	"Cornfield Chase",
	"Creo - Flow",
	"Daisy Bell (1892)",
	"Deadlocked (Geometry Dash)",
	"Death By Glamour Piano",
	"Deltarune - Field Of Hopes And Dreams - Urimegaconnor (1)",
	"DELTARUNE - It’s TV Time!",
	"Deltarune - THE WORLD REVOLVING",
	"Deltarune Chapter 5 - Flower Man",
	"Descend [PianoSolo]",
	"Dialtone - MIDI",
	"DJ Nate Theory Of Everything 3.Mid",
	"DJVI - Base After Base (Geometry Dash)",
	"Doki Doki Literature Club - Main Theme - ShinkoNetCavy",
	"Dry out Geometry Dash",
	"Eldoraudio-Hyperfun-by-Kevin-Macleod",
	"Eldoraudio-Jingle-Punks-Good-Starts",
	"Eldoraudio-The Green Orbs - After School Jamboree  Happy   1 ",
	"Eldoraudio-The-Builder chosic.com ",
	"Eldoraudio-Wallpaper chosic.com ",
	"Event Horizon (1)",
	"Fallen Down - Toby Fox",
	"Fallen down (Reprise)",
	"Field of Memories - Waterflame",
	"Finale - Toby Fox",
	"finale-undertale",
	"Five nights at Freddy's Song",
	"Flower Man - DELTARUNE Chapter 5 - Toby Fox",
	"FNAF",
	"Gaster's Theme - Toby Fox",
	"Genshin Impact Character Demo - Furina All The World'S A Stage",
	"Geometry Dash - Thinking Space II Nuke Powder",
	"Geometry Dash - Time Machine",
	"Geometry Dash Menu Theme",
	"Geometry Dash Stereo Madness Original By Forever Bound",
	"Get Outside! (WIP)",
	"Glory - Ultrakill",
	"God Eater From Vs Shaggy Mod V2",
	"Got-Main-Theme-Advanced",
	"Great Fairy Fountain Theme",
	"Great Fairy Fountain Theme (Legend Of Zelda)",
	"Hammer Of Justice - Deltarune Chapter 3+4 - Toby Fox",
	"Hatsune Miku - Senbonzakura",
	"Hatsune Miku - Tell Your World",
	"Heroes Main",
	"Home - Were Finally Landing 65702210",
	"Hyperfun.mp3",
	"Idina-Menzel-Let-It-Go-Piano-Version-AwesomeFunguy-20170701215652-Nonstop2k.Com",
	"Impact & Orbit1 - Stay",
	"In Absentia ΛΟΓΟΣ - ULTRAKILL Layer 8-1 Theme (Boxx Cover) (Wip)",
	"input 1777578189898 1",
	"Jumper (Geometry Dash)",
	"K Anime Project - Shiro 2",
	"Kevin Macleod -  Cipher  (1)",
	"Kevin Macleod - Amazing Plan (Duet).mid (1)",
	"Kevin MacLeod - Call to Adventure (1)",
	"Kevin Macleod - Carefree",
	"Kevin MacLeod - Merry Go (1)",
	"Kevin MacLeod - Quirky Dog",
	"Kevin MacLeod - The Show Must Be Go",
	"Kevin MacLeod - Wallpaper",
	"Kevin MacLeod - Who Likes To Party",
	"Kevin MacLeod Heartbreaking Recreation (1)",
	"KEY AFTER KEY LMS",
	"Korobeiniki Tetris Theme (Piano Tiles Version)",
	"Lana Del Rey Young And Beautiful Piano Midi",
	"Last Sahur 😭 - Polyplayer Full Version (Undertale Last Goodbye By Toby Fox X Brainrot)",
	"Legend Of Zelda - Saria's Song",
	"Legendary Belmont - Castlevania Curse Of Darkness",
	"Lena Raine - Pigstep",
	"Letitgo",
	"Limbo",
	"May This Moment Last Forever Midi",
	"MEGALOVANIA - Toby Fox",
	"MeGaLoVania Piano",
	"Metal Crusher",
	"Metro Exodus - Race Against Fate (Fingerstyle) [MIDIfind.Com]",
	"Mice on Venus (Minecraft)",
	"MiConv.com  Bunny Hop - Quincas Moreira",
	"MiConv.Com OUTBREAK - Nicopatty (Nico Nextbots OST)",
	"Mili - Compass",
	"Mili - Fly, My Wings",
	"Mili - Gone Angels",
	"Mili - Hero",
	"Mili - Through Patches of Violet",
	"Minecraft OST Aria Math (Advanced)",
	"Monster Hunter Freedom 2 - Pokke Village (2)",
	"my light (我的光) - yung kai",
	"My Light (我的光) - Yung Kai",
	"New Super Mario Bros Overworld Theme",
	"NieR - Song of the Ancients Devola",
	"Old Slap Battles 75 Killstreak Theme (Final Boss)",
	"Oppa Toby Style - Homestuck S Collide OST 2 For Piano RWE",
	"Oppa Toby Style Homestuck S Collide OST For Piano 1776388611729",
	"ORDER.Mid",
	"Output",
	"P-2 WAIT OF THE WORLD - Tenebre Rosso Sangue - ULTRAKILL - Urimegaconnor",
	"Peaches - Jack Black (from the Super Mario Bros. Movie)",
	"Penumbra Phantasm LWP",
	"PHOENIX LMS",
	"Pixelland by Kevin Macleod",
	"PLEAD - Last Man Standing (C00lkidd Vs 007n7) Forsaken OST - Key After Key",
	"Plead MIDI",
	"Pokke Village - Monster Hunter 2nd",
	"Promise R",
	"Rage of the Champions!",
	"Red Battle - Pokémon Gold Silver",
	"Revenge- Minecraft",
	"Rex Duodecim Angelus Homestuck 1776449720878",
	"Rigor Mormist (Fog) - Plants VS Zombies",
	"Rush stereo madness",
	"Samplab Screen Recording 202 (1)",
	"sans. - Toby Fox",
	"Saviour Of The Waking World Piano",
	"Schoolhouse Trouble Playable",
	"Scizzle Aquatic Ambience Piano Tutorial Solo Arrangement",
	"Shiawase Vip",
	"Silent Partner - Dog Park   Dog and Pony Show (from YouTube Audio Library)",
	"Silent Partner - Sugar Zone (A1D3N93 Remix)",
	"Sneaky Snitch - Kevin MacLeod",
	"Snowy - Toby Fox",
	"Sonic the Hedgehog - Mystic Cave Zone",
	"Spider Dance - Undertale",
	"Spongebob Squarepants Theme (MIDI)",
	"Stationsquare-Ts",
	"Stereo madness",
	"Stereo Madness - ForeverBound",
	"Stronger Than You - Undertale",
	"Subwoofer Lullaby (Minecraft)",
	"Summer Smile - Silent Partner No Copyright Music-303964052",
	"Sundowner (Piano Duet)",
	"Super Mario Bros - Main Theme",
	"Super Mario World Castle Theme Kyle Landry",
	"Super Smash Bros Brawl- Menu Theme",
	"Sweden (Minecraft)",
	"Swift Strike",
	"tera-io-flamewall-camellia",
	"Tetris BassBurst Solid",
	"Tetris Theme, BLACK MIDI 50K NOTES",
	"The Death Of Gods Will (MIDI)",
	"The Entertainer - Scott Joplin ",
	"The Green Orbs - At the Fair (Piano Cover)",
	"The Green Orbs - Claudio The Worm (Duet)",
	"The Green Orbs - Old MacDonald Instrumental (Happy)",
	"The Legend Of Zelda Ocarina Of Time - Great Fairy Fountain (1)",
	"The Legend Of Zelda Ocarina Of Time - Lost Woods",
	"The NOexistenceN Of You AND Me - Just You",
	"The Nuker 4 Audio Remake (Original Composition From TN1.5)",
	"The Nuker 4 Part 1",
	"Thick Of It [The one from IG reels]",
	"Title Theme (The Legend Of Zelda Ocarina Of Time)",
	"Touhou - BAD APPLE NORMAL Mhxa",
	"Town Talk",
	"Triage At Dawn",
	"TripleTrouble",
	"ULTRAKILL - Mirror Rim Intro",
	"ULTRAKILL - The World Looks Red [WIP]",
	"Undertale - Asgore",
	"Undertale - Ruins",
	"Undertale - Ruins [Piano]",
	"Undertale - SAVE the World",
	"Undertale - Toby Fox",
	"Undertale To The Bone",
	"Undertale~PFFinale~123,000",
	"Universal Collapse - Dm Dokuro",
	"Universal Collapse - DM DOKURO Wooper Universal Collapse",
	"Uwa!! So Temperate♫ (UNDERTALE)",
	"Valve HALF LIFE 2 OST (Www.Lightaudio.Ru)",
	"War Without Reason MIDI (1)",
	"Waterdrop (1)",
	"Waterdrop-The Nonexistence Of You And Me OST",
	"Wet Hands (Minecraft)",
	"Withered - Literally Every Fnf Mod Ever (Vs Bob Week) Piano Solo",
	"Your Reality",
	"Zelda - Ocarina Of Time - Great Fairy Fountain",
}