-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"2Pac - Changes",
	"66203 Sa-Susunod-Na-Habang-Buhay",
	"87646 Terbuang-Dalam-Waktu",
	"Ai Đưa Em Về (Take Me Back Home) – TIA  feat. Lê Thiện Hiếu (Low Cortisol Song)",
	"Alan Walker - Alone Part II",
	"ALL MY FELLAS 8FR",
	"Arctic Monkeys Arr. Lucky Piano - No. 1 Party Anthem (1)",
	"Ariana Grande, Justin Bieber - Stuck With U",
	"As The World Caves In - Matt Maltese",
	"Attack On Titan Season 3 - Red Swan.Mid",
	"Bad Habit - Steve Lacy",
	"banh mi Khong",
	"basic pitch transcription",
	"Beanie",
	"Beatles Let It Be",
	"Beggin' – Måneskin Drum Sheet Music",
	"Blood Theme (From Dexter) - Daniel J Licht (Piano Solo)",
	"blue - yung kai",
	"Burning Blue - Mariah The Scientist (Piano Solo)",
	"Camellia - Flamewall",
	"Chaos-Construct",
	"Charlie Puth - We Don'T Talk Anymore (Feat. Selena Gomez)",
	"Chiquitita - ABBA (Only The Ending)",
	"Christina Perri - A Thousand Years",
	"Clair-De-Lune-Debussy",
	"coffin nails   rapp snitch knishes",
	"Congratulations - Mac Miller (Final Project)",
	"Convenience - Jaydes",
	"Counting Stars by OneRepublic - Drums",
	"Country Roads",
	"Credits Song For My Death (Code: 900)",
	"Dandelions - Ruth B. 2",
	"Dandelions.com",
	"DạO BướC HongKong 1999",
	"Dark Red",
	"Daylight - David Kushner",
	"Die with a smile - Piano Solo LKZ",
	"Dimension Creo",
	"Dracula - Tame Impala",
	"Elektronomia - Sky High",
	"Elton John - I'm Still Standing (Expert)",
	"End Of Beginning - Djo",
	"Engravings-Ethan-Bortnick",
	"Ere - Juan Karlos",
	"EXECRETION Midi Recreation Instrumental",
	"Faint - Linkin Park Faint",
	"GIMS - NINAO Official Lyrics Vido",
	"God Is - Kanye West WIP",
	"Golden Brown Arragement By natsu",
	"Grenade By Bruno Mars",
	"Guns N Roses - Sweet Child O' Mine (1)",
	"Habang Buhay",
	"Her - JVKE",
	"Hey There Delilah",
	"How The World Works - Bo Burnham",
	"I Need A New Beginnig - Ruiji",
	"I THOUGHT YOU WANTED TO DANCE",
	"I Want You Back - Jackson 5",
	"Impostor Syndrome - Sydney Gish",
	"In Love - Low G (Piano)",
	"In the end drum",
	"iris-goo-goo-dolls",
	"Je-Te-Laisserai-Des-Mots-Patrick-Watson",
	"John Legend - All Of Me - Pianoitall.Mid",
	"John Rod Dondoyano - Wave To Earth - Seasons [Yougensaki Remake]",
	"Joji - Die For You",
	"Joji - SLOW DANCING IN THE DARK",
	"Joji Die For You Piano Midi.Mid",
	"Joji Glimpse Of Us Piano Cover Midi 2.Mid",
	"Juice WRLD - Robbery",
	"Just Give Me One More Day Alej",
	"Just The Two Of Us - Grover Washington Jr. Feat. Bill Withers (Piano Solo)",
	"Kahit Maputi Na Ang Buhok Ko",
	"Kathang Isip Tut",
	"KhôNg BuôNg - Hngle (Piano)",
	"L'Amour Toujours - Gigi D'Agostino (Organ Cover)",
	"Laufey - From The Start",
	"Long Time - Playboi Carti",
	"Love Story X Golden Brown",
	"Love Story X Golden Brown (1)",
	"lover girl - laufey",
	"Made Sum Plans (Osamason)",
	"Michael Jackson - Bad",
	"Michael Jackson - Don’T Stop Till You Get Enough",
	"Michael Jackson - Smooth Criminal",
	"Michael Jackson (They Don'T Care About Us) Complete",
	"Mike Posner - I Took A Pill In Ibiza (SeeB Remix)",
	"Mitski - My Love Mine All Mine",
	"Mood - 24kGolden, Iann Dior",
	"Mr Sandman.Mid",
	"mrs magic",
	"NắNg Có Mang Em Về - Shartnuss, Tr. D, Phankeo (Piano)",
	"Night Changes Piano Arr 1775503451731",
	"No batidão impossible",
	"Nơi này có anh impossible",
	"NOSTYLIST Destroy Lonely Converted To Piano By DK Marshmello",
	"Not Like Us",
	"Off The Map - SoFaygo Off The Map SoFaygo Piano Conversion By DK Marshmello",
	"Palagi-Tj-Monterde-Palagi",
	"Pasilyo - Sun Kissed Lola (Piano Cover)",
	"Phonecert (폰서트) - 10CM",
	"Quando Bate Aquela Saudade - Rubel Piano",
	"rapp snitch knishes",
	"Rapp Snitch Knishes - MF DOOM",
	"Ricky Montgomery - Line Without A Hook [FULL]",
	"Robert-Miles-Children-20240118103815-Nonstop2k.Com",
	"Rush E – lyre only",
	"Someone Like You (Easy Piano)",
	"Star Shopping Midi.Mid",
	"Strawberry Guy - Mrs Magic (Strings Version)",
	"Sufjan Stevens - Mystery Of Love",
	"Talking To The Moon (Bruno Mars).Mid",
	"Tally Hall- Hidden In The Sand",
	"Tek It - Cafune",
	"THE ITCHYWORMS - Di Na Muli ( Extended Solo ) NNTranscription",
	"The+New+Periodic+Table+Song",
	"TheFatRat+-+Windfall",
	"Tony Ann - Anxiety",
	"Took Her To the O - King Vonn",
	"Took Her To The O- King Von",
	"Torete - Moonstar88",
	"Uhaw(Tayong Lahat) - Dilaw",
	"Vamp Anthem - Playboi Carti (Piano Sheets)",
	"Vicetone - Nevada ZNG",
	"Violent Crimes - Kanye West Violent Crimes - Kanye West",
	"We Not Like You (Tiktok Version)",
	"WEEZER.Buddy Holly K",
	"What Happened To Virgil - Lil Durk Ft. Gunna",
	"Where'D All The Time Go - Dr. Dog",
	"World's smallest violin",
	"Yebba'S Heartbreak Piano Solo",
	"بروحي فتاة.",
	"那些年",
}