-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"(緒なら) (MS) - If I Am With You",
	"1 V2 Main Serong By The Changcuters",
	"1'Darkest Child' In C Minor - Kevin MacLeod",
	"1Across The Sea By Weezer",
	"1Aruarian Dance - Nujabes V2",
	"1Baggy Trousers - Madness Madness Baggy Trousers",
	"1Brasilian Skies - Masayoshi Takanaka",
	"1Caravan (From 'Whiplash')",
	"1Creep - Radiohead",
	"1Estrelar - Marcos Valle",
	"1Heart-Shaped Box",
	"1Hey Jude Acoustic By The Beatles",
	"1Join Me In Death By HIM",
	"1Juicebox By The Strokes",
	"1Kagefumi (Accurate) By Hyakkei",
	"1Karma Police - Radiohead, Thomas Yorke (Piano Solo)",
	"1Laputa By Panchiko",
	"1Lithium - Nirvana",
	"1Ma Cherie Guitar By Malice Mizer",
	"1Main Serong By The Changcuters",
	"1Nirvana - Smells Like Teen Spirit",
	"1Oh Que Será - Willie Colon",
	"1Reunion By Korea Girl",
	"1Robert Miles - Children",
	"1Succession Main Theme",
	"1The Man Who Sold The World",
	"2Pac - Changes",
	"2Pac - Time Back - Piano Tutorial",
	"66203 Sa-Susunod-Na-Habang-Buhay",
	"87646 Terbuang-Dalam-Waktu",
	"Ai Đưa Em Về (Take Me Back Home) – TIA  feat. Lê Thiện Hiếu (Low Cortisol Song)",
	"Alan Walker - Alone Part II",
	"Alan Walker - Better Off Alone (Alone, Pt. III)",
	"Alan Walker - On My Way (BúM ).Mid",
	"Alan Walker - Sing Me To Sleep",
	"Alan Walker - The Drum",
	"Alan-Walker-The-Spectre-Anonymous-20200425083142-Nonstop2k.Com",
	"ALL MY FELLAS 8FR",
	"Ao No Sumika (JJK T2 OP)",
	"Arctic Monkeys Arr. Lucky Piano - No. 1 Party Anthem (1)",
	"Ariana Grande, Justin Bieber - Stuck With U",
	"Arranged By Dara S. - Should I Add More Instruments To This",
	"As The World Caves In - Matt Maltese",
	"Attack On Titan Season 3 - Red Swan.Mid",
	"Aura Monster Subaru (Jjs Version)",
	"Bad Habit - Steve Lacy",
	"BAILE INoLVIDABLE - Bad Bunny",
	"banh mi Khong",
	"basic pitch transcription",
	"Beanie",
	"Beatles Let It Be",
	"Beethoven Virus But It'S Insane (MS)",
	"Beggin' – Måneskin Drum Sheet Music",
	"Blood Theme (From Dexter) - Daniel J Licht (Piano Solo)",
	"blue - yung kai",
	"Brain-Stew",
	"BTS - House Of Cards",
	"Burning Blue - Mariah The Scientist (Piano Solo)",
	"Camellia - Flamewall",
	"Careless-Whisper",
	"Champagne Coast - Blood Orange",
	"Champagne Coast - Piano Cover (TikTok Version)",
	"Chaos-Construct",
	"Charlie Puth - We Don'T Talk Anymore (Feat. Selena Gomez)",
	"Chikni Chameli - 8K4k Music Video Katrina Kaif Hrithik Agneepath Shreya Ghoshal Ajay-Atul Trimmed By Jukeblocks Converted By Jukeblocks",
	"Chiquitita - ABBA (Only The Ending)",
	"Christina Perri - A Thousand Years",
	"Cinderella (Instrumental)",
	"Clair-De-Lune-Debussy",
	"coffin nails   rapp snitch knishes",
	"Congratulations - Mac Miller (Final Project)",
	"Convenience - Jaydes",
	"Counting Stars by OneRepublic - Drums",
	"Country Roads",
	"Credits Song For My Death (Code: 900)",
	"Creep - Radiohead Dramatic Piano Solo",
	"Dandelions - Ruth B. 2",
	"Dandelions.com",
	"DạO BướC HongKong 1999",
	"Dark Red",
	"Daylight - David Kushner",
	"Demons",
	"Die with a smile - Piano Solo LKZ",
	"Diedlonely & éNouement - Stellar Piano Midi",
	"Dimension Creo",
	"Djo - End Of Beginning - Piano Tutorial With Sheet Music",
	"Dr Dre - Still Dre",
	"Dracula - Tame Impala",
	"Elektronomia - Sky High",
	"Elton John - I'm Still Standing (Expert)",
	"End Of Beginning - Djo",
	"Engravings-Ethan-Bortnick",
	"Ere - Juan Karlos",
	"Every Living Breathing Moment - Grant Steller (Piano)",
	"EXECRETION Midi Recreation Instrumental",
	"Faint - Linkin Park Faint",
	"Forever - The Little Dippers",
	"Forsaken - Through Patches Of Violet (Hacklord LMS)",
	"From The Start - Laufey",
	"From The Start (Laufey) (MS)",
	"FULL PIANO STILL DRE",
	"GIMS - NINAO Official Lyrics Vido",
	"Girlfriends - New Computers",
	"God Is - Kanye West WIP",
	"Golden Brown Arragement By natsu",
	"Gotye - Somebody That I Used To Know (Ft. Kimbra)",
	"Grenade By Bruno Mars",
	"Guns N Roses - Sweet Child O' Mine (1)",
	"Guzzx - Xingpei",
	"Habang Buhay",
	"Her - JVKE",
	"Here Comes The Boy (Piano Fragment) (MS)",
	"Hey There Delilah",
	"Hillsong United - Oceans",
	"Hillsong Worship - Broken Vessel (Amazing Grace)",
	"How The World Works - Bo Burnham",
	"I Need A New Beginnig - Ruiji",
	"I THOUGHT YOU WANTED TO DANCE",
	"I Want You Back - Jackson 5",
	"I Wonder - Kanye West",
	"Im Not The Only One",
	"Impostor Syndrome - Sydney Gish",
	"Impostor Syndrome (Sidney Gish)",
	"In Love - Low G (Piano)",
	"In the end drum",
	"iris-goo-goo-dolls",
	"Ivy - Frank Ocean",
	"JAMIROQUAY.Virtual Insanity",
	"Je-Te-Laisserai-Des-Mots-Patrick-Watson",
	"John Legend - All Of Me - Pianoitall.Mid",
	"John Rod Dondoyano - Wave To Earth - Seasons [Yougensaki Remake]",
	"Joji - Die For You",
	"Joji - SLOW DANCING IN THE DARK",
	"Joji Die For You Piano Midi.Mid",
	"Joji Glimpse Of Us Piano Cover Midi 2.Mid",
	"Juice WRLD - Robbery",
	"Just Give Me One More Day Alej",
	"Just Give Me One More Day Alej (1)",
	"Just The Two Of Us - Grover Washington Jr. Feat. Bill Withers (Piano Solo)",
	"JVKE - Golden Hour",
	"Kahit Maputi Na Ang Buhok Ko",
	"Kara Sevda - Anlatamam Piano Tutorial (Dizi MüZiğI, Toygar IşıKlı)",
	"Kathang Isip Tut",
	"Kendrick Lamar - Meet The Grahams",
	"KhôNg BuôNg - Hngle (Piano)",
	"Kinji - Windburn Live",
	"Kota Ini Tak Sama Tanpamu - Nadhif Basalamah Tutorial Piano Pemula",
	"L'Amour Toujours - Gigi D'Agostino (Organ Cover)",
	"La La Land Epilogue Mid",
	"La Maritza Piano Tutorial",
	"Laufey - From The Start",
	"Let You Break My Heart Again - Laufey Philharmonia Orchestra Official Audio",
	"Levels",
	"Like Him - Tyler, The Creator (FULL BEST VERSION DONE)",
	"Long Time - Playboi Carti",
	"Look At What You'Ve Done - Drake",
	"Love Is In The Air, Pt. 1",
	"Love Story X Golden Brown",
	"Love Story X Golden Brown (1)",
	"LOVELI LORI - Love For You",
	"lover girl - laufey",
	"Lover Girl (Laufey - But Classical) (MS)",
	"Made Sum Plans (Osamason)",
	"Mala Vida Mala Fama",
	"Marc Indigo - Boy For The Weekend",
	"Massive - Drake",
	"Mesmerizer (Midi)",
	"Michael Jackson - Bad",
	"Michael Jackson - Don’T Stop Till You Get Enough",
	"Michael Jackson - Smooth Criminal",
	"Michael Jackson - Thriller",
	"Michael Jackson (They Don'T Care About Us) Complete",
	"Mike Posner - I Took A Pill In Ibiza (SeeB Remix)",
	"Mitski - My Love Mine All Mine",
	"Mood - 24kGolden, Iann Dior",
	"Moonlight Sonata M3 (MS)",
	"Mr Sandman.Mid",
	"mrs magic",
	"Mundo By IV Of Spades",
	"NắNg Có Mang Em Về - Shartnuss, Tr. D, Phankeo (Piano)",
	"Nice Boys (TEMPOREX) (MS)",
	"Night Changes Piano Arr 1775503451731",
	"NIGHT DANCER - Imase",
	"Nights - Frank Ocean",
	"No batidão impossible",
	"Nơi này có anh impossible",
	"NOSTYLIST Destroy Lonely Converted To Piano By DK Marshmello",
	"Not Like Us",
	"Off The Map - SoFaygo Off The Map SoFaygo Piano Conversion By DK Marshmello",
	"Olivia Rodrigo - Drivers License",
	"Olivia Rodrigo - Vampire",
	"Output",
	"Pachelbel Canon In D (Fast Easy Piano Version)",
	"Palagi-Tj-Monterde-Palagi",
	"Pasilyo - Sun Kissed Lola (Piano Cover)",
	"Pasilyo - Sunkissed Lola (Piano)",
	"Phonecert (폰서트) - 10CM",
	"Poster Boy - 2hollis",
	"PUN - DAY ONE Piano Tutorial",
	"Quando Bate Aquela Saudade - Rubel Piano",
	"rapp snitch knishes",
	"Rapp Snitch Knishes - MF DOOM",
	"Ricky Montgomery - Line Without A Hook [FULL]",
	"Risk It All - Bruno Mars",
	"Robert-Miles-Children-20240118103815-Nonstop2k.Com",
	"Roommates - Malcolm Todd",
	"Rush E – lyre only",
	"Rush E Mobile",
	"Sempurna By Andra And The Backbone",
	"Shooting Stars - Piano Solo Arrangement",
	"Should I Add More Instruments To This (MS - Prolly Fixed)",
	"SHUCKS ENDING CUTCENE PIANO COVER",
	"Someone Like You (Easy Piano)",
	"Star Shopping Midi.Mid",
	"Stephanie - Nafeeisboujee",
	"Stephen Sanchez - Until I Found You",
	"Strawberry Guy - Mrs Magic (Strings Version)",
	"Subaru'S Ringtone (From Re Zero Kara Hajimeru Isekai Seikatsu A Dog Of Flanders)",
	"Sufjan Stevens - Mystery Of Love",
	"Talking To The Moon (Bruno Mars).Mid",
	"Tally Hall- Hidden In The Sand",
	"Tame Impala - Loser",
	"TaU THE SONG",
	"Tek It - Cafune",
	"The Greatest Showman - Rewrite The Stars Piano Cover With Strings (With PIANO SHEETS)",
	"THE ITCHYWORMS - Di Na Muli ( Extended Solo ) NNTranscription",
	"The One That Got Away X Clean - Katy Perry Taylor Swift",
	"The+New+Periodic+Table+Song",
	"TheFatRat+-+Windfall",
	"This Is What Falling In Love Feels Like - JVKE For Piano-1",
	"Titibo-Tibo For Piano Solo",
	"Tony Ann - Anxiety",
	"Took Her To the O - King Vonn",
	"Took Her To The O- King Von",
	"Torete - Moonstar88",
	"Tyler, The Creator - DOGTOOTH",
	"Tyler, The Creator - EARFQUAKE",
	"Tyler, The Creator - IGOR'S THEME",
	"Uhaw(Tayong Lahat) - Dilaw",
	"UNDERTALE OST 051 - Another Medium (FULL ORCHESTRA)",
	"Vamp Anthem - Playboi Carti (Piano Sheets)",
	"Vicetone - Nevada ZNG",
	"Violent Crimes - Kanye West Violent Crimes - Kanye West",
	"Virtual Insanity 180 BPM PIANO ONLY",
	"Voidside Swordfight (AZALI) (MS)",
	"We Not Like You (Tiktok Version)",
	"WEEZER.Buddy Holly K",
	"WHAT A BEAUTIFUL NAME (HILLSONG)",
	"What Happened To Virgil - Lil Durk Ft. Gunna",
	"Where'D All The Time Go - Dr. Dog",
	"World's smallest violin",
	"Yebba'S Heartbreak Piano Solo",
	"ZAYN - Dusk Till Dawn Ft Sia",
	"بروحي فتاة.",
	"แม่ฮ้างมหาเสน่ห์ - ลูกแพร ไหมไทย อุไรพร (Incomplete)",
	"แสงสุดท้าย-1",
	"那些年",
}