-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"Ai Đưa Em Về (Take Me Back Home) – TIA  feat. Lê Thiện Hiếu (Low Cortisol Song)",
	"Alan Walker - Alone Part II",
	"Bad Habit - Steve Lacy",
	"banh mi Khong",
	"basic pitch transcription",
	"Beanie",
	"Beggin' – Måneskin Drum Sheet Music",
	"blue - yung kai",
	"Camellia - Flamewall",
	"Chaos-Construct",
	"coffin nails   rapp snitch knishes",
	"Congratulations - Mac Miller (Final Project)",
	"Counting Stars by OneRepublic - Drums",
	"Country Roads",
	"Credits Song For My Death (Code: 900)",
	"Dandelions - Ruth B. 2",
	"Dandelions.com",
	"Daylight - David Kushner",
	"Die with a smile - Piano Solo LKZ",
	"Dimension Creo",
	"Elektronomia - Sky High",
	"Elton John - I'm Still Standing (Expert)",
	"Engravings-Ethan-Bortnick",
	"GIMS - NINAO Official Lyrics Vido",
	"Golden Brown Arragement By natsu",
	"Guns N Roses - Sweet Child O' Mine (1)",
	"Her - JVKE",
	"How The World Works - Bo Burnham",
	"I THOUGHT YOU WANTED TO DANCE",
	"In the end drum",
	"iris-goo-goo-dolls",
	"Je-Te-Laisserai-Des-Mots-Patrick-Watson",
	"Laufey - From The Start",
	"lover girl - laufey",
	"Mike Posner - I Took A Pill In Ibiza (SeeB Remix)",
	"Mitski - My Love Mine All Mine",
	"mrs magic",
	"Night Changes Piano Arr 1775503451731",
	"No batidão impossible",
	"Nơi này có anh impossible",
	"rapp snitch knishes",
	"Rapp Snitch Knishes - MF DOOM",
	"Rush E – lyre only",
	"Someone Like You (Easy Piano)",
	"Strawberry Guy - Mrs Magic (Strings Version)",
	"Tek It - Cafune",
	"The+New+Periodic+Table+Song",
	"TheFatRat+-+Windfall",
	"Tony Ann - Anxiety",
	"Took Her To the O - King Vonn",
	"Took Her To The O- King Von",
	"Vicetone - Nevada ZNG",
	"World's smallest violin",
	"بروحي فتاة.",
}