-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Everyone, Attack!(Minion Quest Boss Theme) From Mario And Luigi Superstar Saga + Bowser'S Minions",
	"1Mission Impossible Theme - Lalo Schifrin (Piano Solo)",
	"Aaj Ki Raat (Stree 2) Midi",
	"Aashiqui - The Love Theme",
	"Accomplished",
	"Alan Walker - Alone",
	"Alan Walker Faded",
	"Anlatamam - Kara Sevda [Demon]",
	"APT",
	"Bad Style",
	"Basic Pitch Transcription",
	"Billie Eilish - WILDFLOWER (In The Key Of A Major).30-Sec-Sample.MIDISTAX.COM",
	"Black Gryph0n - Upside Down (A Hazbin Hotel Song)",
	"Blinding Lights",
	"Bohemian Rhapsody - Queen",
	"Bohemian Rhapsody - Queen (Piano Solo)",
	"Carol Of The Bells With Style",
	"Carter Burwell - Bella'S Lullaby [MIDIfind.Com] 2",
	"Charlie Clouser - Saw Final Theme WWW.MIDISFREE.COM",
	"Cigarettes After Sex - Apocalypse (Ending) V2",
	"Còn gì đẹp hơn impossible",
	"Cornfield Chase",
	"Dạo Bước HongKong 1999",
	"Davy Jones Theme (Pirates Of The Caribbean)",
	"Ed Sheeran - Shape Of You",
	"Every Breath You Take - The Police (1)",
	"Game Of Thrones Main Theme",
	"Get Proto",
	"Golden Brown - The Stranglers - Piano (1)",
	"Got-Main-Theme-Advanced",
	"Government Funding (Kane Pixels)",
	"Gravity Falls",
	"Gravity Falls - Main Theme",
	"Gulabi Aankhen",
	"Hans-Zimmer-At-World-S-End-Pirates-Of-The-Caribbean-PhaniaX-20170811002106-Nonstop2k.Com",
	"hans-zimmer-cornfield-chase-interstellar-soundtrack-21091-nonstop2k.com",
	"Havana",
	"Hazbin Hotel - Losin' Streak",
	"HUNTRIX - GOLDEN From KPop Demon Hunters",
	"I am still standing",
	"INSIDE OUP 2",
	"Interstellar-Suite - Hans Zimmer",
	"Janam Janam",
	"Jaws Theme",
	"Je Te Laisserai Des Mots - Patrick Watson",
	"Je Te Laisserai Des Mots (Ft Golden Brown) Piano Tutorial",
	"JOHN.I'm still standing K",
	"K6XIWC7S03.Mp3",
	"Kara-Sevda-MüZikleri---Anlatamam---Piano-Tutorial--Medium----4K-720p-60F.Mp3",
	"Kaun Tujhe",
	"Light Lights Up Light",
	"Like A Dog Chasing Car",
	"Lily",
	"Looping In The Rooms",
	"Looping In The Rooms - Rusino",
	"Love Story",
	"Love Story X Golden Brown",
	"Mia--Sebastians-Theme",
	"Michael Jackson’S This Is It",
	"MidiLeaks.RiverFlowsInYou",
	"Multo - Cup Of Joe RNE",
	"My heartPIANO",
	"Next To You",
	"Not Alone - 1.34",
	"Not-Tomorrow-1-V3-0-",
	"OCSUAP2BM8.Mp3",
	"Oppenheimer-Can-You-Hear-The-Music-Music-By-Ludwig-Goransson-Arrangement-By-Akmigone",
	"Pirates of the Caribbean - He's a Pirate (3)",
	"Ravyn Lenae - Love Me Not",
	"Requiem For A Dream - Main Theme - EASY",
	"Shakira, Burna Boy - DAI DAI",
	"Squid Game musique",
	"Squid Game slow",
	"succession-piano-version-7",
	"Super Mario World Ending Theme As Played By Tom Brier OB9",
	"TếT Nhà Bà Hoan",
	"The Amazing Digital Circus - Running The Show",
	"The Entertainer - Scott Joplin",
	"The One Who’S Running The Show - TADC THE AMAZING DIGITAL CIRCUS",
	"The Ring Theme",
	"The Simpsons Main Theme  Danny Elfman MLX",
	"Tiersen Yann - La Valse D Amelie (Piano Version) [MIDIfind.Com]",
	"Titibo-Tibo For Piano Solo",
	"Tony Ann - Now We Are Free - Gladiator Theme",
	"Tum Hi Ho (Aashiqui 2)",
	"Two Birds - Regina Spektor",
	"Yann Tiersen - La NoyéE",
	"You'Ve Got A Friend In Me - Toy Story",
	"Ариэль - В Краю Магнолий (Акустика) [MIDIfind.Com]",
}