-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"15861 202012111801234f98921685a88c3cec0fc8a5a8dea5e97215",
	"1Everyone, Attack!(Minion Quest Boss Theme) From Mario And Luigi Superstar Saga + Bowser'S Minions",
	"1Mission Impossible Theme - Lalo Schifrin (Piano Solo)",
	"Aaj Ki Raat (Stree 2) Midi",
	"Aashiqui - The Love Theme",
	"Accomplished",
	"Alan Walker - Alone",
	"Alan Walker Faded",
	"Animotion Obsession",
	"Anlatamam - Kara Sevda [Demon]",
	"APT",
	"Arabian-Night",
	"Ariana Grande - 7 Rings - Solo - Klaus Lightsbane",
	"Bad Style",
	"Basic Pitch Transcription",
	"Billie Eilish - Wildflower - Solo - Skynyrd Fraefolgwyn",
	"Billie Eilish - WILDFLOWER (In The Key Of A Major).30-Sec-Sample.MIDISTAX.COM",
	"Black Gryph0n - Upside Down (A Hazbin Hotel Song)",
	"Blinding Lights",
	"Bohemian Rhapsody - Queen",
	"Bohemian Rhapsody - Queen (Piano Solo)",
	"Buckethead - Soothsayer [MIDIfind.Com]",
	"Bullet For My Valentine - Tears Don'T Fall (2) [MIDIfind.Com]",
	"Candyman Theme Song - It Was Always You Helen",
	"Carol Of The Bells With Style",
	"Carter Burwell - Bella'S Lullaby [MIDIfind.Com] 2",
	"Celine Dion - My Heart Will Go On - Solo - Ravel Falskhern",
	"Charlie Clouser - Saw Final Theme WWW.MIDISFREE.COM",
	"Cigarettes After Sex - Apocalypse (Ending) V2",
	"Còn gì đẹp hơn impossible",
	"Cornfield Chase",
	"Crayon Shin-Chan OP3「Ora Wa Ninkimono」",
	"Dạo Bước HongKong 1999",
	"Davy Jones Theme (Pirates Of The Caribbean)",
	"Demon Slayer - Nezuko Theme - Solo - Nozomi Tenma",
	"Demon Slayer - The Mugen Train - Tanjiro'S Dream - Solo - Nozomi Tenma",
	"Demon Slayer- Kamado Tanjiro No Uta - Solo - Zephyr Lathillion",
	"Doja Cat - Say So Bass [MIDIfind.Com]",
	"Ed Sheeran - Shape Of You",
	"Every Breath You Take - The Police (1)",
	"Game Of Thrones Main Theme",
	"Gehra Hua Final Midi",
	"Get Proto",
	"Golden Brown - The Stranglers - Piano (1)",
	"Golden-Brown",
	"Got-Main-Theme-Advanced",
	"Government Funding (Kane Pixels)",
	"Gravity Falls",
	"Gravity Falls - Main Theme",
	"Gulabi Aankhen",
	"Hans-Zimmer-At-World-S-End-Pirates-Of-The-Caribbean-PhaniaX-20170811002106-Nonstop2k.Com",
	"hans-zimmer-cornfield-chase-interstellar-soundtrack-21091-nonstop2k.com",
	"Happy-Birthday-To-You-4",
	"Havana",
	"Hazbin Hotel - Losin' Streak",
	"HUNTRIX - GOLDEN From KPop Demon Hunters",
	"I am still standing",
	"I Like Me Better - Lauv - Solo - Kenta Shiro",
	"INSIDE OUP 2",
	"Interestelar (Online-Audio-Converter.Com) Trimmed By Jukeblocks",
	"Interstellar-Suite - Hans Zimmer",
	"Janam Janam",
	"Jaws Theme",
	"Je Te Laisserai Des Mots - Patrick Watson",
	"Je Te Laisserai Des Mots (Ft Golden Brown) Piano Tutorial",
	"JOHN.I'm still standing K",
	"Justin Bieber - Love Yourself - Solo - Ravel Falskhern",
	"K6XIWC7S03.Mp3",
	"Kara Sevda - Anlatamam Piano Cover G9s0-TJbuPQ Converted By Jukeblocks",
	"Kara-Sevda-MüZikleri---Anlatamam---Piano-Tutorial--Medium----4K-720p-60F.Mp3",
	"Kaun Tujhe",
	"Kendrick Lamar - Luther - Solo - Ravel Falskhern",
	"Light Lights Up Light",
	"Like A Dog Chasing Car",
	"Lily",
	"Linkin Park - Numb (Tim Dawes Remix) 2",
	"Looping In The Rooms",
	"Looping In The Rooms - Rusino",
	"Love Is In The Air, Pt. 1 - Rock Burwell",
	"Love Story",
	"Love Story - Taylor Swift - Octet - Harmonia Crystal",
	"Love Story X Golden Brown",
	"Lukas Graham - 7 Years - Solo - Ravel Falskhern",
	"Marshmello Ft. Bastille - Happier - Solo - Ravel Falskhern",
	"Mia--Sebastians-Theme",
	"Michael Jackson’S This Is It",
	"MidiLeaks.RiverFlowsInYou",
	"Multo - Cup Of Joe RNE",
	"MusicNotes Sheet Music - Doja Cat - Say So - Solo - Shiro Astral 3",
	"My heartPIANO",
	"Naruto - Sadness And Sorrow - Duet - SnowTheBard",
	"Naruto - Sadness And Sorrow - Octet - SnowTheBard",
	"Next To You",
	"Not Alone - 1.34",
	"Not-Tomorrow-1-V3-0-",
	"OCSUAP2BM8.Mp3",
	"One Direction - What Makes You Beautiful - Solo - Ravel Falskhern",
	"OneRepublic - Counting Stars - Solo - Ravel Falskhern",
	"Oppenheimer-Can-You-Hear-The-Music-Music-By-Ludwig-Goransson-Arrangement-By-Akmigone",
	"Pirates of the Caribbean - He's a Pirate (3)",
	"Post Malone Ft. Ty Dolla $Ign - Psycho - Solo - Ravel Falskhern",
	"Ravyn Lenae - Love Me Not",
	"Red Hot Chili Peppers - Snow Hey Oh [MIDIfind.Com]",
	"Requiem For A Dream - Main Theme - EASY",
	"Shakira, Burna Boy - DAI DAI",
	"Shawn Mendes - Stitches - Solo - Ravel Falskhern",
	"Sia - Snowman - Octet - SnowTheBard",
	"Slay The Princess, Brandon Boone - The Princess - Quartet - Sechesin",
	"Squid Game musique",
	"Squid Game slow",
	"succession-piano-version-7",
	"Super Mario World Ending Theme As Played By Tom Brier OB9",
	"TếT Nhà Bà Hoan",
	"The Amazing Digital Circus - Running The Show",
	"The Entertainer - Scott Joplin",
	"The One Who’S Running The Show - TADC THE AMAZING DIGITAL CIRCUS",
	"The Ring Theme",
	"The Simpsons Main Theme  Danny Elfman MLX",
	"This Is It",
	"Tiersen Yann - La Valse D Amelie (Piano Version) [MIDIfind.Com]",
	"Titibo-Tibo For Piano Solo",
	"Tones And I - Dance Monkey (Midi By Carlo Prato) (Www.Cprato.Com)",
	"Tony Ann - Now We Are Free - Gladiator Theme",
	"Tum Hi Ho (Aashiqui 2)",
	"Two Birds - Regina Spektor",
	"Vai Steve - For The Love Of God (5) [MIDIfind.Com]",
	"Vanessa Carlton - A Thousand Miles - Solo - Ravel Falskhern",
	"X - Sadame (Guitar Version)",
	"Yann Tiersen - La NoyéE",
	"You'Ve Got A Friend In Me - Toy Story",
	"Zack Tabudlo - Pano - Solo - Ravel Falskhern",
	"Ариэль - В Краю Магнолий (Акустика) [MIDIfind.Com]",
	"कौन तुझे Kaun Tujhe",
}