-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	"1Everyone, Attack!(Minion Quest Boss Theme) From Mario And Luigi Superstar Saga + Bowser'S Minions",
	"1Mission Impossible Theme - Lalo Schifrin (Piano Solo)",
	"Accomplished",
	"Alan Walker - Alone",
	"Alan Walker Faded",
	"Bad Style",
	"Blinding Lights",
	"Bohemian Rhapsody - Queen",
	"Bohemian Rhapsody - Queen (Piano Solo)",
	"Charlie Clouser - Saw Final Theme WWW.MIDISFREE.COM",
	"Cigarettes After Sex - Apocalypse (Ending) V2",
	"Còn gì đẹp hơn impossible",
	"Cornfield Chase",
	"Dạo Bước HongKong 1999",
	"Every Breath You Take - The Police (1)",
	"Game Of Thrones Main Theme",
	"Got-Main-Theme-Advanced",
	"Government Funding (Kane Pixels)",
	"Gravity Falls",
	"Gravity Falls - Main Theme",
	"hans-zimmer-cornfield-chase-interstellar-soundtrack-21091-nonstop2k.com",
	"I am still standing",
	"INSIDE OUP 2",
	"Interstellar-Suite - Hans Zimmer",
	"Janam Janam",
	"Jaws Theme",
	"Je Te Laisserai Des Mots - Patrick Watson",
	"JOHN.I'm still standing K",
	"Like A Dog Chasing Car",
	"Lily",
	"Looping In The Rooms",
	"Looping In The Rooms - Rusino",
	"Mia--Sebastians-Theme",
	"Multo - Cup Of Joe RNE",
	"My heartPIANO",
	"Oppenheimer-Can-You-Hear-The-Music-Music-By-Ludwig-Goransson-Arrangement-By-Akmigone",
	"Pirates of the Caribbean - He's a Pirate (3)",
	"Shakira, Burna Boy - DAI DAI",
	"Squid Game musique",
	"Squid Game slow",
	"succession-piano-version-7",
	"Super Mario World Ending Theme As Played By Tom Brier OB9",
	"The Entertainer - Scott Joplin",
	"The One Who’S Running The Show - TADC THE AMAZING DIGITAL CIRCUS",
	"The Simpsons Main Theme  Danny Elfman MLX",
	"Tiersen Yann - La Valse D Amelie (Piano Version) [MIDIfind.Com]",
	"Tony Ann - Now We Are Free - Gladiator Theme",
	"Two Birds - Regina Spektor",
	"Yann Tiersen - La NoyéE",
}