return {
    "Accomplished",
    "Bad Style",
    "Bohemian Rhapsody - Queen",
    "Còn gì đẹp hơn impossible",
    "Dạo Bước HongKong 1999",
    "Gravity Falls",
    "hans-zimmer-cornfield-chase-interstellar-soundtrack-21091-nonstop2k.com",
    "I am still standing",
    "JOHN.I'm still standing K",
    "Mia--Sebastians-Theme",
    "My heartPIANO",
    "Pirates of the Caribbean - He's a Pirate (3)",
    "Squid Game musique",
    "Squid Game slow",
    "succession-piano-version-7",
    "The Simpsons Main Theme  Danny Elfman MLX",
    "Two Birds - Regina Spektor",
}
