-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	" Erika  A German WW2 marching song",
	"(˃⤙˂˶ )Hmph It's Not Like I Like You or anything mhxa",
	"(˶ ｰ̀ ⤙ｰ́ ˶) It'SNot Like I Like You Or Anything Mhxa",
	"(Anybody Can Find Love Except You) Need Drums Mhxa",
	"🇩🇪ERIKA Piano Mhxa",
	"1000 LIVING MILLENNIUM mhxa",
	"12 Variations of Twinkle Twinkle Little Star",
	"50 subs (100k notes) (1)",
	"6 TRILLION YEARS AND A OVERNIGHT STORY mhxa V2",
	"6 TRILLION YEARS AND AN OVERNIGHT STORY mhxa",
	"A STORY OF SIX TRILLION YEARS AND A NIGHT mhxa",
	"Ado - Gira Gira mhxa",
	"Ado - MIRROR mhxa",
	"Ado - Usseewa mhxa",
	"Advance Wars 2 Black Hole Rising - Colins Theme WWW.MIDISFREE.COM",
	"Aerials",
	"Alexander Rybak - Fairytale mhxa",
	"Anoufie - Noir Mhxa",
	"Anybody can find love except you mhxa",
	"Arima Kousei -Twinkle Twinkle Little Star Mhxa",
	"At the speed of light(Bloodbath)",
	"BadLiZ, The Great Strategy (v4) GS2",
	"Balakirev - Islamey Mhxa",
	"Beabadoobee - The Perfect Pair Mhxa",
	"Beethoven - Moonlight sonata 3rd Movement IN mhxa",
	"Beethoven - Moonlight sonata 3th movement mhxa",
	"Beethoven - Sonata 29Op.106 Hammerklavier Mhxa",
	"Beta0404",
	"BlaBartk - Piano Concerto No.2 Mhxa",
	"Boywithluke - Problematic mhxa",
	"Broken World mhxa",
	"Bruno Mars - When i was your man",
	"buông đôi tay nhau ra x nắng ấm xa dần",
	"cause i love you x gạt đi nc mắt",
	"Celestial Opus",
	"chắc ai đó sẽ về",
	"Champagne Coast but piano cover mhxa",
	"Champagne Coast Mhxa",
	"Chaos-Construct",
	"Chipi chipi Chapa Chapa",
	"Chờ đợi có đáng sợ",
	"Chopin - Minute Waltz Op.64 No.1 Mhxa",
	"Chopin - Waltz No.8 Op.64 No.3 Mhxa",
	"Chopin - Waltz Op 64 Improvisation Mhxa",
	"cocktail",
	"coffin nails   rapp snitch knishes",
	"Composition - Blue Sky (1)",
	"Confession of a rotten girl* mhxa",
	"Cordyceps Piano Cover V1",
	"Counting Stars by OneRepublic - Drums",
	"CupofJoe & Multo mhxa",
	"Dark dragon fire F-777 impossible",
	"Dark dragon fire-F777 (Avernus)",
	"Deco27 - Monitoring best friend remix mhxa",
	"Deco27 - Monitoring mhxa",
	"Deco27 - The vampire mhxa",
	"DJ Okawari - Flower Dance Mhxa",
	"drag-me-down-twenty-one-two",
	"Eldoraudio-Flower Dance - DJ Okawari Very Hard Ver. Piano Arranging By. Lune Music Sheets MP3 320K",
	"Eldoraudio-Rush E  original by Sheet Music Boss  NOTE  Impossible  ",
	"Engravings mhxa",
	"EnterSandman",
	"Erika piano",
	"Ethan Bortnick - cut my fingers off mhxa",
	"Evangelion - A Cruel Angel's Thesis Neon Genesis mhxa",
	"Every Living Breathing Moment mhxa",
	"F.Liszt - Reminiscences De Don Juan S.418 Mhxa",
	"flamewall",
	"Flower day mhxa",
	"forsaken-neon-by-dimrain47",
	"Fullmetal Alchemist - Brotherhood mhxa",
	"Golden Hour  JVKE Updated Ver 1772653873814",
	"Gooseworx - Your New Home MIDI (Your Piano Tutorials)",
	"Grant Steller - Every living Breathing Moment mhxa",
	"Gravity - Hazbin Hotel",
	"Gravity - Hazbin Hotel Season 2  Best remix",
	"Gravity (from Hazbin Hotel)",
	"Gravity (from Hazbin Hotel) maybe better",
	"Gravity Falls Theme",
	"Guns N Roses - Sweet Child O' Mine",
	"Harder rush e playable maybe",
	"hãy trao cho anh",
	"Hello- OMFG (WIP)(Copy)",
	"HELP!! Kobo kanaeru* mhxa",
	"Highscore",
	"Hwang Jin Yi - Flower Day Mhxa",
	"I love you so The Walters",
	"I'm just a chill guy mhxa",
	"id 072019",
	"If I Am With You - I alone the hornored one mhxa",
	"Indila - Love Story Mhxa",
	"Interstellar x Experience",
	"Irida Piano Cover",
	"iris-goo-goo-dolls",
	"Isolation",
	"It'S Not Like I Like You Or Anything (Easy) Mhxa",
	"Jane! - The Long Faces - Topic (128k)",
	"JANGAN TUNGGU LAMA LAMA (Reggea Version) CICI FARAMIDA DEMO",
	"Jeffy'S Infinite Irida - SHUCKS! V3 (Piano Tutorial)",
	"JVKE golden hour piano mhxa",
	"JVKE her mhxa",
	"Kaijuu Ni Naritai",
	"Kansas - Carry On My Wayward Son",
	"Kenshi Yonezu - Lemon mhxa",
	"KJUIMOG (Kim Jong Goon)",
	"Korn — A.D.I.D.A.S. (String) [MIDIfind.com]",
	"Lady Gaga - Judas mhxa",
	"Leviteto - LOL mhxa",
	"Lightning Moment",
	"Limbo isolation",
	"Liszt - Spanish Fantasy S.253 Mhxa",
	"Little Do U Know",
	"Looping The Rooms mhxa",
	"Lord kael - Sweetly",
	"Lord Kael - Sweetly Mhxa",
	"Love story mhxa",
	"Luna Abyss",
	"Mac Miller - Congratulations",
	"Melly Mike  Young Black  Rich Official Music Video(1)",
	"Mendelssohn - Etude Op.104No.1 In B - Minor Mhxa",
	"Metallica - Master Of Puppets (Pro).Mid",
	"Metallica-Enter-Sandman midi",
	"Mia And Sebastian'S Theme Mhxa",
	"Michael Jackson - Billie Jean",
	"Miki Matsubara - STAY WITH ME Mhxa",
	"Mitski - My Love Mine All Mine",
	"Moonlight Kokosei mhxa",
	"MrKitty-After-Dark-rlc-winston-20211103115423-nonstop2k.com",
	"Mundo x Your universe mhxa",
	"Naruto Shippuden - Naruto Shpippuuden Opening 9 SWR",
	"natori - sarushibai mhxa",
	"natori - serenade mhxa",
	"Natori propose mhxa",
	"Nevada - Vicetone",
	"Never-Gonna-Give-You-Up-3",
	"nguyện cầu đến 50 năm",
	"những lời hứa bỏ quên ost",
	"Night of Knights Lunatic mhxa",
	"no name (7)",
	"No Name (7)",
	"not yours",
	"Nuke powder",
	"oi josuke",
	"One Direction Night Changes ADVANCED",
	"Open+Window+vGH",
	"Osbourne Ozzy - No More Tears (3) [MIDIfind.Com]",
	"Outside",
	"Outside – Calvin Harris & Ellie Goulding - Piano Cover",
	"Pi the Song",
	"Picture Perfect Piano Cover",
	"Pixies - Where Is My Mind [MIDIfind.Com]",
	"Rammstein - Sonne.Mid",
	"Random noises harder than rush e",
	"Ravel Scarbo Mhxa",
	"Red Sun in the Sky (天上太阳红彤彤)",
	"Ricochet Love Amethyst Part Piano arr 1776788643947",
	"Rush #1",
	"RUSH © + MIDI DOWNLOAD",
	"Rush Ab Optimized not impossible still very hard",
	"RUSH ABCD",
	"Rush Among Us 2",
	"Rush ANKHA Not impossible",
	"Rush Astronomia not impossible but hard",
	"RUSH B - ReBlacked",
	"Rush B (Impossible)",
	"Rush B But Without Anything Else!!!",
	"Rush B playable",
	"Rush B playable i guess",
	"Rush Bad Apple impossible",
	"Rush Bad Apple not impossible",
	"RUSH BARBASHASSR",
	"RUSH C ULTRA IMPOSSIBLE",
	"Rush C ZOTMIDI",
	"Rush C# 3",
	"Rush D (1)",
	"Rush D (Impossible)",
	"Rush D Optimized Still Possible",
	"RUSH DIGITAL CIRCUS (Remake)",
	"rush e",
	"Rush E (1.2M Notes)",
	"Rush E 2 (Impossible) (1)",
	"Rush E 2 but it's actually playable",
	"RUSH E 2 but its HAPPY",
	"Rush e 2 playable i guess",
	"Rush E 2 test",
	"rush e 3",
	"Rush e 3 playable I guess",
	"Rush E 4",
	"Rush E 4 Black Midi By S3G",
	"Rush E boss? mhxa",
	"RUSH E but something is OFF!",
	"Rush e fanchen ver I guess",
	"Rush e hard FIXED FIXED FIXED FIXED FIXED",
	"Rush E not impossible but still very hard fixed",
	"Rush E Optimized Fixed Fixed Fixed Fixed",
	"Rush E Optimized not impossible but still hard",
	"RUSH E Optimized not impossible but still very hard",
	"Rush E Optimized Not Impossible But Still Very Hard Fixed Fixed Fixed",
	"Rush E Optimized Not Impossible But StillHard Fixed Fixed",
	"Rush E Original + Midi Download",
	"Rush E original sheet i spend my money on",
	"Rush e playable",
	"Rush E Real (2)",
	"Rush E Real 2",
	"RUSH E SMBs version pre-remaster",
	"RUSH E WITHOUT ANYTHING ELSE",
	"RUSH E ZOTMIDIs Ver WIP",
	"Rush Eb Optimized not impossible but still very hard",
	"Rush Epic Games Fortnite",
	"RUSH F",
	"Rush Gigachad (Remake)",
	"RUSH HAPPY BIRTHDAY",
	"RUSH HOME ALONE (Remake)",
	"Rush Jingle Bells",
	"RUSH K",
	"RUSH K (1)",
	"RUSH LGBT",
	"Rush lin gan guli guli impossible",
	"Rush Lin gan guli guli not impossible",
	"RUSH LRABER",
	"RUSH Lynes (fixed)",
	"RUSH MOSKAU",
	"Rush Mountain King Optimized not impossible but hard",
	"Rush Moutain King Lala version",
	"Rush of Life - Tony Ann",
	"Rush Piggies not impossible but hard.mjd",
	"Rush polish cow",
	"Rush Raining tacos impossible",
	"RUSH RICK ASTLEY (Remake)",
	"Rush Round And Round not impossible",
	"Rush Rush not impossible but hard",
	"Rush Sigma Boy not impossible but hard",
	"RUSH SM3DW",
	"Rush SM64",
	"RUSH SONICSPIANOONIRL REMASTERED",
	"RUSH STAR",
	"RUSH STAR (Remake)",
	"RUSH STEREO MADNESS (Remake)",
	"RUSH TWINKLE TWINKLE LITTLE STAR",
	"Rush USSR Optimized not impossible but hard",
	"RUSH VAJUSO",
	"Rush Victory",
	"Rush Vietnam remastered better and possible",
	"Rush Vietnam sounds bad btw midi by oganesson(Loadstringsgi)",
	"RUSH YOUTUBE - Kopie",
	"Rush Z (Impossible) V2",
	"Rush Z not impossible but still hard",
	"Rush 悪ノ召使 (重制版)",
	"RUSH+ELISE",
	"Sad Камин -EMIN Feat. JONY By OOR Piano YT",
	"Sheena Ringo - A double suicide mhxa",
	"Sheena Ringo -Crime & Punishment mhxa",
	"Shiganai Kokosei - Moonlight Mhxa",
	"Shucks V3 On Piano",
	"SHUCKS! DEMO Piano Cover V2",
	"sinkingtown",
	"SMB - Rush F (Impossible)",
	"Smoke on the Water",
	"Smoke on the Water (Drum)",
	"Somewhere only we know mhxa",
	"Stalemate",
	"System Of A Down - Aerials (18) [MIDIfind.Com]",
	"System of a Down - B.Y.O.B",
	"Tada Koe Hitotsu - (LittlebitExtreme) Mhxa",
	"Tada Koe Hitotsu (EXTREME)Mhxa",
	"Tally Hall - The Bidding",
	"Tally+Hall+-+Turn+The+Lights+Off",
	"tau the song playable",
	"tegrtstrgy",
	"tháng 4là lời nói dối của em",
	"Thang dien impossible lol",
	"The Corpse Is Mocking Me Piano Cover",
	"the entertainer",
	"The Entertainer - Scott Joplin",
	"The Nuker 4",
	"The Nuker 4 (1)",
	"The Nuker 4 Audio Remake (Original Composition From TN1.5)",
	"The Nuker 4 Part 1",
	"the-real-slim-shady-eminem",
	"Theatre mhxa",
	"this is the talking",
	"this is what falling in love feels like JVKE",
	"Thundercat+-+'Uh+Uh'",
	"Time leaper",
	"Tokyo ghoul unravel mhxa",
	"TOKYOVANIA mhxa",
	"Tony Ann - Awakening",
	"Tony Ann - Desire",
	"Tony Ann - Discovery",
	"Tony Ann - Lost",
	"Tony Ann - Pulse",
	"Tony Ann - Rain",
	"Tony Ann Taurus",
	"Took Her To The O- King Von",
	"Took The O",
	"Touhou Bad Apple mhxa",
	"Touhou Owen was her v1 mhxa",
	"Touhou Owen was her V2 mhxa",
	"Trap royalty but impossible",
	"trillium",
	"Ultimate destruction",
	"Vaundy - Odoriko mhxa",
	"Vicetone nevada impossible",
	"vicetone-nevada",
	"Want to be Crem#ted/Ab#se mhxa",
	"We Are Number One MIDI (1).Mid",
	"We're Going To Be Friends (WIP)",
	"What Makes You Beautiful - One Direction (for Solo Piano)",
	"White Stripes (The) — We Re Going to Be Friends [MIDIfind.com]",
	"wifi skeleton - Nope your too late i already died (midi)",
	"Wind Of Fjords - Soft Knees",
	"Yiruma - River Flows In you mhxa",
	"Young Girl A mhxa",
	"Yuta Kakizaki - Tell Me The Moon Is Beautiful Mhxa",
}