-- Auto-updated by the Cloudflare Worker on upload/delete
return {
	" Erika  A German WW2 marching song",
	"(˃⤙˂˶ )Hmph It's Not Like I Like You or anything mhxa",
	"(˶ ｰ̀ ⤙ｰ́ ˶) It'SNot Like I Like You Or Anything Mhxa",
	"(Anybody Can Find Love Except You) Need Drums Mhxa",
	"[Black MIDI] RUSH E CURSED REMIX",
	"60375 Purnama-Merindu-",
	"âM ThầM BêN Em 2",
	"Azali - MECHANICAL GOD",
	"CơN MưA Ngang Qua",
	"CơN MưA Ngang Qua 2",
	"Doll Dancing",
	"Ending Shucks",
	"Feather - Nujabes",
	"Irida Cartoon V4",
	"Its Raining Tacos",
	"Its Raining Tacos.Mid",
	"KJ",
	"KJ V2",
	"KOBO KANAERO - HELP!! Mhxa",
	"Play Date",
	"Rush E (Impossible).Transformed",
	"Rush E (MIDI) (SYNTHESIA)",
	"Rush E 3 Real",
	"Rush E 4",
	"Rush E 4 No Lag",
	"RUSH N",
	"Samplab Screen-20260606-1108",
	"Screen-20260606-110846 06062026",
	"Screen-20260606-130710 06062026",
	"Ton 618",
	"Zedd-Clarity-20231118170709-Nonstop2k.Com",
	"Военные песни - Катюша (3) [MIDIfind.Com]",
	"Народные песни - Походный марш Люфтваффе (Немецкий) [MIDIfind.Com]",
	"아무것도 아님",
}