return {
    " Erika  A German WW2 marching song",
    "(˃⤙˂˶ )Hmph It's Not Like I Like You or anything mhxa",
    "1000 LIVING MILLENNIUM mhxa",
    "12 Variations of Twinkle Twinkle Little Star",
    "50 subs (100k notes) (1)",
    "6 TRILLION YEARS AND A OVERNIGHT STORY mhxa V2",
    "6 TRILLION YEARS AND AN OVERNIGHT STORY mhxa",
    "A STORY OF SIX TRILLION YEARS AND A NIGHT mhxa",
    "Ado - Gira Gira mhxa",
    "Ado - MIRROR mhxa",
    "Ado - Usseewa mhxa",
    "Alexander Rybak - Fairytale mhxa",
    "Anybody can find love except you mhxa",
    "At the speed of light(Bloodbath)",
    "BadLiZ, The Great Strategy (v4) GS2",
    "Beethoven - Moonlight sonata 3rd Movement IN mhxa",
    "Beethoven - Moonlight sonata 3th movement mhxa",
    "Beta0404",
    "Boywithluke - Problematic mhxa",
    "Broken World mhxa",
    "Bruno Mars - When i was your man",
    "buông đôi tay nhau ra x nắng ấm xa dần",
    "cause i love you x gạt đi nc mắt",
    "Celestial Opus",
    "chắc ai đó sẽ về",
    "Champagne Coast but piano cover mhxa",
    "Chipi chipi Chapa Chapa",
    "Chờ đợi có đáng sợ",
    "cocktail",
    "coffin nails   rapp snitch knishes",
    "Composition - Blue Sky (1)",
    "Confession of a rotten girl* mhxa",
    "Counting Stars by OneRepublic - Drums",
    "CupofJoe & Multo mhxa",
    "Dark dragon fire F-777 impossible",
    "Dark dragon fire-F777 (Avernus)",
    "Deco27 - Monitoring best friend remix mhxa",
    "Deco27 - Monitoring mhxa",
    "Deco27 - The vampire mhxa",
    "drag-me-down-twenty-one-two",
    "Eldoraudio-Rush E  original by Sheet Music Boss  NOTE  Impossible  ",
    "Engravings mhxa",
    "EnterSandman",
    "Erika piano",
    "Ethan Bortnick - cut my fingers off mhxa",
    "Evangelion - A Cruel Angel's Thesis Neon Genesis mhxa",
    "Every Living Breathing Moment mhxa",
    "flamewall",
    "Flower day mhxa",
    "forsaken-neon-by-dimrain47",
    "Fullmetal Alchemist - Brotherhood mhxa",
    "Golden Hour  JVKE Updated Ver 1772653873814",
    "Gooseworx - Your New Home MIDI (Your Piano Tutorials)",
    "Grant Steller - Every living Breathing Moment mhxa",
    "Gravity - Hazbin Hotel",
    "Gravity - Hazbin Hotel Season 2  Best remix",
    "Gravity (from Hazbin Hotel)",
    "Gravity (from Hazbin Hotel) maybe better",
    "Gravity Falls Theme",
    "Guns N Roses - Sweet Child O' Mine",
    "Harder rush e playable maybe",
    "hãy trao cho anh",
    "Hello- OMFG (WIP)(Copy)",
    "HELP!! Kobo kanaeru* mhxa",
    "Highscore",
    "I love you so The Walters",
    "I'm just a chill guy mhxa",
    "id 072019",
    "If I Am With You - I alone the hornored one mhxa",
    "Interstellar x Experience",
    "iris-goo-goo-dolls",
    "Isolation",
    "Jane! - The Long Faces - Topic (128k)",
    "JANGAN TUNGGU LAMA LAMA (Reggea Version) CICI FARAMIDA DEMO",
    "JVKE golden hour piano mhxa",
    "JVKE her mhxa",
    "Kaijuu Ni Naritai",
    "Kansas - Carry On My Wayward Son",
    "Kenshi Yonezu - Lemon mhxa",
    "KJUIMOG (Kim Jong Goon)",
    "Korn — A.D.I.D.A.S. (String) [MIDIfind.com]",
    "Lady Gaga - Judas mhxa",
    "Leviteto - LOL mhxa",
    "Lightning Moment",
    "Limbo isolation",
    "Looping The Rooms mhxa",
    "Lord kael - Sweetly",
    "Love story mhxa",
    "Luna Abyss",
    "Mac Miller - Congratulations",
    "Melly Mike  Young Black  Rich Official Music Video(1)",
    "Metallica-Enter-Sandman midi",
    "Michael Jackson - Billie Jean",
    "Moonlight Kokosei mhxa",
    "MrKitty-After-Dark-rlc-winston-20211103115423-nonstop2k.com",
    "Mundo x Your universe mhxa",
    "natori - sarushibai mhxa",
    "natori - serenade mhxa",
    "Natori propose mhxa",
    "Nevada - Vicetone",
    "Never-Gonna-Give-You-Up-3",
    "nguyện cầu đến 50 năm",
    "những lời hứa bỏ quên ost",
    "Night of Knights Lunatic mhxa",
    "no name (7)",
    "not yours",
    "Nuke powder",
    "oi josuke",
    "One Direction Night Changes ADVANCED",
    "Open+Window+vGH",
    "Outside",
    "Outside – Calvin Harris & Ellie Goulding - Piano Cover",
    "Pi the Song",
    "Random noises harder than rush e",
    "Red Sun in the Sky (天上太阳红彤彤)",
    "Ricochet Love Amethyst Part Piano arr 1776788643947",
    "Rush #1",
    "Rush Ab Optimized not impossible still very hard",
    "RUSH ABCD",
    "Rush Among Us 2",
    "Rush ANKHA Not impossible",
    "Rush Astronomia not impossible but hard",
    "RUSH B - ReBlacked",
    "Rush B playable",
    "Rush B playable i guess",
    "Rush Bad Apple impossible",
    "Rush Bad Apple not impossible",
    "RUSH BARBASHASSR",
    "Rush C# 3",
    "Rush D Optimized Still Possible",
    "RUSH DIGITAL CIRCUS (Remake)",
    "rush e",
    "Rush E (1.2M Notes)",
    "Rush E 2 (Impossible) (1)",
    "Rush E 2 but it's actually playable",
    "RUSH E 2 but its HAPPY",
    "Rush e 2 playable i guess",
    "Rush E 2 test",
    "rush e 3",
    "Rush e 3 playable I guess",
    "Rush E 4",
    "Rush E 4 Black Midi By S3G",
    "Rush E boss? mhxa",
    "RUSH E but something is OFF!",
    "Rush e fanchen ver I guess",
    "Rush e hard FIXED FIXED FIXED FIXED FIXED",
    "Rush E not impossible but still very hard fixed",
    "Rush E Optimized Fixed Fixed Fixed Fixed",
    "Rush E Optimized not impossible but still hard",
    "RUSH E Optimized not impossible but still very hard",
    "Rush E Optimized Not Impossible But Still Very Hard Fixed Fixed Fixed",
    "Rush E Optimized Not Impossible But StillHard Fixed Fixed",
    "Rush E Original + Midi Download",
    "Rush E original sheet i spend my money on",
    "Rush e playable",
    "RUSH E SMBs version pre-remaster",
    "Rush Eb Optimized not impossible but still very hard",
    "Rush Epic Games Fortnite",
    "RUSH F",
    "Rush Gigachad (Remake)",
    "RUSH HAPPY BIRTHDAY",
    "RUSH HOME ALONE (Remake)",
    "Rush Jingle Bells",
    "RUSH LGBT",
    "Rush lin gan guli guli impossible",
    "Rush Lin gan guli guli not impossible",
    "RUSH LRABER",
    "RUSH Lynes (fixed)",
    "RUSH MOSKAU",
    "Rush Mountain King Optimized not impossible but hard",
    "Rush Moutain King Lala version",
    "Rush of Life - Tony Ann",
    "Rush Piggies not impossible but hard.mjd",
    "Rush polish cow",
    "Rush Raining tacos impossible",
    "RUSH RICK ASTLEY (Remake)",
    "Rush Round And Round not impossible",
    "Rush Rush not impossible but hard",
    "Rush Sigma Boy not impossible but hard",
    "RUSH SM3DW",
    "Rush SM64",
    "RUSH SONICSPIANOONIRL REMASTERED",
    "RUSH STAR",
    "RUSH STAR (Remake)",
    "RUSH STEREO MADNESS (Remake)",
    "RUSH TWINKLE TWINKLE LITTLE STAR",
    "Rush USSR Optimized not impossible but hard",
    "RUSH VAJUSO",
    "Rush Victory",
    "Rush Vietnam remastered better and possible",
    "Rush Vietnam sounds bad btw midi by oganesson(Loadstringsgi)",
    "RUSH YOUTUBE - Kopie",
    "Rush Z not impossible but still hard",
    "Rush 悪ノ召使 (重制版)",
    "RUSH+ELISE",
    "Sheena Ringo - A double suicide mhxa",
    "Sheena Ringo -Crime & Punishment mhxa",
    "sinkingtown",
    "Smoke on the Water",
    "Smoke on the Water (Drum)",
    "Somewhere only we know mhxa",
    "Stalemate",
    "System of a Down - B.Y.O.B",
    "Tally Hall - The Bidding",
    "Tally+Hall+-+Turn+The+Lights+Off",
    "tau the song playable",
    "tegrtstrgy",
    "tháng 4là lời nói dối của em",
    "Thang dien impossible lol",
    "the entertainer",
    "The Entertainer - Scott Joplin",
    "the-real-slim-shady-eminem",
    "Theatre mhxa",
    "this is the talking",
    "this is what falling in love feels like JVKE",
    "Thundercat+-+'Uh+Uh'",
    "Time leaper",
    "Tokyo ghoul unravel mhxa",
    "TOKYOVANIA mhxa",
    "Tony Ann - Awakening",
    "Tony Ann - Desire",
    "Tony Ann - Discovery",
    "Tony Ann - Lost",
    "Tony Ann - Pulse",
    "Tony Ann - Rain",
    "Tony Ann Taurus",
    "Took Her To The O- King Von",
    "Took The O",
    "Touhou Bad Apple mhxa",
    "Touhou Owen was her v1 mhxa",
    "Touhou Owen was her V2 mhxa",
    "Trap royalty but impossible",
    "trillium",
    "Ultimate destruction",
    "Vaundy - Odoriko mhxa",
    "Vicetone nevada impossible",
    "vicetone-nevada",
    "Want to be Crem#ted/Ab#se mhxa",
    "We're Going To Be Friends (WIP)",
    "What Makes You Beautiful - One Direction (for Solo Piano)",
    "White Stripes (The) — We Re Going to Be Friends [MIDIfind.com]",
    "wifi skeleton - Nope your too late i already died (midi)",
    "Wind Of Fjords - Soft Knees",
    "Yiruma - River Flows In you mhxa",
    "Young Girl A mhxa",
}
